### ISSUE TITLE
Missing icons on nerd fonts

### ISSUE THREAD

**Issue by akex06** [ryanoasis/nerd-fonts#1033]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
There are missing icons on nerd fonts

Expected behavior:
There are missing 30% and 50% charging icons

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   Hack Nerd Font Mono Regular
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   https://www.nerdfonts.com/font-downloads
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   zsh
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   Linux, ParrotOS

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/67469268/209996274-aa92e759-5dd8-4b83-8cf2-a28ac3facedc.png)

**Comment by Finii** [comment]
From the screenshot I guess you mean 10% charging, 50% charging, and 70% charging.

The Material Design Icons version which we use does not have them:
![image](https://user-images.githubusercontent.com/16012374/210013385-d39af55e-4987-4fa9-8966-c316c4fe5401.png)

So we can not have them.

On the other hand, the _current version_ of Material Design Icons does have them, together with for example wireless charging icons:

![image](https://user-images.githubusercontent.com/16012374/210013544-fb5fbd69-c4bf-45a7-b2cf-ee027a4a2045.png)

Note that the 'old' icons have codepoints in the 4 hex-digit range (`F086`), while the current set grew so big that it went over to the 5 hex-digit range (`F0086`).

This is also the reason that we can not 'just update' - we would have a breaking change for the codepoints.

**But it will come**. With
* #773 

all the current Material Design Icons will come to Nerd Fonts (which in turn will grow in size, of course, unfortunately).

With `v2.3.0` (which had been scheduled to come out last month) Nerd Font will have both: MDI at the old and at the new codepoints - as transition to `v3.0.0` which will drop the old MDI codepoints.

So your problem is already solved, but not active at the moment.
