### ISSUE TITLE
△ and ▲ have different widths

### ISSUE THREAD

**Issue by jedahan** [ryanoasis/nerd-fonts#104]
#### Subject of the issue

△ and ▲ have different widths on Inconsolata complete, with or without mono. I'd expect them to be the same size, just one with an outline and one without.

iTerm2 on OSX

<img width="232" alt="screen shot 2016-09-23 at 12 11 25 am" src="https://cloud.githubusercontent.com/assets/32407/18773969/4cbecdfa-8122-11e6-8d69-d63440d2fc99.png">

Menlo 18 pt:

<img width="194" alt="screen shot 2016-09-23 at 12 12 33 am" src="https://cloud.githubusercontent.com/assets/32407/18773989/720581c6-8122-11e6-964f-a4c6dc66fa03.png">

**Comment by ryanoasis** [comment]
Hey just looked into this.. at first I thought there could be a problem with the original source font (because the patching doesn't modify those characters).

But after some testing are you sure you are not just using the 'small' version of one of the triangles and the other as large?

Could you provide the unicode value of each just to be sure?

Below is `Inconsolata for Powerline Nerd Font Complete.otf`
![selection_15_10_16_19 46 18_775x509_001](https://cloud.githubusercontent.com/assets/8083459/19414097/73053512-9310-11e6-9aac-6ae1007ff8d2.png)

I also quickly glanced at several other fonts via Character Map. Sorry but I cannot test on OSX.

Thanks

**Comment by jedahan** [comment]
Tried it in two terminals - iTerm2 and hyperterm (and terminal.app), all had the same issue. menlo is fine.

![screen shot 2016-10-16 at 1 53 33 pm](https://cloud.githubusercontent.com/assets/32407/19419551/fe8f3a3c-93a7-11e6-929d-511b6e91737a.png)
<img width="842" alt="screen shot 2016-10-16 at 1 53 24 pm" src="https://cloud.githubusercontent.com/assets/32407/19419552/fe9145fc-93a7-11e6-8e56-2d102c127955.png">

**Comment by ryanoasis** [comment]
@jedahan Thanks for trying it out again. I will take another look :smile:

**Comment by jedahan** [comment]
When I install, font book complains about 'ambiguous width' stuff, hopefully that helps
