### ISSUE TITLE
Arch links need an update

### ISSUE THREAD

**Issue by moralground** [ryanoasis/nerd-fonts#1057]
The AUR links are mostly broken now that the bulk of the fonts have been imported into Arch Linux's main repository:

https://archlinux.org/packages/community/any/nerd-fonts/

Some fonts remain in the AUR:

https://aur.archlinux.org/packages?K=nerd+font

I think it would be best to stop listing specific ones in the README and just put those two links somewhere for Arch users.

**Comment by Finii** [comment]
Thanks for the information.

Yes, maybe it would be better to just link to the search page. And then, iirc we had that before and people complained that there should be direct links. I assumed the packages to be more stable.

But I guess you are right.

Should the Arch packages still be listed under 'AUR', because, strictly they are not. Hmm.

Ah I see. Yes, I will change it. Thanks again!

**Comment by Finii** [comment]
_Note to self:_
Unrelated but related, the pkgver stuff, need to check if/how this works with `-git` packages.
https://github.com/ryanoasis/nerd-fonts/issues/573#issuecomment-770453386

**Comment by Finii** [comment]
Link to
* #771
