### ISSUE TITLE
New material design icon block icons are much smaller and thus less readable.

### ISSUE THREAD

**Issue by Dragon-Hatcher** [ryanoasis/nerd-fonts#1061]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Identical icons from the old and new material design blocks render much smaller in the new block and are thus less readable.

Expected behavior:
Identical icons from the old and new material design blocks should render the same.

Example symbols:
`U+F631` (Old) vs `U+F0132` (New)
`U+F503` (Old) vs `U+F0004` (New)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   -  `Symbols-2048-em Nerd Font Complete Mono.ttf`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Downloaded from the release page (version 2.3.1)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Linux Mint 21, Cinnamon

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/64214386/213830966-6f2913c9-8d76-4829-97ba-a6a29ad9ac62.png)
(Note that Kitty squishes icons into one cell when there is no trailing space and expands them to full size when there is. The first two icons in each section have a trailing space. Periods for scale. Here is the command I ran: `echo -e 'Old: U+F631    | U+F503    |\nNew: U+F0132 󰄲 󰄲 󰄲󰄲| U+F0004 󰀄 󰀄 󰀄󰀄|\n....................................'`)

**Comment by Finii** [comment]
Hmm. Will check the scaling. 
It differs in methodics. 

Anyhow, bigger symbols should be in Symbols Only Nerd Font.ttf (without Mono). Maybe :thinking:

I will have a look. 



________________________________
From: Dragon-Hatcher ***@***.***>
Sent: Saturday, 21 January 2023 02:06
To: ryanoasis/nerd-fonts
Cc: Subscribed
Subject: [ryanoasis/nerd-fonts] New material design icon block icons are much smaller and thus less readable. (Issue #1061)

🗹 Requirements
I have searched the issues for my issue and found nothing related and/or helpful
I have searched the FAQ for help
I have searched the Wiki for help
🎯 Subject of the issue
Experienced behavior:
Identical icons from the old and new material design blocks render much smaller in the new block and are thus less readable.
Expected behavior:
Identical icons from the old and new material design blocks should render the same.
Example symbols:
U+F631 (Old) vs U+F0132 (New)
U+F503 (Old) vs U+F0004 (New)
🔧 Your Setup
Which font are you using (e.g. Anonymice Powerline Nerd Font Complete.ttf)?
Symbols-2048-em Nerd Font Complete Mono.ttf
Where did you get the file from (download link, self patched, source downloaded from link...)
Downloaded from the release page (version 2.3.1)
Which terminal emulator are you using (e.g. iterm2, urxvt, gnome, konsole)?
Kitty
Are you using OS X, Linux or Windows? And which specific version or distribution?
Linux Mint 21, Cinnamon
★ Screenshots (Optional)

(Note that Kitty squishes icons into one cell when there is no trailing space and expands them to full size when there is. The first two icons in each section have a trailing space. Periods for scale. Here is the command I ran: echo -e 'Old: U+F631   | U+F503   |\nNew: U+F0132 󰄲 󰄲 󰄲󰄲| U+F0004 󰀄 󰀄 󰀄󰀄|\n....................................')

**Comment by Dragon-Hatcher** [comment]
Actually they are all small for me with the non mono version.
![image](https://user-images.githubusercontent.com/64214386/213901044-7db441f6-6315-42df-bf32-cf0d9d753cd4.png)

**Comment by Finii** [comment]
Hmm, in the font new (bottom) and old (top row) `account` is exactly the same size:

![image](https://user-images.githubusercontent.com/16012374/213935301-a756ae48-637c-4764-9e75-d4d8bd057d5f.png)

Well. The `Nerd Font Mono` font is (as I predicted ;) different. Here the scaling changed:

![image](https://user-images.githubusercontent.com/16012374/213935610-0b141d23-829e-4f95-884c-282584f3c879.png)

While the old scaling (top row) the icons are individually scaled, the new scaling produces different (usually smaller) scaling.
The reason is, and to show this I added `account-alert`, that related glyphs are scaled with the same factor.

Assume someone who wants to show `account` or `account-alert` in a table depending on some data. The 'person' is now the same size in both cases. Another usecase is a battery icon used to show the battery state. There is also a 'battery-broken' icon with a stroke-out battery, which would be smaller if scaled individually.

See more example for 'glyph sets' that should be all scaled identical for best user experience: https://github.com/ryanoasis/nerd-fonts/pull/773#issuecomment-1023497439

**Comment by Dragon-Hatcher** [comment]
Ah. I understand the rational for the resizing now. Does it make sense to keep the old ones different as an option for a larger scale then? Seems weird though considering they will be removed.

**Comment by Finii** [comment]
We could add individual scale-groups, but with 8000 icons that approach sounded rather maintenance intensive, or at least the initial work that has to be put into it is a bit high, given I'm just one person ;-D

So, I have no real solution for that, open for all suggestions.

**Comment by Dragon-Hatcher** [comment]
Oh. Are you saying that every icon is scaled the same amount as every other icon but they could be larger if someone put in the work to figure out which icons needed to be scaled together?

I might be willing to look into doing that. Would, for example, various sets of codepoint ranges be sufficent?

**Comment by Dragon-Hatcher** [comment]
This also creates some weird artificats like this:
![image](https://user-images.githubusercontent.com/64214386/214185460-f8427966-8325-4b11-a4cc-5aea11ed412d.png)
The King and Queen fill two cells but the rest of the pieces fit in just one so they look misaligned.
Do you think scaling these together would look better?

![image](https://user-images.githubusercontent.com/64214386/214185702-85bedc52-f9eb-439f-a6cc-f1691afb61f6.png)
New Vs
![image](https://user-images.githubusercontent.com/64214386/214186150-3144907f-505c-4674-b80f-f153ddf78da0.png)
Old

Same font scale

**Comment by Finii** [comment]
The chess pieces are all the same width:

![image](https://user-images.githubusercontent.com/16012374/214188404-07d3e2a6-fd39-4e01-8121-a1ab271e45b4.png)

Not sure how you create the output.

Codepoints `F0857` ff

**Comment by Finii** [comment]
> new vs old

I can check which glyphs make the scaling so small, it seems to be not the majority ;-)
But atm I need to solve 1068 :unamused:

**Comment by Dragon-Hatcher** [comment]
> The chess pieces are all the same width:
I believe Kitty scales based on rendered width not defined width. Not sure if anything can really be done about that.

**Comment by Dragon-Hatcher** [comment]
> I can check which glyphs make the scaling so small, it seems to be not the majority ;-) But atm I need to solve 1068 
Just eyeballing it perhaps U+F068D nf-md-solid is the issue? If not it may be a good baseline.

**Comment by Finii** [comment]
Well, `solid` fills the whole 512x512 design space, right.

But there are other glyphs that use the full dimension at least in some directions.
A combinded bounding box without `F068D` will still be 512x512.

![image](https://user-images.githubusercontent.com/16012374/214319481-93328967-d556-493d-ac5a-11d1ffd07791.png)

**Comment by Dragon-Hatcher** [comment]
Hmm. So do you think it is feasible to increase the overall scale or no?

**Comment by Finii** [comment]
Just from your image (old = individually maximized icons), it seems 'a lot' of pairs are ok, but not all
 
![image](https://user-images.githubusercontent.com/16012374/214499132-f3e6f6f4-7de1-4d8d-a5aa-9f8285252765.png)

Then here is a look at the original icons (bottom-left) and square-individually-scaled (top right).

![image](https://user-images.githubusercontent.com/16012374/214502550-1c156873-e184-48ac-8595-94a0f61b01f0.png)

They all go wrong as you see. Worst is the 'eject' that gets ridiculously big compared with previous-track.

**In principle** I guess we could change to 'maximize individually' and add "groups" of icons that should be handled as one. One needs to look at one square-ish scale (i.e. Symbols Only Mono) and one very slender and tall because problems might turn up only in one of them. I guess there are no fonts out there that are wider than tall, so we do not need to check that.

Keep in mind that some people use the font for terminals, but other use them to show icons in GUIs.

So the feasibility is just a matter of examining three sets of each 7000 icons (original vs (square / oblong)).
I certainly shy away from that work, as we _also_ want to update all the sourcefonts, check renaming, potentially drop Win-Compat, add Propo, improve website (docu), ... :grimacing:

**Comment by Dragon-Hatcher** [comment]
Alright. I'm going to close this then until someone wants to do the work of grouping several thousand icons. Thanks for clearing this up!

**Comment by Finii** [comment]
We could also solve this the other way around.

NOW scale each symbol individually, and add groups for glyphs when someone complains about some mismatch concretely.

What do you think? In fact that was the way we always handled it before :grimacing:
