### ISSUE TITLE
[Cousine Nerd Font] Adding round borderchars.

### ISSUE THREAD

**Issue by hungpham3112** [ryanoasis/nerd-fonts#1108]
- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
I'm using Cousine Nerd Font for display text and icon for vim terminal also gvim. Today, I worked with some settings with borderchars then I realized that Cousine Nerd Font not support it. I changed to Hack Nerd Font, it can display round borderchars like my expectation.
So I wonder if Cousine Nerd Font can have round borderchars 
`
 '─│─│╭╮╯╰'
`

**Additional context**

https://user-images.githubusercontent.com/75968004/216885210-68367f75-9411-4c14-b9e2-58be74e36a6a.mp4

**Comment by Finii** [comment]
Thank you for raising the Issue.

Maybe we should increase Powerlevel compatibility, triggered by discussion with @igniscyan

The next comments will show what would be needed.

---

Some links

This fits into another current discussion in
* #1122 

There are other related issues all over and also some changes
* #414
* 59c5cb5a1f33139b79838f010fafea26623ed046  `font-patcher: Patch in heavy angle brackets`

Maybe also consider again
* #780
* #272

**Comment by Finii** [comment]
[Powerlevel10k](https://github.com/romkatv/powerlevel10k) offers a specifically patched font for usage with their prompt system.

The patching is done [here](https://github.com/romkatv/nerd-fonts).

The changes consist of these commits
* 413b507c `fix box drawing characters, tune powerline glyph sizes and make all glyphs '1.18 * advance' wide`
* d0adb252 `allow negative bearings; move oversized glyphs 1/3 to the left`
* 90154ac4 `allow for missing block glyphs`
* 26d98f83 `add build`
* e5d35fdd `tweak font attributes (font, family, etc.)`
* 3eff1b47 `patch fonts in docker`
* 8a04d68e `reduce vertical oversizing by 33%, otherwise it looks awful in iTerm2`

Analyzing the changes

* Overlap increased to 3%, sometimes 2%
* ScaleGroups removed
* Existing glyphs `2500` - `25A0` all scaled to 3% Overlap h (2% v) with reference glyph `2588` (full block)

**Comment by 237dmitry** [comment]
What wrong with this characters?

![ArcoLinux_2023-02-15_13-44-14](https://user-images.githubusercontent.com/78153320/219006334-47ea4c8b-baf1-45eb-8c55-1c265e61bd74.png)

**Comment by Finii** [comment]
We do not patch them in. Some Nerd Fonts fonts have them (if the original font has them), some dont.
This is not so nice, because some ppl want to have them in any font.

If the original font has them already in and we do change the 'cell' size (which might happen), then the glyphs do not reach the border anymore or protrude too much out of the 'cell'. Because we just change the 'cell' size globally without rescaling exiting glyphs.

**Comment by Finii** [comment]
These are the few box drawing glyphs that are _really_ in Cousine Nerd Font:

![image](https://user-images.githubusercontent.com/16012374/219016873-b3d03b35-90d5-44ed-8138-0aeb03d75609.png)

**Comment by 237dmitry** [comment]
> hese are the few box drawing glyphs that are really in Cousine Nerd Font:

Why does `gucharmap` show these round borders? Terminal:

![ArcoLinux_2023-02-15_15-34-54](https://user-images.githubusercontent.com/78153320/219028958-870333d3-87ce-49f4-bd43-31ea3505ecae.png)

**Comment by Finii** [comment]
Your  terminal (whichever that is) substitudes it?

```
fc-list :charset=2570 | grep -i cousine
```

?

**Comment by Finii** [comment]
On my machine

```
$ fc-list :charset=2570 --format "%{family}\n" | sort | uniq
3270 Nerd Font
C059
CaskaydiaCove Nerd Font
DejaVu Sans
DejaVu Sans,DejaVu Sans Condensed
DejaVu Sans Mono
DejaVuSansMono Nerd Font
DejaVu Serif
DejaVu Serif,DejaVu Serif Condensed
Delugia
Fira Code
FiraCode Nerd Font
FreeMono
FreeSerif
Nimbus Mono PS
Nimbus Roman
Nimbus Sans
Nimbus Sans Narrow
P052
URW Bookman
URW Gothic
VL Gothic,VL ゴシック
VL PGothic,VL Pゴシック
Z003
```

despite current Cousine installed:

![image](https://user-images.githubusercontent.com/16012374/219046845-2329adaf-7713-493d-b60c-e2cd744cb8eb.png)

**Comment by Finii** [comment]
If you right click on the glyph in charmap it shows the glyph origin, on my machine it is DejaVu - despite the fact that I selected Cousine:

![image](https://user-images.githubusercontent.com/16012374/219049501-9d9d6769-34bc-44b7-bb58-a9710f9bad97.png)

**Comment by 237dmitry** [comment]
No, it does not support

```
 ~ $ fc-list :charset=2570 --format "%{family}\n" | sort | uniq
C059
DejaVu Sans
DejaVu Sans,DejaVu Sans Condensed
DejaVu Sans Mono
DejaVu Serif
DejaVu Serif,DejaVu Serif Condensed
Droid Sans
FantasqueSansMono Nerd Font
Nimbus Mono PS
Nimbus Roman
Nimbus Sans
Nimbus Sans Narrow
P052
Terminus
URW Bookman
URW Gothic
xos4 Terminus
Z003
```

**Comment by 237dmitry** [comment]
> it is DejaVu

Yes. So the `Cousine` somehow takes characters from another font? In that case, I'm sorry, I'm not an expert.

**Comment by Finii** [comment]
Tilix and charmap are written in a way that they use another font is the asked-for glyph is not in the selected font.

**Comment by Finii** [comment]
Note to self:

Cousine has negative rhs bearing at Aogonek :grimacing: 

![image](https://user-images.githubusercontent.com/16012374/219058536-a833d3c6-312b-4c19-819b-2fab640e38ad.png)

I thought there is one corner in the code that I do not need to touch, but ... alas .. that breaks our cell calculations that can not make up their mind if they want to take the advance width or the bounding box width.
