### ISSUE TITLE
Update Iosevka to 18.0.0

### ISSUE THREAD

**Issue by Defman21** [ryanoasis/nerd-fonts#1111]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
It's got a new major [release](https://github.com/be5invis/Iosevka/releases/tag/v18.0.0) which would be nice to have in the next version of Nerd Fonts.

**Describe the solution you'd like**
Update the font in the repo 😌

**Describe alternatives you've considered**
Not appliable.

**Additional context**
https://github.com/ryanoasis/nerd-fonts/issues/832

**Comment by Finii** [comment]
All source fonts will be updated for `v3.0.0`.

I already made a list some time back: https://github.com/ryanoasis/nerd-fonts/discussions/962#discussioncomment-3894678

Which is obviously outdated already. In the next days/weeks I will go through all source fonts and update to what is current on that particular day ;-)

Thanks for reminding :-) Closing because it is already on the plan.

**Comment by Finii** [comment]
At the moment I still think this is realistic :grinning: 

![image](https://user-images.githubusercontent.com/16012374/217754962-b6321a3b-7ab1-444e-8ba3-9e865beea376.png)

**Comment by Finii** [comment]
Issues down to ~100 ... but still room for improvement before `v3.0.0`:

![image](https://user-images.githubusercontent.com/16012374/217763340-f7de3713-9b96-4240-b36f-78b1cb53f281.png)

**Comment by Defman21** [comment]
>I already made a list some time back

Oh, sorry, I haven't even looked at the discussions 😅
