### ISSUE TITLE
Victor Mono vertical alignment?

### ISSUE THREAD

**Issue by nathanielevan** [ryanoasis/nerd-fonts#1116]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
After patched with options `-s`, `-l` and `-c`, Victor Mono's vertical alignment seems too low. Here's a comparison:
* Patched:
![scshot-120223-031044](https://user-images.githubusercontent.com/9361126/218279196-b12b83da-de27-4e4f-b9a1-30263be3c8be.png)
* Unpatched:
![scshot-120223-031059](https://user-images.githubusercontent.com/9361126/218279213-8ce779fa-e910-40b1-8c55-515f2ff79170.png)

Metrics:
metrics | unpatched | 3.5.1
:-------------------------:|:-------------------------:|:-------------------------:
Typo ascent | 1100 | 1200
Typo descent | -250 | -150
Typo line gap | 200 | 0
HHEA ascent |1100 | 1200
HHEA descent | -250 | -150
HHEA line gap | 200 | 0

Expected behavior:
Patched font retains its vertical alignment

**Comment by Finii** [comment]
Thanks for reporting, and with the detailed metrics.

Turns out we drop the gap instead of redistributing, because one sign is wrong.
I have no clue how that bug crept in :-(

---

Btw, I use `font-line` to check that kind of stuff.

```
$ font-line report src/unpatched-fonts/VictorMono/Regular/VictorMono-Regular.ttf
=== src/unpatched-fonts/VictorMono/Regular/VictorMono-Regular.ttf ===
Version 1.410
SHA1: 3365cea003978e423ff95a479db2965f69942ce5

::::::::::::::::::::::::::::::::::::::::::::::::::
  Metrics
::::::::::::::::::::::::::::::::::::::::::::::::::
[head] Units per Em:   1100
[head] yMax:           1306
[head] yMin:          -529
[OS/2] CapHeight:      800
[OS/2] xHeight:        618
[OS/2] TypoAscender:   1100
[OS/2] TypoDescender: -250
[OS/2] WinAscent:      1100
[OS/2] WinDescent:     250
[hhea] Ascent:         1100
[hhea] Descent:       -250

[hhea] LineGap:        200
[OS/2] TypoLineGap:    200

::::::::::::::::::::::::::::::::::::::::::::::::::
  Baseline to Baseline Distances
::::::::::::::::::::::::::::::::::::::::::::::::::
hhea metrics: 1550
typo metrics: 1550
win metrics:  1550
```
```
font-line report patched-fonts/VictorMono/Regular/complete/Victor\ Mono\ Regular\ Nerd\ Font\ Complete.ttf                   master ↑ 1 … 3 
=== patched-fonts/VictorMono/Regular/complete/Victor Mono Regular Nerd Font Complete.ttf ===
Version 1.410;Nerd Fonts 2.3.3
SHA1: 9907eee46ccd8601bafccd0f36f88f24227e0609

::::::::::::::::::::::::::::::::::::::::::::::::::
  Metrics
::::::::::::::::::::::::::::::::::::::::::::::::::
[head] Units per Em:   1100
[head] yMax:           1306
[head] yMin:          -529
[OS/2] CapHeight:      800
[OS/2] xHeight:        618
[OS/2] TypoAscender:   1200
[OS/2] TypoDescender: -150
[OS/2] WinAscent:      1200
[OS/2] WinDescent:     150
[hhea] Ascent:         1200
[hhea] Descent:       -150

[hhea] LineGap:        0
[OS/2] TypoLineGap:    0

::::::::::::::::::::::::::::::::::::::::::::::::::
  Baseline to Baseline Distances
::::::::::::::::::::::::::::::::::::::::::::::::::
hhea metrics: 1350
typo metrics: 1350
win metrics:  1350
```

**Comment by Finii** [comment]
After PR:

```
$ font-line report Victor\ Mono\ Regular\ Nerd\ Font.ttf
=== Victor Mono Regular Nerd Font.ttf ===
Version 1.410;Nerd Fonts 2.3.3-36
SHA1: d27acb443db1a69400ecabb9ffe04c0f0389c818

::::::::::::::::::::::::::::::::::::::::::::::::::
  Metrics
::::::::::::::::::::::::::::::::::::::::::::::::::
[head] Units per Em:   1100
[head] yMax:           1306
[head] yMin:          -529
[OS/2] CapHeight:      800
[OS/2] xHeight:        618
[OS/2] TypoAscender:   1200
[OS/2] TypoDescender: -350
[OS/2] WinAscent:      1200
[OS/2] WinDescent:     350
[hhea] Ascent:         1200
[hhea] Descent:       -350

[hhea] LineGap:        0
[OS/2] TypoLineGap:    0

::::::::::::::::::::::::::::::::::::::::::::::::::
  Baseline to Baseline Distances
::::::::::::::::::::::::::::::::::::::::::::::::::
hhea metrics: 1550
typo metrics: 1550
win metrics:  1550
```

**Comment by Finii** [comment]
@all-contributors Please add @nathanielevan also for bug :heart:

**Comment by nathanielevan** [comment]
Many thanks for the patch, however Fantasque Sans Mono seems to have failed patching:
```
Nerd Fonts: WARNING Font vertical metrics inconsistent (HHEA 2298 / TYPO 2348 / WIN 2298), using WIN
Redistributing line gap of 100 (50 top and 50 bottom)
Nerd Fonts: Error in baseline to baseline code detected
```
It's one of those fonts with inconsistent vertical metrics. Did a little debugging and it appears that specifically with this font it fails at the final check on [this line](https://raw.githubusercontent.com/ryanoasis/nerd-fonts/e69a025a8d19135563731529b0d5cd93b87608c3/font-patcher); here's what I got
```
check_win_btb: 2348 != our_btb: 2298
```

**Comment by Finii** [comment]
Merde!

I'm currently on the ice, skating with the kids, will look/fix asap.

Thank for checking, reporting, etc ❤️

**Comment by Finii** [comment]
Well, `get_btb_metrics()` can not be changed because that is how the baseline distances need to be calculated.

And also the last check is ok, I guess.

But what is shocking and wrong, maybe is this

```python
        # We use either TYPO (1) or WIN (2) and compare with HHEA
          # and use HHEA (0) if the fonts seems broken - no WIN, see #1056
          our_btb = typo_btb if use_typo else win_btb
          if our_btb == hhea_btb:
              metrics = 1 if use_typo else 2 # conforming font
          else:
              # We trust the WIN metric more, see experiments in #1056
              print("{}: WARNING Font vertical metrics inconsistent (HHEA {} / TYPO {} / WIN {}), using WIN".format(projectName, hhea_btb, typo_btb, win_btb))
              our_btb = win_btb
              metrics = 1
```

`metrics` can be 0, 1, or 2 (HHEA, TYPO, WIN).
We say we want to use WIN.
We set `out_btb` to WIN's value.
We set `metrics` to TYPO ??!

I need to read #1056 and find out why the code is wrong.
Also contradicting is (was) the comment in the top, 'use HHEA for broken fonts'.

**Comment by Finii** [comment]
Hmm, all fonts in `src/unpatched-fonts/FantasqueSansMono/` patch without the 'metrics inconsistent' warning?
It is also listed as problematic in my table https://github.com/ryanoasis/nerd-fonts/issues/1056#issuecomment-1396928839

Do you use a different Fantastique Sans Mono?

I see it with `Hermit` (tested just that one, because it is marked red on list above).

**Comment by nathanielevan** [comment]
Ah right, I forgot I was using the "large line height" variant -- it's available to download [here](https://github.com/belluzj/fantasque-sans/releases/tag/v1.8.0). Indeed I'm not getting that error with the regular version

**Comment by Finii** [comment]
Thank you so much for reporting and evaluating!

Fixed the issue in the two commits mentioned above.

:+1: :heart_eyes:

**Comment by Finii** [comment]
I should resign... :sob: 

```
$ ./gotta-patch-em-all-font-patcher\!.sh -cj /NerdFontsSymbolsOnly
# [Nerd Fonts]  Filter given, limiting search and patch to pathname pattern '/NerdFontsSymbolsOnly'
# [Nerd Fonts]  Total source fonts found: 2
# [Nerd Fonts]  Release timestamp is Sun, 12 Feb 2023 18:37:03 +0100
# [Nerd Fonts]  Processing font 1/2
# [Nerd Fonts]  Processing font 2/2
Nerd Fonts Patcher v2.3.3-44 (3.5.7) (ff 20220308) executing
Nerd Fonts Patcher v2.3.3-44 (3.5.7) (ff 20220308) executing
PythonUI_Init()
copyUIMethodsToBaseTable()
Nerd Fonts: Error in baseline to baseline code detected
Patcher run aborted!
```

There are too many special cases in the code.

Well, I will fix this silently en passant with (PR to be filled in)

**Comment by nathanielevan** [comment]
What are the results of `check_hhea_btb`, `check_typo_btb`, `check_win_btb` and `our_btb`? I'll see if I can help somehow. I'm currently also thinking of adding a flag for `font-patcher` to simply set the gap to 0 and not redistribute it

**Comment by Finii** [comment]
Thank you, but, the fix is the diff above. See 49e766281d83e8ead72edb9ccbb99af7bae5b0f7

Not redistributing the gap is not an option? That will destroy the original font vertical metrics.
If someone want to change the gap there are tools to just do that.

---

The names are `check_` + metric name + `_btb`. `btb` stands for baseline to baseline distance (i.e. "line height").

In the `check_` we have the results for after the gap redistribution and general metrics correction (where needed). All fonts will / shall have the same btb, regardless which client uses the font (they sometimes prefer different metrices). The will habe the same btb, even though we removed the gap. We need to remove the gap because we want to have powerline glyphs that touch from line to line i.e. have no gap.

`our_btb` is our target-btb. Sometimes the different metrics do not match and then we need to decide which btb is the "real" btb.

**Comment by gregbacchus** [comment]
Just to add to this, as it wasn't mentioned specifically (but possibly related) many of the icons in Victor Mono are higher up than others. 

e.g. U+E38A 

![image](https://user-images.githubusercontent.com/1761608/220536959-f167fac8-cd1d-44a5-874a-9ba624baa95c.png)
in SauceCode Pro

vs 

![image](https://user-images.githubusercontent.com/1761608/220537236-81f44a3b-d293-42d5-8ad3-f4f0aec9bca5.png)
in VictorMono

**Comment by Finii** [comment]
Thanks for reporting / showing this @gregbacchus 

To check I re-patched both fonts with the current `master` patcher, and this is how it comes out:

![image](https://user-images.githubusercontent.com/16012374/220545423-bfea09f6-157a-46d3-ab97-b037085b2e6c.png)

So I guess the problem is fixed :grimacing:

**Comment by gregbacchus** [comment]
Thank you @Finii, and great work, by the way!
