### ISSUE TITLE
Roboto has blank or missing glyphs for borders (used in vim's which key, telescope, terminal fuzzy finders in general)

### ISSUE THREAD

**Issue by digidoor** [ryanoasis/nerd-fonts#1128]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
No borders.
![roboto](https://user-images.githubusercontent.com/37601466/219904316-ef05af37-5da3-4b0b-87dd-dd53104e37bf.png)

Expected behavior:
Borders.
![2023-02-18 14_15_49-npm install types-registry@latest](https://user-images.githubusercontent.com/37601466/219904327-fbc0aa73-9519-4285-9cf7-d7f8c0ebec30.png)

Example symbols:
I don't know the codepoint for these non-text glyphs. The fastest way to see these borders for me is to open helix (text editor) and use `<Space>` to get a little context menu. This is the same border that is used in neovim's telescope plugin, and I believe vim and neovim's which key plugins, so those would also work. The working screenshot is Iosevka and all other Nerd Fonts I've tested work except for Roboto.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Roboto Mono Nerd Font Complete Mono Windows Compatible.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   Here, directly, as well as using the giant install script. Same results either way.
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - it's the cmd.exe window via git for windows or MINGW64 or whathaveyou.
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows 10.

#### ★ Screenshots (Optional)
![2023-02-18 15_43_44-npm install types-registry@latest](https://user-images.githubusercontent.com/37601466/219904452-47192e34-ef81-4097-913c-23961ba92040.png)

**Comment by Finii** [comment]
Thanks for reporting this.

Nerd Fonts does not patch in the border glyphs. Either the font did have them to start with, or they will also not be in the patched font.

But fear not, others also noticed the problem
* #1108

and because it (that we do not touch them) proses possible problems (whatever, the details are not important here), we have this:
* #1125 

I guess that it will be incoporated in the next days and will then be part of `v3.0.0`.

If you need the font earlier, you can patch with the patcher from the PR branch, or wait until it has been merged and then use the docker or zip archive to self-patch (which is easier than patching from a branch).

**Comment by digidoor** [comment]
> I guess that it will be incorporated in the next days and will then be part of `v3.0.0`.
That's fantastic news. I look for ward to it.
