### ISSUE TITLE
f000-f003 not rendering for Symbols Nerd Font (Symbols Only)

### ISSUE THREAD

**Issue by pcattori** [ryanoasis/nerd-fonts#1149]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
While using [LazyVim](https://www.lazyvim.org/), I noticed that `f002` (magnifying glass) was not being rendered correctly in the dashboard.

I also ran the [`test-fonts.sh` script](https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/test-fonts.sh) locally and spot checked the glyphs. All the ones I sampled were rendered correctly except for the f000-f003 range.

I also tried with the Fira Code Nerd Font and saw the same results.

Expected behavior:
`f002` should render as the Font Awesome magnifying glass

Example symbols:
- f000: 
- f001: 
- f002: 
- f003: 

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Fira Code + Symbols Nerd Font (Symbols Only)
   - Also tried with Fira Code Nerd Font
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - `brew install --cask font-symbols-only-nerd-font`
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - `iterm2`
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - MacOS 12.6

#### ★ Screenshots (Optional)

<img width="930" alt="Screen Shot 2023-03-19 at 10 37 26 AM" src="https://user-images.githubusercontent.com/1477317/226183194-3f724b14-a21f-411a-ab3e-71fc71e26984.png">

<img width="465" alt="Screen Shot 2023-03-19 at 10 29 46 AM" src="https://user-images.githubusercontent.com/1477317/226183015-dbc65e2f-e1cf-4268-867e-8366d83ef528.png">

<img width="856" alt="Screen Shot 2023-03-19 at 10 35 09 AM" src="https://user-images.githubusercontent.com/1477317/226183040-9255ae0f-d55a-4a31-8d43-96ae0d3e4b6c.png">

**Comment by Finii** [comment]
Hmm, glyph is in the font file

<img width="912" alt="Screenshot 2023-03-20 at 07 28 17" src="https://user-images.githubusercontent.com/16012374/226263702-971b0865-7e12-4f2b-a6a2-2da553c6375b.png">

But is seem to not render ...

<img width="959" alt="Screenshot 2023-03-20 at 07 49 00" src="https://user-images.githubusercontent.com/16012374/226267053-cdb5a0b2-7c56-4916-ad37-9eb3a04d68fe.png">

Which is a iTerm problem, because it **does render** in `Terminal`:

<img width="1285" alt="Screenshot 2023-03-20 at 07 54 00" src="https://user-images.githubusercontent.com/16012374/226267989-2e144a19-ddae-40ca-94b7-c861ef6531ac.png">

**Comment by Finii** [comment]
iTerm always renders them differently....

<img width="958" alt="Screenshot 2023-03-20 at 07 58 33" src="https://user-images.githubusercontent.com/16012374/226268894-0ac5e15d-630c-49f1-ae10-60c8ebba0f23.png">

_Note that the glyph_ does _change, but still is not the default unknown glyph glyph_

I searched `iTerm`'s website but did not find an explanation there.
Also did not find anything here https://gitlab.com/gnachman/iterm2

As this is clearly some strange behavior of `iTerm`, closing the issue here. Maybe you should open an issue over there.
Probably it is for a good reason that they do what they do.

**Comment by Finii** [comment]
Ah, see this:

https://gitlab.com/gnachman/iterm2/-/issues/7570

It should have been fixed with https://gitlab.com/gnachman/iterm2/-/commit/03653f3f8760ee1a82bf0f099a5ab325c018d75a

That is one year ago, how old is my iTerm :thinking:

**Comment by Finii** [comment]
https://gitlab.com/gnachman/iterm2/-/issues/10431#note_1005459893

![image](https://user-images.githubusercontent.com/16012374/226277924-e4e5e10b-1214-44fe-8e17-57ade449972a.png)
