### ISSUE TITLE
Import glyphs from JetBrains Mono

### ISSUE THREAD

**Issue by AndrewP-GH** [ryanoasis/nerd-fonts#1158]
**Requirements**

I have pathed my font from the Internet (Berkeley font) via `nerdfonts/patcher:latest`, but I see, that glyphs are not the same as in **JetBrains Mono**. How can I import the glyphs pack from **JetBrains Mono nerd font** or get parameters which were used when this font was created?

**Comment by Finii** [comment]
Without more information I can only speculate...
Did you give `--complete` as option?

**Comment by AndrewP-GH** [comment]
Yes, I have tried in my experiments.
1) -l -c --careful
2) -s -l -c --careful
3) -l -c
4) -l -c --variable-width-glyphs -s
It's interesting, that I'm facing this problem in Iterm2 on mac.
The same happens with other installed nerd fonts, except jetbarains mono (look at attached imgs)

<img width="1192" alt="Screenshot 2023-04-04 at 21 56 37" src="https://user-images.githubusercontent.com/9119924/229893108-273a5bc1-deef-42e6-9179-3e5c2a45c0ae.png">
<img width="1195" alt="Screenshot 2023-04-04 at 21 56 54" src="https://user-images.githubusercontent.com/9119924/229893115-ce2cb1c5-731e-4ad1-80ab-d4db24871731.png">
<img width="1188" alt="Screenshot 2023-04-04 at 21 57 04" src="https://user-images.githubusercontent.com/9119924/229893117-2eafc3b0-a9fa-43c9-a61c-fed842e6359f.png">
<img width="1191" alt="Screenshot 2023-04-04 at 21 57 15" src="https://user-images.githubusercontent.com/9119924/229893120-67ab3eca-62bf-4397-bfc5-4a53597fccdf.png">

**Comment by Finii** [comment]
Hmm, unfortunately you did not fill in the issue form...

Lets examine the 4 images you appended:

![image](https://user-images.githubusercontent.com/16012374/230929543-459f6add-3937-4ee1-90aa-9eaa148c3168.png)

You write
> 1. -l -c --careful
> 2. -s -l -c --careful
> 3. -l -c
> 4. -l -c --variable-width-glyphs -s

What I see is the the two middle ones (number 2 and 3) have a smaller whale or what that is (docker?); meaning they are the `--mono` (or `-s`) ones, which contradict what you write. You can also read it in the font names in the iTerm settings, the two middle ones have a `Nerd Font Mono` font while the first and last have a `Nerd Font` (without `Mono`) font:
1. BerkeleyMono **Nerd Font**
2. FiraCode **Nerd Font Mono**
3. Hack **Nerd Font Mono**
4. JetBrainsMono **Nerd Font** (Propo?)

(So you command line snippets do not match the images.)

Ah but the helm (Kubernetes?) thing is different. Is THAT what you mean?

`-l` is rather useless, any specific reason you use it?

Why do 1 and 2 have `--careful` and 3+4 not?

It is not easy to even understand what your problem is.
