### ISSUE TITLE
Space Mono Ligature fi looks strange

### ISSUE THREAD

**Issue by Fxzzi** [ryanoasis/nerd-fonts#1187]
#### 🗹 Requirements

- [ X ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ X ] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ X ] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Ligatures should be shown with Space Mono NF. When typing `'fi'` there is a space after and they are stuck together as shown here
![image](https://user-images.githubusercontent.com/18248986/235455202-d187722a-4870-42f6-9ba1-2c137ff1c95c.png)

Expected behavior:

The ligatures for => and ==> are not included and / or shown using this font.

Example symbols:

`->=> ==> fi`

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_
   - SpaceMonoNerdFont-Regular.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - TTF from releases page (packaged in pacman repo)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - 
   - Kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - 
   - Arch Linux with Kernel 6.3.0

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/18248986/235455658-8cd02374-1a9f-4cc7-8f15-593efa22743a.png)

**Comment by wjcostel** [comment]
Maybe the name of the font has changed (on the system)?  I just had this happen to me after an update and I went back to the config files and opened up Font Manager and plugged in the names of the fonts as they appeared in Font Manager.  I'm not entirely sure though because I may have two versions of the same font (nerd font & non-nerd font) and now I'm just telling the dotfiles to refer to the non-nerd font versions.

**Comment by Finii** [comment]
Can you show your kitty conf?

Ah, if I remember correctly I was unable to turn on (?) any ligatures in kitty. Is there a trick?

Hmm, but even in Writer there seem to be no ligs?

![image](https://user-images.githubusercontent.com/16012374/235460929-3d1c9554-abd9-42ae-a382-6faa0989f0a7.png)

otoh...

![image](https://user-images.githubusercontent.com/16012374/235461218-0c4c2e43-64d1-4877-870b-945cf4858b6a.png)

**Comment by Finii** [comment]
Ah, when looking on that...

The `fi` ligature is just one character wide. That is not supported by `kitty`. If you type two letters it has to occupy too `cells`.
Kitty has very strong opinions about how things have to be and does not try to do what you might want.

Suggest: Use some other terminal.

**Comment by Finii** [comment]
You are right! :-)

![image](https://user-images.githubusercontent.com/16012374/235463923-7cc12589-02c3-4b17-943c-a89892c5cfbb.png)

Well, the `fi` and `->` are encoded in the font to be just one cell wide, this is not supported by Kitty which is very unflexible.
Probably the `=>` has also not the expected-by-kitty width.

Compare Kovid's answer here
* https://github.com/kovidgoyal/kitty/issues/6220#issuecomment-1526937601

Note that in that concete issue the ligature IS exactly n chars long, but still ... must be a font issue :roll_eyes: 


So.. Sorry. The font and the terminal are not compatible. You will have the same issue with the unpatched font.

**Comment by Fxzzi** [comment]
Any terminal you'd recommend? And a config for ligatures?

**Comment by Finii** [comment]
Personally I use `tilix`, because that does not assume anything about the font and allows everything (*). Which makes it 'dead slow' of course (will, I never dump megabytes of logfiles, so it does not matter. I know how to `grep` ;).
I mainly use tilix for the tiling of course, and because I can sync-type in a multiple windows (I mean tiles). In this way I can `sudo apt update` on 20 machines in parallel for example.

And although I'm a command line person and was used to X configuration stuff (in 198x), I really like a terminal with a settings dialog and not a text file.

In total I have no clue which terms are good or bad. Kitty turns up in issues here often because of inflexibility. Maybe Tilda is also blanzingly fast - but I always have to self build because it does not work with my graphics cards :roll_eyes: 

Before `tilix` I used `Gnome terminal` (laugh) and `Terminator` (you see speed is not my problem).
My 'reason' for `tilix` is simple just the first tiling thing a found by change after `terminator` got problematic because of Python versions.

(*) Some years back I did couple of Erlang and other functional languages, and there proportional fonts are not seldom used. So a terminal that can run any (also proportional) fonts is what I like more.

**Config for Ligs** Well, maybe you can turn ligs off with Kitty, if that helps you. How, I don't know. My eyes always already glace over when I need to remember that shift-ctrl-f2 starts the settings (O_o)

**Comment by Fxzzi** [comment]
Wondering if this can be reopened. Regular apps which don't even support ligatures (as far as I know) are also experiencing the issue with the `fi`

See this screenie from dunst 
![image](https://user-images.githubusercontent.com/18248986/235508255-a7bff867-ce9a-40e6-9165-43154d91c30f.png)

If you need any more info please do not hesitate to let me know

**Comment by Finii** [comment]
But that is how Space Mono is intended to look?
See here on Google Fonts, the unpatched/original Space Mono:

![image](https://user-images.githubusercontent.com/16012374/235609156-7c8cf46b-4db6-4656-9ba5-decc82243351.png)

You just need to turn ligatures off in your terminal.

Otoh, that lig is really ... bad looking. We could of course remove it on patching. But usually the patched fonts do not differ from the original, they just get more glyphs.

We can reopen...

**Comment by Finii** [comment]
Thanks for persisting there must be a bug :-D

@allcontributors please add @Fxzzi for bug
