### ISSUE TITLE
TL;DR Section

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#124]
#### Create TL;DR section

Create a TL;DR section in the readme, particularly because of how long the install section has become

**Comment by nathanchere** [comment]
Agreed, a thorough but concise TLDR section would be very helpful. Especially when you have things like option 1 saying to run ./install.sh (from where? If you download just that file it doesn't work because it looks for /patched-fonts directory, but you also repeatedly say don't clone the entire repo, so wtf?)

**Comment by ryanoasis** [comment]
@nathanchere Yep thank you. I see your point that it is _not_ very clear and in this case very contradictory :blush:

**Comment by zeorin** [comment]
@ryanoasis I considered downloading the files individually when I was updating install.sh. In fact, this is probably a better course of action than assuming someone is going to download the whole repo.

The reason I didn't is because there was a warning somewhere that we shouldn't count on the file paths, they may change. If the file paths are considered dependable (especially if we use some way to search the right release/branch), then I can modify install.sh to download files instead of copying them.

**Comment by ryanoasis** [comment]
Yeah actually the way things are now I would agree it would probably be better for the install script to download the fonts from the repo (at least that'd be my vote at the moment).

The file paths should be more reliable now (at least on 1.x versions) the one thing that will probably change on the minor version changes could be the filenames themselves.

Also since 1.0.0 I believe some of the options on the install script are no longer relevant (minimal and the other patches options) because we have removed all but the Complete variations to do repo size concerns.

**Comment by ryanoasis** [comment]
For now I think we will rewrite and condense (combine) some of the installation options as they stand now. Per @nathanchere there are some obvious contradictions :blush:
