### ISSUE TITLE
\ue0b4 cuts half of the previous character

### ISSUE THREAD

**Issue by 237dmitry** [ryanoasis/nerd-fonts#1240]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

The last update to version 3.0.1 brought many unforgettable minutes of rewriting and debugging scripts. When will you finish experimenting with users?

The essence of the problem. Character number '\ue0b4' began to eat half of the previous character. This happens with any of the installed fonts.

Expected behavior:

Fonts should not be globally changed every minor release 

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_

```
AgaveNerdFont-Bold.ttf
AgaveNerdFont-Regular.ttf
DroidSansMNerdFont-Regular.otf
FantasqueSansMNerdFont-Bold.ttf
FantasqueSansMNerdFont-BoldItalic.ttf
FantasqueSansMNerdFont-Italic.ttf
FantasqueSansMNerdFont-Regular.ttf
TerminessNerdFont-Bold.ttf
TerminessNerdFont-BoldItalic.ttf
TerminessNerdFont-Italic.ttf
TerminessNerdFont-Regular.ttf
```
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - 
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - 

Tilix, xfce4-terminal

- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - 

Linux

#### ★ Screenshots (Optional)

![font](https://github.com/ryanoasis/nerd-fonts/assets/78153320/80d5dd3e-f535-41c6-baf9-a34629bae79d)

**Comment by Finii** [comment]
Sorry to hear of your problem.

Does that also happen with a normal letter before `e0b4`?
The glyph looks good

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/e6ff7497-5566-4e88-a56f-0f735f107d69)

It looks more the problem is the dot thing, that took 2 cells before:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/f4527c07-a2f6-4b67-8cbc-1811dfe9f9dc)

Do you have its codepoint?

**Comment by Finii** [comment]
Might be `ea71`, I will check, but please report which it is in your case.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/921ea3e9-05a2-4569-a497-d4e29022ceac)

**Comment by 237dmitry** [comment]
> The glyph looks good

I think this behavior for  every symbol from "User Private Area". There was not this issue in 3.0.0.

PS. `ea71` the same.

**Comment by Finii** [comment]
I believe `ea71` has a bug, but the glyph is unchanged compared with 3.0.0 (it's exactly the same in 3.0.0 and 3.0.1).

**Comment by 237dmitry** [comment]
> I believe ea71 has a bug, but the glyph is unchanged compared with 3.0.0 (it's exactly the same in 3.0.0 and 3.0.1).

Maybe the other characters are aligned more to the right than before? I am not an expert. I tested random characters and got the same result.

**Comment by Finii** [comment]
Would be good to get screenshots of the random other issues together with the codepoints, then I can try to reproduce.

I myself also use Tilix :thinking:


________________________________

**Comment by Finii** [comment]
But this is expected behavior? You need to add a blank after an over-wide symbol?
That does not happen only with `e0b4` but with everything, you can try a `X` or something.

See also [this](https://github.com/ryanoasis/nerd-fonts/discussions/1103#discussioncomment-4852120) for an explanation. If you do not want to add a blank you need to either use `Nerd Font Mono` or `Nerd Font Propo`. But `Ner Font` needs blanks after a symbol.

**Comment by 237dmitry** [comment]
> But this is expected behavior? You need to add a blank after an over-wide symbol?

No. I need the way it was before. No extra space after the character followed by e0b4.

I tried `Propo` fonts variant, nothing changed.

**Comment by Finii** [comment]
Yes, the `ea71` has a bug, as I said.
Try your nice script with 3.0.0.

**Comment by Finii** [comment]
In your own screenshot you see that it is not `e0b4` that is 'wrong', but for example the colon `:` also 'eats half of the size of the previous icon':

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/35a93d76-01bf-42cf-9091-63ae56e2bfc5)

The icons are all wider than one cell, means that they 'overhang' into the next cell, which happens to contain `:` or `E0B4`, or whatever. That is what a `Nerd Font` font promises. This is different for both other variants, `Nerd Font Mono` shrinks the icons down to be only one cell wide, while in `Nerd Font Propo` the icons are as wide as they look like (which means the font is not monospaced anymore).

The filled circle has a bug, and some few other icons, they are too far to the right.

**Comment by 237dmitry** [comment]
> in your own screenshot you see that it is not e0b4 that is 'wrong'

I do not know WHAT IS WRONG. You should know it better. You changed fonts settings. Please, do not change they every release. All was perfect in 3.0.0... And yearly was too.

**Comment by Finii** [comment]
@237dmitry Reverted the change with #1261 (i.e. `font-patcher (4.3.4)`).
Sorry for the problems!

**Comment by 237dmitry** [comment]
3.0.2 Nothing was changed

**Comment by Finii** [comment]
Well, I can definitively see the change

### 3.0.2
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/2c86d3a7-450b-43f4-aa22-9db8c3a7359d)

### 3.0.1 (image taken from above)
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/921ea3e9-05a2-4569-a497-d4e29022ceac)

#### And this is your original problem statement:
![font](https://github.com/ryanoasis/nerd-fonts/assets/78153320/80d5dd3e-f535-41c6-baf9-a34629bae79d)

The circle-filled is not cut anymore.

**Comment by 237dmitry** [comment]
> The circle-filled is not cut anymore.

`e0b4`, not circle. I try to point to it two releases in row. Once more time -- `e0b4` cuts some previous characters.

![238311293-35a93d76-01bf-42cf-9091-63ae56e2bfc5 1](https://github.com/ryanoasis/nerd-fonts/assets/78153320/91c93acf-f247-45a1-a5fd-2142ac655f87)

**Comment by Finii** [comment]
Did you even LOOK at the image you just posted?

Do you see that the colon (`:`) is ALSO on top of the icons (in the left row, where I draw the arrows), just not so obvious because the color is the same gray for the icon and the colon.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/60b2e2bc-cfe3-4711-8a30-bb72d000cb90)
_Simulation of colored colon_

> Once more time

Yes, this is the last time I point you to your misunderstanding. But as you have written before, you are not interested in understanding things; while yelling at me seems appropriate?

One final remark: If you do not want the symbol to overflow into the next character you need to use a different Nerd Font variant.
What you show is `Nerd Font`, what you probably want is `Nerd Font Propo` or if you are in a terminal `Nerd Font Mono`.
Please read https://github.com/ryanoasis/nerd-fonts/discussions/1103#discussioncomment-4852120.

**Comment by Finii** [comment]
In this script of yours:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/77f6ddf4-df8d-45d9-90c6-363e098054c7)

Replace the `"'u{fe04b}"` with `"M"` and see if the letter M is also broken :roll_eyes:

**Comment by 237dmitry** [comment]
> `e0b4` cuts some previous characters.
>> and see if the letter `M` is also broken roll_eyes

Some. Not of all, mainly from "Private Use Aria" block (in range `e000..f8ff`)

> What you show is Nerd Font, what you probably want is Nerd Font Propo or if you are in a terminal Nerd Font Mono

I tried Propo and Mono. No difference.
