### ISSUE TITLE
New glyphs on `Font Logos`

### ISSUE THREAD

**Issue by hasecilu** [ryanoasis/nerd-fonts#1281]
**Requirements**

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
There is a lack of Linux glyphs (projects related to Linux, distros, Desktop Enviroments, Window Managers, maybe some applications).

**Describe the solution you'd like**
I made a PR to [font-logos](https://github.com/lukas-w/font-logos) projects like a month ago -> https://github.com/lukas-w/font-logos/pull/93
But it seems there no much changes over there, the last merget commit was one year ago.
I added about 30 new logos of some popular/well known projects and would like that get merged here on NF.  
To be honest my main reason to have these logos merged it's to used them on `neofetch`.

![Screenshot from 2023-06-02 12-19-05](https://github.com/ryanoasis/nerd-fonts/assets/53124818/8e08a21d-69b8-47de-8807-8f2a5c1afc1f)

![Screenshot from 2023-05-23 14-49-12](https://github.com/ryanoasis/nerd-fonts/assets/53124818/4229e14e-48db-4e4b-9b64-c579428217b5)

**Describe alternatives you've considered**
I created a **temporal** branch where I merged the new logo glyphs, some unmerged PR there, and addressed some issues. I understand that the original maintainer can be busy so until the main repo is on again I could add/maintain it for a bit.

Here it's the branch: https://github.com/hasecilu/font-logos/tree/testing

Relevant/new glyphs: from f330 to f34d

Any recommendation? Do you think is viable to have this merged here on Nerd Fonts?

**Comment by Finii** [comment]
Very good work!
Ah, yes, indeed Lukas seems to have stopped doing stuff about a year ago. Also my PR there is still in the waiting.

The problem comes when we use a branch or temporarily a fork of Font Logos, if Lukas starts updating and uses different codepoints then we a problem:
* For example we use your PR and add `Vanilla OS` at `F34B`
* Lukas adds some other icons first, and only then adds your icons. So he will put `Vanilla OS` at `F352` (example)
* How do WE update Font Logos?

We can either pull Font Logos normally, but then we have some Nerd Font releases where Vanilla OS is on one codepoint, and later it is on another codepoint.
We can pull Font Logos but reorder the icons to fulfill the codepoint guarantee [1], but that still means that the codepoints for Vanilla OS are different when you use Font Logos directly or use Nerd Fonts.

There is not really a good solution for this.

Ah, look here, this looks like neovim:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/61ffca8a-e775-4976-838f-67d2147fef2f)

That does not really belong into Font Logos and will probably not be pulled. If we add this here it will lead to confusion. But then, maybe Lukas thinks it is good to add that.

Otoh, 1 (one) months waiting for you PR is not long for normal repos. I believe people are a bit spoilt with how fast it is _at the moment_ at Nerd Fonts; that was also much more relaxed (i.e. slow in adopting) in previous years, and that can change any day.

I close this for now, be can see if Lukas does something in the next months. Feel free to ping here then.

[1] Once a glyph got a codepoint allocated the codepoint will NOT change even on glyph updates, only in exceptional cases it is dropped completely

**Comment by Finii** [comment]
And I like neovim ;-)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/e1564acd-0e88-45e1-ab53-dfc45371c20b)
_My laptop_ :grin:
