### ISSUE TITLE
Caskaydia Cove introduces ligature issue not in Cascadia Code

### ISSUE THREAD

**Issue by Kissaki** [ryanoasis/nerd-fonts#1291]
Testing in Windows Terminal - font size 12, Windows 11, NF v3.0.2

I would expect the ligature for `=>` to be the same and without visual artifacts.

Cascadia Code:

![image](https://github.com/ryanoasis/nerd-fonts/assets/93181/e6bd7aac-408f-4eae-90d6-230e0b44b136)

CaskaydiaCove Nerd Font Mono:

![image](https://github.com/ryanoasis/nerd-fonts/assets/93181/08f0c635-ff35-4b68-a9a0-ab77ad0ace68)
 

#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Comment by Finii** [comment]
Oh, sorry to hear that. Lets find the reason.

Works in `Writer`

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/330ef965-1adb-4495-874d-e5b745511941)

**Comment by phjordan** [comment]
I see the same, in Windows Terminal as well as in VS Code, Nerd Fonts 3.0.2

![image](https://github.com/ryanoasis/nerd-fonts/assets/27995479/e80e1ae6-1ad1-4ed6-8c3c-41de1c886627)

**Comment by Finii** [comment]
Can not reproduce on Win10, VS Code 1.71.0, NF 3.0.2:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/98fbcd87-23c0-4326-97ee-1d2ec72bb871)

My settings:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/d4bf0148-8fa1-4c6d-b2e3-3ce1751f1eb5)

**Comment by Finii** [comment]
The problem with `Windows Terminal` is that they bundle Cascadia Cove (VF) with it and one can not uninstall it, which I hate.

Installing that thing now, hold tight.

**Comment by Finii** [comment]
@phjordan  Btw, please share a picture of your `config.json` and maybe a view of the font settings dialog with 'cas' as search term:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/11e86b05-f853-4fac-b1d5-87670824604f)

You see I have no Cascadia Code installed. I unpacked the Caskaydia zip file, select all, right click, install (for user) (is how I installed the fonts).

**Comment by Finii** [comment]
Can see it with `Windows Terminal`:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/e29378bf-c0ab-48b5-825b-34c35031dc21)

(:thought_balloon: Now I can not restart VS Code, great)

**Comment by Finii** [comment]
* Could not start VS Code
* Revert changes in config.js - still not opening
* Remove VS Code via 'apps'
* Reinstall VS Code via MS Store - problem: can not install
* Reboot
* Reinstall VS Code via MS Store - problem: can not install
* Download VS Code `msi`
* Install - can not overwrite old files?
* Reboot / manual deletion of old files
* Install ok
* Start ... still not opening

Windows is so easy, everything works out of the box!

**Comment by phjordan** [comment]
Here are my font settings, Both 'Cascadia Code' and 'CaskaydiaCove...' are installed for all users.

![image](https://github.com/ryanoasis/nerd-fonts/assets/27995479/5ce22e5b-a48d-41ad-b653-3e07ca642d2d)

I noticed that the `editor.fontSize`-setting does have an effect. I don't know anything about font rendering and scaling, but maybe this observation is of help. With 'Cascadia Code' set as font, the arrows seem fine for all font sizes.

My original VS code settings.json:
![image](https://github.com/ryanoasis/nerd-fonts/assets/27995479/0c964abd-a533-4e8f-9c48-3a94f078b044)

It looks fine with `editor.fontSize` commented out:
![image](https://github.com/ryanoasis/nerd-fonts/assets/27995479/b74fea9f-8b82-4d10-a787-012b7a507a14)

It looks fine with font size 14:
![image](https://github.com/ryanoasis/nerd-fonts/assets/27995479/9286a51e-0de5-4f46-b2ea-7d056b7a8f7b)

Font size 12:
![image](https://github.com/ryanoasis/nerd-fonts/assets/27995479/981f03b6-3dbb-4913-829f-afdc4c629be2)

Font size 22:
![image](https://github.com/ryanoasis/nerd-fonts/assets/27995479/2b148753-214a-42b3-b805-a5b4aed0d0b5)

**Comment by Finii** [comment]
Ah, I have another hunch...
Which concrete Cascadia Code did you compare with? (Best would be a details screenshot of the font settings thing, when opened Cascadia Code)?

I fear that it might be the hints 🙄

**Comment by phjordan** [comment]
> Which concrete Cascadia Code did you compare with? (Best would be a details screenshot of the font settings thing, when opened Cascadia Code)?

Yes, it seems to be the bundled version of Cascadia Code that I have installed.
![image](https://github.com/ryanoasis/nerd-fonts/assets/27995479/563ef5e7-7a2e-4ee3-b1c9-a8bc134c9953)

**Comment by FrancescoLuzzi** [comment]
> Thanks for the input! There are indeed size-limits where the font switches rendering, I will check that. And maybe I can get VS Code repaired on that one machine, all other machines I have are Win11...
> 
> _Edit: Ah, report was for Win 11_ 🤦‍♀️

Also reproducible on windows 10 👍🏼

**Comment by azdanov** [comment]
I also encountered this issue. `Windows 11, Windows Terminal 1.17`

![image](https://github.com/ryanoasis/nerd-fonts/assets/6123841/84b29c89-dcd9-4f31-9d0a-f1f292d4e358)
Can see that `--` near git are of different sizes

![image](https://github.com/ryanoasis/nerd-fonts/assets/6123841/e3b7c936-9fbf-4ecd-9c1d-7b69396a517f)
And it gets better with font size increase.

**Comment by harshv1741** [comment]
I've Installed the latest version of Caskaydia Cove NF on my windows 10, and now I'm seeing this box icons

![image](https://github.com/ryanoasis/nerd-fonts/assets/51878195/c5b16677-d059-4751-b178-f153e522c629)

![image](https://github.com/ryanoasis/nerd-fonts/assets/51878195/0da41df9-8b8b-425b-a4ac-b3afd81ede21)

**Comment by Finii** [comment]
@harshv1741 This is no ligature Issue.

Please check out
* https://github.com/ryanoasis/nerd-fonts/issues/1190#issuecomment-1530999114

**Comment by Finii** [comment]
I would need someone who can test the potential fix, good would be a thorough test like @phjordan with all the arrows.

**Comment by Finii** [comment]
It would be great if someone who sees the arrows problem can check this font:

[CaskaydiaCove_arrows.zip](https://github.com/ryanoasis/nerd-fonts/files/15049655/CaskaydiaCove_arrows.zip)

(Probably you need to uninstall the old Caskaydia first, then reboot, then install the font given in this comment.)

Without reports it is hard to see if this will fix it or not... Help needed.

**Comment by FrancescoLuzzi** [comment]
Thanks for the update, i'll give it a try as soon as I can!

**Comment by FrancescoLuzzi** [comment]
It seems to be 99.9% resolved!

In some font sizes the "=>" ligature has a **really small** defect (there is a really small gap between the "equal" sign and the "greater than" sign
![image](https://github.com/ryanoasis/nerd-fonts/assets/81475751/5ee93f9a-7bbb-47bb-9991-4d737522ae97)

This is the "correct" arrow on a different size:
![image](https://github.com/ryanoasis/nerd-fonts/assets/81475751/d3934e44-6fb4-41dd-8f36-79facc3e9972)

**Comment by Finii** [comment]
Hmm, this is maybe also a hinting problem, this is most visible at 12 pt / 96 dpi.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/acf190b8-bd6f-4353-999b-b29292002db7)

The advance width is 9.4 pixel, and so the last pixel is only filled less than half, so it is rendered half-grey.
Of course this will vary with the number of characters in front of it.

The situation is comparable with FiraCode unpatched:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/a077c344-89a3-4cb3-9469-85e54d546e29)

Just here other sizes show that same problem.

Are you sure Cascadia Code unpatched does not have the same problem at some sizes? Maybe you can try.
I need to fire up Glyphs3 to examine it. Or was there not a tool on Linux to show the subpixel rendering of variable fonts on Linux :thinking: 

I can check, but I believe this is a principle problem that can not be solved without 'massive' manual intervention.

Affected are a high number of glyphs (the `font-patcher` reports it auto-adjusts 88 glyphs), so that would be quite some work to do, manually edit the hints to extend more to the outside.
Well, and famous FiraCode has the same, so why should we be better ;-)

**Comment by FrancescoLuzzi** [comment]
Tbh you just spoke black magic to me 😂

Jokes aside, I think that this fix is more than eno

**Comment by FrancescoLuzzi** [comment]
> Are you sure Cascadia Code unpatched does not have the same problem at some sizes? Maybe you can try.

Just uninstalled Caskaydia Cove, rebooted and tried using Cascadia Code, the issue is still there
![image](https://github.com/ryanoasis/nerd-fonts/assets/81475751/4b46cece-5c96-46e9-9f11-1f87390461ed)

Well, your patch worked just fine, Cascadia Code is the problem now.
Thanks!

**Comment by Finii** [comment]
Thank you for testing all that stuff!
I will do some final tests with the PR (because it completely changes how the configuration works), and then merge the fix.

**Comment by Finii** [comment]
@allcontributors please add @FrancescoLuzzi for bug

**Comment by nguyenlephuc2108** [comment]
Oh! == is don't work, or my computer have problem?

**Comment by Phoenix-** [comment]
Hi, 
I've got exactly the same problem with -> and => ligatures.
![image](https://github.com/user-attachments/assets/7eba5793-7b1c-4878-9d0b-3d1f7de98860)

Win11 22631.4037
NF 3.2.1
Screenshot is from Windows Fonts Manager, but actual for any text editor. Tried VS Code and Windows Terminal

**Comment by feliperomero3** [comment]
Hi, first, thank you for this nerd font, I've been using for four years now.

I'm experiencing the same ligature 'tearing' issue as @Phoenix- 

(screen capture below)

![image](https://github.com/user-attachments/assets/34b9434e-077a-48be-8d74-d3bcf2c0a774)

In the --> ligature the 'tearing' is barely noticiable

In the ==> ligature, the 'tearing' is much more noticiable

These are the fonts shown in the screen capture (screen capture below)

![image](https://github.com/user-attachments/assets/93545b45-a1f2-4a9a-86b9-44bf1f7137ed)

My versions

`CaskaydiaCove NF: Version 2111.001; VTT 6.35;Nerd Fonts 3.2.1`

**Comment by Finii** [comment]
The problem is the hinting.

- _Cascadia Code_ comes hand-hinted as VF (variable font).
- Nerd Fonts can not (for the foreseeable future) patch VF.
- _Cascadia Code_ also comes as static variants but they are autohinted by `ttfautohint`.
- Thus _Cascadia Code VF_ and _Cascadia Code static_ differs 'a lot' visible in the lettershapes
- People complain that (especially) the small letters of _Caskaydia Cove_ look different from _Cascadia Code_
  - Which they do and dont. They look different from _Cascadia Cove VF_ because _Caskaydia Cove_ is based on _Cascadia Code static_
- For most people the expected look is the one of _Cascadia Code VF_ because it is preinstalled on Win (often)
- Instead of `ttfautohint` we push the _Cascadia Code static_ fonts through `VTT` which is also an autohinter, but with a look more closely to the hand hinted original
- Except that `VTT` does not hint all glyphs the same
- We patch that font; _Caskaydia Cove_ is _Cascadia Code static_ rehinted by `VTT` to have a look similar to _Cascadia Code VF_
- Well, except what you noticed above, the special lig glyphs are not/differently hinted compared to each other, resulting in sub-pixel differences in the line positions, which are then rendered "on pixel off"

The possibilities here are:
1. Use _Cascadia Code static_ with `ttfautohint` (which I assume do not have this problem, but not checked)
2. Hand-hint the problematic ligature glyphs
3. Rewrite `font-patcher` to patch VFs 😁 

Then I obviously did something here with commit b2cf801989 `font-patcher: Allow to rehint some Cascadia glyphs`
Ah, this is
* #1613

That has been merged mid April 2024, just after the `v3.2.1` release:

<img width="1081" alt="Screenshot 2024-09-08 at 13 37 34" src="https://github.com/user-attachments/assets/7f5fc81d-5134-4e2c-8805-054dfbaa48de">

So probably your problems will (mostly) go away after the next release, which is `v3.3.0`, which is scheduled to happen this month (https://github.com/ryanoasis/nerd-fonts/discussions/1705). So please be patient a bit more. The fix is not 100% perfect but at least better (see notes / feedback above).

**Comment by Phoenix-** [comment]
Thanks for the explanation and for your work. Great fonts :)
