### ISSUE TITLE
Can you add https://github.com/uiwjs/file-icons to nerd-fonts

### ISSUE THREAD

**Issue by cathaysia** [ryanoasis/nerd-fonts#1321]
https://github.com/uiwjs/file-icons contains fonticons from vscode-meterial-icon, it's useful for terminal icon, and it's license is MIT. Can you consider add it to nerd-fonts?

**Comment by mafzaldev** [comment]
Hi! Can I contribute to this issue under HacktoberFest?

**Comment by Finii** [comment]
I am a bit underwhelmed by file-icons font file. They originally have color icons (`svg`) and just stuff them into a font file.
But fonts are just black-and-white, which does require some manual postprocessing sometimes:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/150b2e48-f974-4782-8e63-c53a437e7546)

This mouse-head icon is mostly a filled surface (white) which of course will be filled with the font-color which is usually black. The eyes, the ears, all becomes black. If that all-black blob is intended, then they should remove all the inner contours? And if not one needs to adjust the paths such that the white area is **cut out** instead of just filled with font-color.

This is a typical example if a svg collection for mainly web use, and for good measure they just throw it into a font file (because 'we can'), but that borders on un-usable and noone cares.

Sorry for the rant, but I would have to fix all the icons manually myself.

**Comment by Finii** [comment]
@mafzaldev I'm not sure we want this and if we do there are several not-so-obvious things to consider when adding glyph sets. So while it would be easy to 'just add' the set the future maintenance is a problem here. I guess it does not have any codepoint stability guarantees, which means we need to add that afterwards via build scripts or something.
Then there are problems with the icons themselves (see my comment above).
And additionally, at least some of these icons are in Nerd Fonts already; what will we do with the n-th instance of a GO logo?

So thanks for the offer, but this is maybe beyond Hacktoberfest.

**Comment by cathaysia** [comment]
Ok, so I close it. :(
