### ISSUE TITLE
install.sh should use XDG_DATA_HOME to determine target location for user installs

### ISSUE THREAD

**Issue by afoglia** [ryanoasis/nerd-fonts#1324]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
I want to pass a custom install location to the install script (so I can use stow to keep my personal packages organized). I realize this is an uncommon case, but with this simple feature request, I can easily kludge it myself.

**Describe the solution you'd like**
I want the install.sh script to respect `XDG_DATA_HOME` variable for user installations. If not, it should fall back to $HOME/.local/share as per the XDG directory spec.

Basically [line 205 of install.sh](https://github.com/ryanoasis/nerd-fonts/blob/7deaff60d02ad26c38f4f8cc714300c08f598b1e/install.sh#L205) should be

```
usr_font_dir="${XDG_DATA_HOME:-"${HOME}/.local/share"}/fonts"
```

or some equivalent.

(And maybe change the help text for `--install-to-user-path` to "Install fonts to user's font path", removing the unnecessary reference to home.)

This makes more sense according to the standard conventions and configurations of fontconfig.

(This will allow me to override the directory by setting `XDG_DATA_HOME` to `$HOME/.local/stow/nerd-fonts-<ver>/share` before invoking `install.sh`.)

**Describe alternatives you've considered**
Another parameter could be added to the install.sh script to take a directory name. But there's no current options that take parameters, and adding that logic in a bash script can quickly get messy. Supporting XDG_DATA_HOME is simpler, adds support for more complicated environments, and in the spirit of the current `--install-to-user-path` option.

**Additional context**
N/A

**Comment by Finii** [comment]
Thanks for coming up with this. The change is really trivial.

But as you are obviously using `install.sh`...:

I thought it very unlikely that anyone would actually use the script. As you need to (at least shallow) clone the repo, which is a lot of volume. And even if you install every patched font (another thing I can not imagine) instead of just some select ones, you still have all the unpatched fonts sitting there for nothing. Ok, data transfer and data storage does not matter anything anymore today maybe.

BUT, as you might have noticed, we want to drop the patched fonts from the repo itself and depend on release packages instead. The latest added font (Intel One Mono) is one example. The patched fonts are not commited back to the repo, they just live in the release packages. I guess that is the way it will be in the future (that is not entirely clear, but something has to change and choices are limited by multiple constraints).

If `install.sh` shall work in the future, it would have to fetch the release packages and install from there.
This is no problem in principle - there is even already a script that does exactly the fetching - but still would be a behavior change.

Maybe you can share any thoughts on this. Why are you using the script (instead of other means); do you install only some or all fonts; what do you think about the packaging/release; would the change of `install.sh` to fetch the release archives impact you; etc

Thanks for sharing any thoughts :-)

----

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/52328266-037e-4a75-b6c7-0cd7fda261ca)
_Fetch release archives helper script_

**Comment by afoglia** [comment]
Well, for me the best approach would be for someone to make debs and serve them from a deb repo, but that's not at all your responsibility. :-)

As for my plans: Yes, I was going to install all the fonts, because... ah, disk space isn't too much of a limit nowadays, and if I change my mind, by using stow, it's pretty easy for someone like me, who's unfamiliar with details of fontconfig, to just back out the changes.

And as for why all the fonts? Well, I'm only installing them because one of my emacs packages suddenly changed to basically require them. It took me a while to figure that out, and I'm liable to forget should I ever try to change fonts, so why not just install them all and that's one less thing later.

I won't at all claim this was a good idea, just a simple one.

I didn't download the full repo though, just the source tarball from the release page.

Looking at fetch-archive.sh that would have worked. It wasn't mentioned in the install options in the README.  It would benefit from some fixes to make it more user-friendly for end-users, but nothing huge. Not as good as a full install script, but most of the way there.

I definitely can see the benefits of the direction you are headed. Don't change things on my account. Maybe someday these fonts will be so popular they will be packaged nicely by distributions for me. :-)
