### ISSUE TITLE
Script that installs fonts without cloning the entire repository

### ISSUE THREAD

**Issue by mmicu** [ryanoasis/nerd-fonts#1327]
I would like to install a couple of fonts by using the `install.sh` script, but cloning the repository takes a lot of time. In the `README` I can see `Note: Requires cloning the repo as of now`.
My connection is quite good, so I can imagine how slow it can be with slower ones.

We could have a script that we can include in each release that one can download and use to install all the required fonts.
The script could use GitHub APIs to check if a font exists and then it could download and install it accordingly.

**Comment by Finii** [comment]
Ah. This is related to https://github.com/ryanoasis/nerd-fonts/issues/1324#issuecomment-1655101438

What I do not understand, and what noone can explain ;-) Why do people _at all_ want an `install.sh`?
I personally would use the argives from the release page, download them and install them.
Some people prefer installation via package manager, and they could explain it to me: You get automated updates. A valid reason.

But what is the reason to use `install.sh`?

And the current `install.sh` will fail in the future anyhow, when the patched fonts are not part of the repo anymore.

> The script could use GitHub APIs to check if a font exists and then it could download and install it accordingly.

Yes. We already have that, but it is not used for the `install.sh`.

So... I guess the `install.sh` would need to change anyhow, and exactly in the way you propose. I never tackled that, because I saw no reason. Maybe you can give me that, an explanation why we need it :-)

**Comment by Finii** [comment]
> We could have a script that we can include in each release that one can download and use to install all the required fonts.

We have https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/fetch-archives.sh that can fetch the (latest) archive, already:

```
# Fetches the current release files.
# It fetches the latest release, not release candidate.
# Or fetches the specified release's files.
#
# The second parameter specifies the beginning of the artifact
# name that shall be fetched. If unspecified all artifacts will
# be fetched.
#
# Example runs
#   fetch-archives
#   fetch-archives v2.2.2
#   fetch-archives v2.2.2 Heavy
#   fetch-archives latest HeavyDat
#   fetch-archives v3.1.0 'Ara.*zip'   (just fetch the zip archive)
```

That could in principle be used by `install.sh`... but you suggest to have a one-file script that does all?
But how get the `fetch-archives` code? Duplicate? Fetch that file first?

This would take considerable amount of time to develop, would that time be spent wisely? I dont know.

I close this now, maybe you have comments, but my question from July already went unanswered.
