### ISSUE TITLE
KDE Konsole

### ISSUE THREAD

**Issue by JamesFraserLogan** [ryanoasis/nerd-fonts#1328]
#### 🗹 Requirements

- [ ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ ] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ ] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

No glyphs.
Expected behavior:

Glyphs.
Example symbols:

Boxes.
#### 🔧 Your Setup
Hack
- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - 
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - 
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   -

**Comment by Finii** [comment]
Can not help here as almost no information provided.
I guess after installing the font you need to select it in Konsole.

From here: https://www.addictivetips.com/ubuntu-linux-tips/customize-the-kde-terminal/ (*)
I guess there is a dialog to do so:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/a237e2c1-42d6-40ed-992c-af5721089c49)

Closing this due to lack of mandatory-fields-filled.

(*) _This is just the first hit on the web search engine, maybe there are better pages out there_
