### ISSUE TITLE
Add CommitMono font

### ISSUE THREAD

**Issue by tranzystorekk** [ryanoasis/nerd-fonts#1334]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Description**

Font webpage: https://commitmono.com/

Font git repository: https://github.com/eigilnikolajsen/commit-mono

Font license: SIL Open Font 1.1

**Comment by jorgegarciadev** [comment]
Hi, I patched the font using font-patcher 3.0.2 but I got this weird vertical lines in Linux (Konsole and Xfce Terminal) but not in macOS (Iterm2).

![Screenshot_2023-08-10_23-36-58](https://github.com/ryanoasis/nerd-fonts/assets/2560863/6c97d2a4-3593-4d2f-bbb0-75be1ed4c749)
[CommitMonoNerdFont.zip](https://github.com/ryanoasis/nerd-fonts/files/12317380/CommitMonoNerdFont.zip)

Any Idea How to fix it?

**Comment by Finii** [comment]
The lines:
* Change your system's antialiasing to `monochrome` (recommemded) 
* Or, if you feel comfortable editing `font-patcher`, increase the `overlap` to 0.06 or so

https://github.com/ryanoasis/nerd-fonts/pull/780#issuecomment-1380707534





________________________________

**Comment by jorgegarciadev** [comment]
Thanks, Finii. I couldn't find how to set antialiasing to monochrome in KDE. Searching for antialiasing issues in KDE and Konsoles found that changing sub-pixel rendering to RGB to VRGB removes the lines.

**Comment by riiyaa24** [comment]
Hello, I would like to work on this issue. Can you assign me this PR?

**Comment by tranzystorek-io** [comment]
@riiyaa24 there doesn't seem to be any PR for this yet, you can start coding and most probably no one will swipe it away from you 😄

**Comment by Finii** [comment]
We do not do assignments here, usually.

Otoh, your Issue report is good and it will be very easy for me to add the font from the details given in it. Most of the process is automated. As I wrote in some other add-new-font issue, the new release is a bit overdue. I wanted to fix some bugs first and then (*) update and add fonts and trigger the release. The time consuming part is the bugs, and my time is a bit scarce lately :-(

(*) If we first update and add fonts they might be outdated when the actual release happens after fixing the bugs. So that is the reason for that ordering.

**Comment by uncenter** [comment]
Any update on this? Interested in helping move this along.

**Comment by Finii** [comment]
Thank you @uncenter, but adding a font is not hard :-)

We need to figure out which of the 100th of suggested new fonts we really want to add; and commit to maintain them for the next 10+ years. So that is not so easy, judging if there is an audience for a specific font.

Which is the case with this font I guess (interest from more than one person I mean).

I will try to come up with a list of all fonts that were suggested (i.e. expand https://github.com/ryanoasis/nerd-fonts/discussions/1095#discussioncomment-4821624) and then ... I really hate that I always have to discuss just with myself or persons that want that one font, instead of people that have no specific interests in one font ;-) If you know what I mean.

**Comment by uncenter** [comment]
Yeah I have my own patched font but I thought I'd see what I could do here. I see what you mean about the types of fonts / size of audiences of fonts you want to add - I misunderstood your previous comment and I didn't think that was an issue, was just trying to see what the blocker was. Thank you for the clarification!

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
