### ISSUE TITLE
Can not handle font flags (TypeError('ord() expected a character, but string of length 0 found'))

### ISSUE THREAD

**Issue by j-tai** [ryanoasis/nerd-fonts#1342]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
I'm getting this error from the patcher:
```
ERROR: Can not handle font flags (TypeError('ord() expected a character, but string of length 0 found'))
```
And then the patcher produces a 0 byte file as the output.

Expected behavior:
I expected the patcher to output a valid font.

Example symbols:
N/A

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - setofont.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - self-patched, original font from https://osdn.net/projects/setofont/releases/
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - gnome-terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Pop!_OS 22.04

#### ★ Screenshots (Optional)

![image](https://github.com/ryanoasis/nerd-fonts/assets/45131430/0235c972-b472-4a8a-b507-e4d19aa14538)

**Comment by Finii** [comment]
I downloaded this file:

```
-rw-rw-r-- 1 fini fini 13053768 Sep 24  2014 /home/fini/Downloads/X/setofont.ttf
```

When patching I got this output:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/4c7924a9-e231-4c38-810a-b4aa241965a8)

Well, the original font has 57619 glyphs already

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ec8375e5-ed7c-4a2f-8891-06923d601d7f)

if you patch with `--complete` some 9000 are added and that are too much. See the error message:

**`The 'sfnt' format is currently limited to 65535 glyphs, and your font has 66765 of them.`**

`fontforge` does not create the font then, but the `font-patcher` script can not detect Fontforge errors (it's not foreseen in the API).

It detects only too late that it can not tweak the font flags, because the font file is empty:

**`ERROR: Can not handle font flags (TypeError('ord() expected a character, but string of length 0 found'))`**

In principle we can enhance the error message here, but we can do nothing to make this work - there are just too many glyphs. You can try patching with not the complete set but leave some unused glyphs (icon sets) out.

**Comment by j-tai** [comment]
Ah thank you. I didn't realize that message was an error -- I thought it was just a warning or something.

Perhaps the script could detect an empty output file and print something like "See FontForge errors above"?

I'll look into patching the font by deleting some glyphs from the original font. Thanks!

**Comment by Finii** [comment]
> Perhaps the script could detect an empty output file and print something like "See FontForge errors above"?

Yes, I will come up with something. The error messages around the tweaking are not the best anyhow (was too lazy when introducing that feature :grimacing: )

**Comment by Finii** [comment]
New message that is hopefully better:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/173a099e-7604-40f5-97ee-bd465bde3333)
