### ISSUE TITLE
"Fork us on GitHub" Label on Homepage Covering One of Navbar Option (in Small Screen)

### ISSUE THREAD

**Issue by iamRabia-N** [ryanoasis/nerd-fonts#1366]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
"Fork us on GitHub" label is covering one of homepage navbar option in small screen.

Expected behavior:
Label correctly aligned on the right side.

#### ★ Screenshots (Optional)

**Current Design**

![img (6)](https://github.com/ryanoasis/nerd-fonts/assets/115794049/37d3205e-2cb2-4b43-a99b-f0aeb6eee439)

**Expected Updated Design**

![img (7)](https://github.com/ryanoasis/nerd-fonts/assets/115794049/e68da26d-8ad6-45f8-aa20-b93202489f30)

Kindly assign me this issue.

**Comment by akhileshallewar880** [comment]
Hi, I'm interested in working on this issue. Could you please assign it to me....

**Comment by AnshikaGupta6112** [comment]
Hi, I'd like to take on this task. Can you please assign it to me?

**Comment by Finii** [comment]
Thank you for reporting the issue!

I believe instead of shrinking the label it would be better to make it click-through? It is quite unreadable with the very small font.

There also seems to be something broken with the tabs rescaling. If the window gets smaller and smaller, first the tabs overflow in a second line, and then the short words are used instead (and then the font size is decreased):

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ee471b48-a5aa-4100-8604-18f106e13118)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/437b9567-65cf-4d9f-a488-31f659f1497e)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/7218282e-14cb-44e0-89a1-5e15fac81d47)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/43e5c35d-b243-4c07-91ec-1481bf986433)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ae883899-bf6f-4b66-9372-528312ad54aa)

**Comment by Finii** [comment]
Ugg, I have no experience here, now three people want to be assigned? What shall I do :-}

But then, this is at least two different problems... :thinking:

**Comment by Finii** [comment]
Hmm, the tab code is here: https://github.com/ryanoasis/nerd-fonts/blob/gh-pages/_includes/topnav.html
That seems to be a general Jekyll problem?

**Comment by APURVA-MOGAL** [comment]
hey @Finii can you please assign this task to me? I can do this for you!
or Is this issue already done?

**Comment by Finii** [comment]
@APURVA-MOGAL 

See my answer above

> I have no experience [with Hacktoberfest], now three people want to be assigned? What shall I do :-}

Which sub-topic do you want to do? Maybe we can split this in two (if that is reasonable)
* Fork-me covers Tab
* Tab line becomes two lines with some widths

**Comment by APURVA-MOGAL** [comment]
@Finii 
I can solve both the issues but in my opinion tab line become two in some width will not look good because website needs to be useful as well as attractive. So we can minimize single line tab and adjust "fork us on github" properly on the right side.

**Comment by Viswaraje** [comment]
Hello @Finii ,I would like to work on this issue if available.

**Comment by Finii** [comment]
This will be closed by #1373 ; unfortunately I was not able to set the assigment here.

But I will transfer the second half of this discussion to a new issue.

**Comment by Finii** [comment]
New Issue is
* #1375

Thanks for your interest and help!

**Comment by Finii** [comment]
Solved via #1373
