### ISSUE TITLE
Issue with Subtitle Circle and Layout on Smaller Screens

### ISSUE THREAD

**Issue by VitthalGund** [ryanoasis/nerd-fonts#1384]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue
As discussed in [Pull Request #1368](https://github.com/ryanoasis/nerd-fonts/pull/1368#issuecomment-1751669936), I've addressed an issue where the circle shrinks horizontally but not vertically. There's also an additional problem with the layout of the entire website.

**Experienced behavior**:
For screens with a width less than 767px, the subtitle inner circle inside the features section shrinks horizontally but not vertically. This results in an unusual appearance and overflow from its parent element.

Furthermore, while debugging this, I discovered a significant issue that breaks the layout of the entire website. Specifically, within the Font Patcher script section, the `<details>` tag overflows from its parent. This results in a horizontal scrollbar, which disrupts the website's layout.

**Expected behavior**:
I would expect the subtitle inner circle inside the features section to shrink both horizontally and vertically as the screen size decreases to ensure proper alignment.

Regarding the `<details>` tag, when a detail section is open, the `<summary>` section should overflow from its parent element without causing layout issues.

Assign this issue to me 🙋🏻‍♂️
#### 🔧 Your Setup
- Operating System: Windows 11
- Browser: Chrome

#### Before:
![Before Image 1](https://github.com/ryanoasis/nerd-fonts/assets/97181033/377356ce-3f55-415d-b610-4e3aa420c22b)
![Before Image 2](https://github.com/ryanoasis/nerd-fonts/assets/97181033/b43e0a32-ee46-4043-8380-8714e6536b0d)

#### After:
![After Image 1](https://github.com/ryanoasis/nerd-fonts/assets/97181033/6a78d7e2-1356-4096-a57e-75efc632e4d3)
![After Image 2](https://github.com/ryanoasis/nerd-fonts/assets/97181033/81829635-75ac-44dd-8f05-b2e63654bb78)

#### Before:
![Before Image 3](https://github.com/ryanoasis/nerd-fonts/assets/97181033/2d9922bc-062d-41e0-b08d-0bbfc505e1c1)
![Before Image 4](https://github.com/ryanoasis/nerd-fonts/assets/97181033/bb848c22-a0dc-4966-b777-6d3670b44d59)

#### After:
![After Image 3](https://github.com/ryanoasis/nerd-fonts/assets/97181033/40b16723-1e55-419a-8fc6-c443579ce8b2)
![After Image 4](https://github.com/ryanoasis/nerd-fonts/assets/97181033/56395e3f-fbd4-439f-93a2-cae6bca0d760)

**Comment by Finii** [comment]
Very welcome!

**Comment by Finii** [comment]
Fixed via #1387

**Comment by Finii** [comment]
The fix via #1387 breaks all other subtitle circles, for example here:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/a9852bde-71ef-4d4b-87b3-329054cdf37a)
_wide version_

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/2ce7ef56-164c-46b5-b505-990c1ba6e001)
_small version_

Fixed it the noob way via c88da98 instead.

**Comment by VitthalGund** [comment]
> The fix via #1387 breaks all other subtitle circles, for example here:
> 
> ![image](https://user-images.githubusercontent.com/16012374/277379190-a9852bde-71ef-4d4b-87b3-329054cdf37a.png) _wide version_
> 
> ![image](https://user-images.githubusercontent.com/16012374/277379383-2ce7ef56-164c-46b5-b505-990c1ba6e001.png) 
_small version_
> 
> Fixed it the noob way via [c88da98](https://github.com/ryanoasis/nerd-fonts/commit/c88da986f0f1b37076b969b5e9a920337dc5db0c) instead.

Hi @Finii ,

Thank you for your thorough review of the changes made in PR #1387. I appreciate your feedback and the visual examples you've provided to illustrate the issue.

It's evident that the fix in the PR caused unintended problems with other subtitle circles, as demonstrated in the images you shared. I'm sorry for any inconvenience this may have caused.

I will take a closer look at the commit [c88da98](https://github.com/ryanoasis/nerd-fonts/commit/c88da986f0f1b37076b969b5e9a920337dc5db0c) to understand the adjustments you've made. If you believe that this is a more suitable approach, I'd be interested in exploring it further.

It's important to ensure that the fix addresses the issue without introducing new problems. Please let me know if there are any specific details or considerations I should be aware of while reviewing your solution.

Best regards,
@VitthalGund

**Comment by Finii** [comment]
Dear VitthalGund!

Thank you for your engagement :-)

What I (re)did was hard setting the size of the circle in pixels. I guess that fits to the approach to set some sizes depending on screen width - this is all not scaling in a ordinary sense, but just jumps in 2 or 3 distinct sizes that are pixel-wise hard coded. I know this has drawbacks for very high resolution displays (for example I work with a 4k display), but at least I usually just turn the in-browser magnification up on pages that seem unreadable (120% usually). That works ok-ish.

This method (not directly scaling with the width but just having some few discrete width-switch-points is how the whole website is designed. For example navbar on top etc.

If one hard codes both width and hight as pixels it is guaranteed to be circular. I have only rudimentary HTML knowledge, but the usual 'size to fit' can - as far as I know - not connect two size values. But we would need that to keep the aspect ratio 1:1 (i.e. circle circular). And I guess that works very well for all circular dividers except the all-icons-circle - because that contains so many things. All other circles contain just 1 thing (one icon-text block, or one image). With the multiple lines in the all-icons-circle this becomes a problem if font size, line size, character width, etc change...

I'm not really sure why it is only a problem with the all-icons-circle. The all-fonts-circle next to it is also multiline and it never had any problems.

<img width="920" alt="Screenshot 2023-10-24 at 07 46 11" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/14a8e647-b81f-48e6-8b4c-7d01f8445b53">

_Some circles this time shown with Safari_

Here the left one is an image, but the other two are also multi lines of text and they work flawlessly.
They even seem like hiding text that is too wide, like a hole punched into the page and the text is behind it - the circle size independent of content:

<img width="235" alt="Screenshot 2023-10-24 at 07 48 58" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/1386d4b5-7d87-46bc-982d-54bd7770349a">

_Just text marked with the mouse cursor_

That effect would be desirable, I guess, for the all-icons-circle also. Why is it (the all icons circle) different 🤔 

I don't know.

Another thing that I noticed is that at some smaller width SOME of the circles loose/drop their outer ring, while other keep it??! But maybe this is specifically implemented as design choice. It does not bother me, just noticed.

<img width="729" alt="Screenshot 2023-10-24 at 07 53 34" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/44729bd2-9c13-41c2-a0a0-bc6f1e997e98">

_"Features" circle without but "all icons" with backdrop_

I'm not sure if anything needs to be done with this. I checked the website with Linux/Firefox, Linux/Chromium, Windows/Firefox, MacOs/Safari, Android/Firefox and it renders ok-ish on all. Often the circles are not really round or centered (which could be improved), but not drastically wrong either.
