### ISSUE TITLE
Italic version of Comic Shanns Mono Nerd Font

### ISSUE THREAD

**Issue by toh995** [ryanoasis/nerd-fonts#1393]
**Requirements**
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
My neovim doesn't render italics for Comic Shanns Mono Nerd Font.

**Describe the solution you'd like**
An Italic version of Comic Shanns Mono Nerd Font

**Describe alternatives you've considered**
Create it myself possibly...?

**Additional context**
According to the [README](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/ComicShannsMono/README.md) for Comic Shanns Mono Nerd Font, a bold version of the font was added.

Is it possible to add an italic version?

I could possibly help out if I get some direction on how to implement this.

**Comment by Finii** [comment]
The automated changes are always problematic.

You could try and play around with this script
https://github.com/ryanoasis/nerd-fonts/blob/master/src/unpatched-fonts/ComicShannsMono/make_bold

and instead of `changeWeight()` use `italizise()` on the whole font (and not on all individual glyphs as I did with changeWeight).

https://fontforge.org/docs/scripting/python/fontforge.html#fontforge.font.italicize

In the loop after the wight change I try to get rid of self-intersections with all the simplify calls.
Maybe that is not needed or needed in a different configuration after the italicisation.

Also some glyphs like vertical bar should probably not italic.

**Comment by Finii** [comment]
Well, although this is technically possible the problems with self-intersecting glyphs are a very big hurdle.
That would take quite a considerable amount of time that is just not available.
Sorry, I will close this now, as it will not be tackled any time in the future (meaning this or next year).
