### ISSUE TITLE
Repatch All Fonts in Patched Fonts

### ISSUE THREAD

**Issue by jo-project** [ryanoasis/nerd-fonts#1397]
**Requirements**

- [ ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [ ] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ ] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please re-patch all fonts in patched fonts

**Comment by Finii** [comment]
If there is no problem, why should they be re-patched? :thinking:

**Comment by jo-project** [comment]
Wait, I thought there's new neovim icon. https://www.reddit.com/r/neovim/comments/17ejggf/neovim_icon_has_been_merged_into_nerd_fonts/

**Comment by Finii** [comment]
Ah I see :-)

Well, better would be if we could update font logos in the release too.
And then we need to add some new fonts (but which)?
And the worst thing are all the bugs revolving around Cascadia Code (sigh).

The next release is due to 12th July 2023:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/41c5ab39-c78d-4e94-ba0e-0a9645998095)

Marginally behind schedule I'd say. :woman_shrugging: Which is sad. Where is all the time?

**Comment by jo-project** [comment]
So I supposed next month?

**Comment by Finii** [comment]
NOW ;)
