### ISSUE TITLE
Font download file not found (Release v3.1.0 missing)

### ISSUE THREAD

**Issue by ginruh** [ryanoasis/nerd-fonts#1411]
#### 🗹 Requirements
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

##### Experienced behavior:
Unable to download some fonts because zip file not found. I have attached some screenshots. In case of file not found, there is no font name and font's abcd... example line. Original font name is also missing. Only Info is shown.

##### Expected behavior:
Fonts should be available for download.

#### ★ Screenshots (Optional)

![image](https://github.com/ryanoasis/nerd-fonts/assets/26306108/ef6e33ad-a4e3-48ee-a530-a65a5eb8e415)
![image](https://github.com/ryanoasis/nerd-fonts/assets/26306108/c5c9de62-5ffa-4868-a892-6343b7abb327)

**Comment by Finii** [comment]
Oh, sorry. These fonts are new with release 3.1.0, and I started the work on that but did not finish yet.
Unfortunately the documentation is ahead of reality here now. 

The release will come these days, today, tomorrow, something like that.

Sent from Nine
________________________________
From: Akshay ***@***.***>
Sent: Monday, November 13, 2023 05:49
To: ryanoasis/nerd-fonts
Cc: Subscribed
Subject: [ryanoasis/nerd-fonts] Font download file not found (Issue #1411)

🗹 Requirements
I have searched the issues for my issue and found nothing related and/or helpful
I have searched the FAQ for help
I have searched the Wiki for help
🎯 Subject of the issue
Experienced behavior:
Unable to download some fonts because zip file not found. I have attached some screenshots. In case of file not found, there is no font name and font's abcd... example line. Original font name is also missing. Only Info is shown.
Expected behavior:
Fonts should be available for download.
🔧 Your Setup
★ Screenshots (Optional)

**Comment by Finii** [comment]
Probably best is to look here:

* https://github.com/ryanoasis/nerd-fonts/milestone/27
* #1404

**Comment by Finii** [comment]
Release in now underway, this will take some hours even if there are no problems ;-)

https://github.com/ryanoasis/nerd-fonts/actions/runs/6940642493

**Comment by Finii** [comment]
Release is out, files should be there.
