### ISSUE TITLE
Consider manage patched and unpatched fonts using git LFS to reduce repo size? 

### ISSUE THREAD

**Issue by LNKLEO** [ryanoasis/nerd-fonts#1441]
the reason this repo too large is because of font files, especially patched fonts, consider using git-lfs to track them and rewrite history will resolve this problem. the only side effect is need to force push whole rewrited history and the upload lfs objects will take a huge time but only the first time, and everyone may be need to reclone the repo. but the repo size will decrease to a vary small size.

**Comment by Finii** [comment]
Thanks for the suggestion.

Yes, something like this and other solutions were already suggested, but unfortunately I can not force push to the repo.

So my aim would be to drop in-repo-releases completely, and then the growth rate will become much less.

In principle the plan was to divide this repo into multiple ones, (patcher itself [1], source font collection, each patched font in own repo (so that we can update-release one font while others do not need to be touched) and maybe a release repo that collect all the info.

But, that needs certain rights... work on that has halted.

[1] https://github.com/NerdFonts
