### ISSUE TITLE
Polybar: Some icons are offset from their center, others are too small

### ISSUE THREAD

**Issue by DarkReaper231** [ryanoasis/nerd-fonts#1443]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Using the glyphs in polybar is not a straight forward experience, some glyphs are smaller than others, some are offset
When inspecting them with Font Manager, it is apparent that they are indeed offset
One solution would be using Mono fonts but that makes all icons super tiny

Using Mono font makes the glyphs super tiny

Expected behavior:
Icons should be centered and all icons should be same size

Example symbols:

These icons are offcenter: "", "", "", "", "", "", "", ""

Refresh icon - "" is smaller than poweroff icon - ""
Some other examples of icons that are too small include:
terminal: ""
firefox: "󰈹" (this is not the one I use in polybar, I use "")
spotify: ""

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Inconsolata Nerd Font
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://archlinux.org/packages/extra/any/ttf-inconsolata-nerd/
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Arch Linux

#### ★ Screenshots (Optional)

Polybar:
![image](https://github.com/ryanoasis/nerd-fonts/assets/38611351/456d70bb-13ca-4005-99c5-b41db158e4f7)
![image](https://github.com/ryanoasis/nerd-fonts/assets/38611351/0c50da7a-2ec4-433b-ab54-840092ef2a49)

Font Manager:
![image](https://github.com/ryanoasis/nerd-fonts/assets/38611351/261a19d1-96be-409e-876b-3c1f2d3fa767)

Mono icons:
![image](https://github.com/ryanoasis/nerd-fonts/assets/38611351/6be6b370-ad54-426a-a8de-e56fc63103a4)

**Comment by DarkReaper231** [comment]
I should also point out, this wasn't an issue before v3

**Comment by Finii** [comment]
For Polybar I would expect that you use `Inconsolata Nerd Font Propo`. Is that the case? Unfortunately you do not specify the concrete font filename.

**Comment by Finii** [comment]
Compare
* #951
* #1103 
* #731

**Comment by DarkReaper231** [comment]
> For Polybar I would expect that you use `Inconsolata Nerd Font Propo`. Is that the case? Unfortunately you do not specify the concrete font filename.

I don't have any font called Propo installed. Can I get it on AUR?

**Comment by DarkReaper231** [comment]
Actually I do

**Comment by DarkReaper231** [comment]
YES PROPO FONT WORKS, OMG THANK YOU SO MUCH

**Comment by Finii** [comment]
I'll have a quick look, unfortunately I have no Nerd Font installed :-D

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/95db9258-d1b4-4353-a7e2-a60c9661056d)

**Comment by Finii** [comment]
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ead5ca77-0e52-447c-84e5-cc9e08fda8eb)

The size of the icons originate from the original set. So comparable icons are often only found within the same set.

For example the 'refresh' you used is for weather indicators, where it fits nicely sizewise.
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/8fb235d6-dfe3-42b0-b8f6-b8b311a4ea00)

Probably you should use the same set to get matching sizes, that means `F011` and `F01E`?
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/d15cbd11-1d52-4dd6-864b-7345fd710cbf)

The `dev` set (you use `dev-terminal`) does have some imbalances, but in general is well balanced within itself:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/fd9646ed-a35b-4972-961c-88ae1c0b407a)

Why spotify is smaller than firefox, I have no clue - both are in the `font awesome` set:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/bef474e4-1eb4-46a4-bdc9-bca2518c490d)

---

I remember we had the discussion to scale all icons to some same size, for example 1.6 cell width. I do not remember the details but the outcome was (obviously) to not-do it. I did put the code in, I remember that; and that it was more complex than anticipated. (Will edit this and add a link if I can find the thread.)
Usually if you change some icons size because it is 'wrong' for one there will be two other that complain the new size is unbearable. :grimacing: 

So what we do is `Nerd Font Mono` scales the icons down (never up, iirc) to fit into one cell, and the other `Nerd Font` and `Nerd Font Propo` do not touch the original icon sizes.
