### ISSUE TITLE
Certain symbols have more space around them in WebStorm console/terminal.

### ISSUE THREAD

**Issue by sebygreen** [ryanoasis/nerd-fonts#1459]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
In WebStorm's console/terminal, certain symbols (see below) have more space to the left and right, leading to an unwanted new line.

Expected behavior:
As in all other of my tools, the symbols should be of consistent width.

Example symbols:
\udb80\udd2c
\udb80\udd59

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _JetBrainsMonoNerdFont-*.ttf_
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://www.nerdfonts.com/font-downloads
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - I don't know what emulator WebStorm uses.
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - macOS Sonoma 14.2
- _Other_
   - oh-my-zsh:latest
   - p10k:latest
       - custom config
   - zsh-syntax-highlighting:latest
   - .zshrc
       - ZLE_RPROMPT_INDENT=0

#### ★ Screenshots

**WebStorm** (check and close symbols have more space around them.)
<img width="762" alt="Screenshot 2023-12-16 at 16 42 21" src="https://github.com/ryanoasis/nerd-fonts/assets/45818412/de4ce372-98ae-4df3-ac87-5425b4f70a0a">

**iTerm2** (correct)
<img width="760" alt="Screenshot 2023-12-16 at 16 28 49" src="https://github.com/ryanoasis/nerd-fonts/assets/45818412/8e9eeb5e-4283-42ce-92ad-d9bb924faeee">

**macOS Terminal** (correct)
<img width="718" alt="Screenshot 2023-12-16 at 16 28 50" src="https://github.com/ryanoasis/nerd-fonts/assets/45818412/479920ff-dd60-4c67-9fd5-e7af1d20e7e0">

**VSCode** (correct)
<img width="537" alt="Screenshot 2023-12-16 at 16 53 03" src="https://github.com/ryanoasis/nerd-fonts/assets/45818412/5d648ae8-baa2-4cb3-92cc-c4c3019f3fb9">

**WebStorm Settings**
<img width="1094" alt="Screenshot 2023-12-16 at 16 44 22" src="https://github.com/ryanoasis/nerd-fonts/assets/45818412/10686d30-b95b-4fa7-950e-a49ed4255798">

**Comment by Finii** [comment]
If it works 'everywhere' except with WebStorm, is it not most likely a problem of WebStorm and not of Nerd Fonts?

Can you copy and paste the two glyphs as text here in a comment? I could check if they have "ambiguous width".

**Comment by Finii** [comment]
`\udb80\udd2c` -> `F012C` -> `nf-md-check`

Lets see what Unicode has to say [1]...

`<group age="2.0" na="" JSN="" ccc="0" dt="none" dm="#" nt="None" nv="NaN" bpt="n" bpb="#" Bidi_M="N" bmg="" suc="#" slc="#" stc="#" uc="#" lc="#" tc="#" scf="#" cf="#" jt="U" jg="No_Joining_Group" lb="XX" sc="Zzzz" scx="Zzzz" Dash="N" WSpace="N" Hyphen="N" QMark="N" Radical="N" Ideo="N" UIdeo="N" IDSB="N" IDST="N" hst="NA" DI="N" ODI="N" Alpha="N" OAlpha="N" Upper="N" OUpper="N" Lower="N" OLower="N" Math="N" OMath="N" Hex="N" AHex="N" VS="N" Bidi_C="N" Join_C="N" Gr_Base="N" Gr_Ext="N" OGr_Ext="N" Gr_Link="N" STerm="N" Ext="N" Term="N" Dia="N" Dep="N" IDS="N" OIDS="N" XIDS="N" IDC="N" OIDC="N" XIDC="N" SD="N" LOE="N" Pat_WS="N" Pat_Syn="N" GCB="XX" WB="XX" SB="XX" CE="N" Comp_Ex="N" NFC_QC="Y" NFD_QC="Y" NFKC_QC="Y" NFKD_QC="Y" XO_NFC="N" XO_NFD="N" XO_NFKC="N" XO_NFKD="N" FC_NFKC="#" CI="N" Cased="N" CWCF="N" CWCM="N" CWKCF="N" CWL="N" CWT="N" CWU="N" NFKC_CF="#" InSC="Other" InPC="NA" PCM="N" RI="N" blk="Sup_PUA_A" isc="" na1="" Emoji="N" EPres="N" EMod="N" EBase="N" EComp="N" ExtPict="N" NFKC_SCF="#" ID_Compat_Math_Start="N" ID_Compat_Math_Continue="N" IDSU="N" InCB="None">`
`<char first-cp="F0000" last-cp="FFFFD" gc="Co" bc="L" ea="A" NChar="N" vo="U"/>`

So, the `ea` is `A` for all codepoints `F0000` to `FFFFD`.

`A` means ambiguous width; can be one or two cells wide, the standard does not know.
In principle each terminal may display it as one or two cells wide. Obviously most terminals choose one cell.
If this does not suit you, you have to complain at the terminal programmers. Some terminals have options to adjust this; maybe Webstorm does also? Usually the option has something with 'ambiguous' in the name.

`iTerm2` for example renders all ambiguous glyphs as one width, except if you request otherwise:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/c9ff81c0-57a8-4a23-b767-62fee56b8fcf)


[1] https://www.unicode.org/Public/UCD/latest/ucdxml/ucd.all.grouped.zip

**Comment by sebygreen** [comment]
hello,
thank you for your insight. i replaced the check symbol with a standard unicode tick in my p10k configuration, and the issue goes away, corroborating your explanation.
i guess i will see if i post a bug report on youtrack, but those don't seem to ever get far quickly.
regardless, i appreciate the time taken.
