### ISSUE TITLE
0xProto Nerd Font (cyrillic)

### ISSUE THREAD

**Issue by kobzar** [ryanoasis/nerd-fonts#1498]
0x9Proto is wonderful font.
But i ahave some issues with cyrillic simbols

![image](https://github.com/ryanoasis/nerd-fonts/assets/1912842/b21a5758-924b-401f-bcee-fd8435ac68a4)

The same words like on image for test
"Чисто тестовое сообщение ююю!"

**Comment by Finii** [comment]
I guess the issue is that for example the yu overlaps at the end of the sentence? `ююю!`

The problem is that 0xProto does not have any Cyrillic glyphs, so what you see there is not from 0xProto but comes in via fontfallback from another font where the widths is different?
Or is there a Cyrillic version? The version we have in `unpatched_fonts` looks like this (yu has codepoint `44E`)

<img width="1010" alt="Screenshot 2024-01-28 at 15 19 37" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/c17b4205-600a-478b-8857-fe3d013ce897">

**Comment by Finii** [comment]
The cyrillic letters are not from (our) 0xProto, so there is nothing we can do here. Sorry.
Maybe you should use another cyrillic font as fallback.
