### ISSUE TITLE
Recursive.zip was not found 

### ISSUE THREAD

**Issue by asang24** [ryanoasis/nerd-fonts#1582]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Hi Team,
 I found that `Recursive` has been added to the nerd-fonts project 3 days ago, but now it can't be found `https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Recursive.zip`
it's in `unpatched-fonts` fold.

Expected behavior:

We download `Recursive Mono` in [nerdfonts.com](https://www.nerdfonts.com/font-downloads)

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - 
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - 
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   -

**Comment by Finii** [comment]
Yes sorry, it _will be added_ with Nerd Font Release 3.2.0.

The problem is that I would need to update the code, then release, then update the doc.
What I do is: Update code and doc, then release.

Please be patient, the release will be ready withing the next ... I would say hours, but it could also take a day or two.
Having a broken documentation between starting-to-release until release-finished is just due to my lazyness :roll_eyes: 
Additionally there were some problems uncovered with _Zed Mono_ that needed investigation before release.

**Comment by asang24** [comment]
tks for your hard working on this awesome project.
