### ISSUE TITLE
Add Bearded icons

### ISSUE THREAD

**Issue by FelixKLG** [ryanoasis/nerd-fonts#1594]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
I think it would be great if the Bearded icon pack was available in Nerd Fonts. 
https://github.com/BeardedBear/bearded-icons

**Describe the solution you'd like**
I'd like to be able to import and use Bearded icons so I can make use of them in my terminal, Bearded Icons is natively a VSCode extension and it has the best icons I've found around. I'd really like to be able to use them in my terminal, this is also because the maintainer (@BeardedBear) is really on top of the ball and updates and creates icons really quickly such as an icon for the JavaScript icon Bun which isn't currently available in NerdFront. 

**Describe alternatives you've considered**
Using another icon pack, my main reason for wanting this however is the speed at which BeardedBear creates icons and makes them available. Such as Bun and others.
(this could potentially resolve the issue currently open for adding Bun as an icon #1565)

**Additional context**
Bearded Icons are under the GPL-3.0 license which could pose licensing issues.

**Comment by BeardedBear** [comment]
hi ! 

> Bearded Icons are under the GPL-3.0 license which could pose licensing issues.

I'm open to discussion on this point if necessary ;)

And thanks for thinking of my pack ;)

**Comment by Finii** [comment]
Thanks for suggesting this interesting set.

But I guess it is not suited to be included into a font because it is mainly a colored set; some icons even are multicolored. That means the icons would need to be hand selected and tweaked to fit into a font - making it a new set.

Minor is the lack of the idea to have revisions; they have no tags, no releasese, just some rolling repository. It is very hard to incorporate such a moving target into some other project (i.e. Nerd Fonts).

I believe the set works best when used with the VS extension.

If there are some icons in that set that are urgently needed we could include them on a one-time-import glyph-by-glyph basis; as other suggested icon additions.
