### ISSUE TITLE
Semi-Systematic Logo-Addition Evaluation

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#1616]
There are several logo requests but it is extremely hard to decide which ones should be included and which should be rejected.

This Issue shall serve as a platform to evaluate them one by one.

What do we have in #1095?

| description | #glyphs | ref | interest | impact | comment | solved already |
|---|---|---|---|---|---|---|
| alt. PL separators | ~10 | #360 | 1 |  | original project dead |
| Raku | 1 | #851 | 1 | 160 | "Perl 6" |
| Deno | 1 | #869 | 2 | 25k | Node successor? | devicons
| Anaconda | 1 | #952 | 1 | 45k | Python package thing | devicons
| Flutter | 1 | #999 | 1 | 200k |  UI tk | devicons
| Vitruvian Man | 1 | #1001 | 2 | - | just from old L. da Vinci | #1740
| pnpm | 1 | #1114 | 3 | 6k | yet another npm | devicons
| neorg | 1 | #1135 | 4 | 220 | Neovim organizer |
| USD | 1 | #1196 | 1 | 12k | Universal Scene Description |
| Glimmer | 2 | #1237 | 1 | 1.9k | Ember something? |
| Progress | 12 | #1345 | 3 | - | from FiraCode | #1733
| Retro Computer | 9? | #1447 | 1 | - ||
| Luau | 1 | #1474 | 1 | 100 | Lua derivative |
| round half blocks | 2 | #1484 | 1 | - ||
| Chuck | 1 | #1489 | 1 | 13k | Music programming | #1740
| Solidity | 2 | #1493 | 2 | 2.7k | Ethereum language | devicons
| Bun | 1 | #1565 | 3 | 16k | js runtime | devicons
| ddev | 1 | #1590 | 1 | 41k | docker PHP env |
| gleam | 1 | #1591 | 1 | 6k | new language |

Current custom block space `E700` - `E6B6` = 74 icons

_Edit: Change round half blocks #glyphs from 4 to 2_
_Edit: Mark icon additons solved by devicon update_

**Comment by Finii** [comment]
I would like to specifically invite @hasecilu for some discussion, but I would be pleased by anyone leaving constructive comments here.

I'm always very reluctant to add anything to the custom set. Usually Nerd Fonts aggregates icon sets and is not an icon set of its own right. The custom set is for giving icons a chance that have no chance upstream but are deemed to be nerd-ish enough. Whatever that means. Popularity of course helps, but then, if it's popular there is no need to use the fallback solution of NF-custom-icons ;-) See the contradiction?

And then, in principle we could add all of these, but that might prompt more and more requests and the codepoints will be depleted quickly (in like 3 years or so?) If people see it is not likely to be added they might refrain from raising a glyph request :grimacing: 

From the above, I personally would probably add
* Vitruvian Man (because it is just an abstract and no project at all)
* The 12 progress indicators
* Chuck, because I like music :laughing: 

For some, like Bun, I have no clue how people want to use it? In the title of a window? Not in a Powerline I assume.

This is no source of joy for me :grimacing:

**Comment by hasecilu** [comment]
Hi, sorry for not answering before, just got time to go through this.

I agree with the fact that Nerd Fonts should be feeded with full sets rather than focusing on bringing individual glyphs. A lot of upstream projects have a specific topic/thematic that already fits with a lot of the requests here on NF but also some other projects that use icons (specially for decorating filetypes like [web-devicons](https://github.com/nvim-tree/nvim-web-devicons) and many more).

In #615 is mentioned the option to update current devicon font with the new one from still mantained `devicons/devicon` project

> Set of icons representing programming languages, designing & development tools 

their last release about 3 months ago https://github.com/devicons/devicon/releases/tag/v2.16.0 (322 New/Updated Icons). They have a very active issue tracker and also there are a lot of contributions there.

Doing a quick search on https://devicon.dev/ tell us that some of the requested icons are there:
- deno
- anaconda
- flutter
- pnpm
- neorg
- solidity
- bun

They claim to have 473 icons, quite a lot (we only have 198) but: the last used devicon icon is `U+E7C5` and the next one is `EA60`, meaning that there are 667 empty codepoints for the new 275 icons, **is there plans for `E8` and `E9` codepoints?** By how are located the projects I think it better to take advantage of the fact that devicon font have _a lot of space to grow_ and try to move all DEV icons there and leave icons that are not very related on custom font.

From my perspective it seems that a lot of request are directly tied to people using terminal apps (most of time developers/sysadmins trying to make their environment pretty) so, a lot of DEV related icons could be expected to be requested. We can only make more accurate claims reading the feedback from users and cli app developers so we may need to wait for it.

Also, maybe creating a pull request template to encourage users trying to contribute icons here to look for an upstream project could help a little.

Extra: it seems the "name" of the glyph is not set correctly (as in lib files), can confirm?

![image](https://github.com/ryanoasis/nerd-fonts/assets/53124818/33b79276-3487-4cf5-8a21-61d423f0aff9)

**Comment by rockorager** [comment]
I believe the `round half blocks` would add two glyphs, not four: a left round halfblock and a right round half block.

**Comment by Finii** [comment]
Ah thanks @rockorager, I corrected the table.
I guess I did not understand what was wanted and assumed quarter blocks ;-)

**Comment by Finii** [comment]
Regarding the devicons, lets see how the codepoint situation is right now:

```console
$ jq -r 'keys[] as $k | "0x\(.[$k] | .code) \($k)"' glyphnames.json | sort -g | sed 's/^..//'

...
e7bb dev-redhat
e7bc dev-scriptcs
e7c4 dev-sqllite
e7c5 dev-vim
ea60 cod-add
ea61 cod-lightbulb
ea62 cod-repo
ea63 cod-repo_forked
...
```

Setting up some codepoint preservation stuff like with Font Awesome...
A quickest check shows that only about ~90 of the old ~200 are in the current devicon release, at least at superficial look.
Anyhow, working...

**Comment by Finii** [comment]
> Extra: it seems the "name" of the glyph is not set correctly (as in lib files), can confirm?

Yes, the `font-patcher` preserves the glyphname of the source, and that is often not very helpful.
I thought several times already to name the glyphs 'correctly', but that would add another dependency to the patcher script. But ob the other hand, that was a concern some years back, when the patcher script was standalone, which it is not really anyhow anymore. So maybe it is a nice improvement. Thanks!

(The lib `i_` files are a mess, but in the meantime we have the `glyphnames.json` 'database' and that could integrate better. I also considered dropping the `i_` files or inversing the information flow.)

**Comment by Finii** [comment]
> Extra: it seems the "name" of the glyph is not set correctly (as in lib files), can confirm?

Fixed this in https://github.com/ryanoasis/nerd-fonts/pull/1691/commits/71e7ae0b4500165e41d415fc1929299d06b6871e (which is part of PR 1691).

Thanks for mentioning!

**Comment by remi-guan** [comment]
I'm developing projects with **Bun**, and I'd like to have a Nerd Font icon for it in my shell prompt. The one on https://devicon.dev/ looks great. 

Currently, since Nerd Font doesn't have it, starship uses this emoji `via 🥟 v1.1.17 ❯`:

![image](https://github.com/user-attachments/assets/0028b4b2-ce63-4545-be03-1dd34f512018)

Which doesn't seem to be fit with my custom airline theme, so I don't have a good icon for Bun project.

 Thanks in advance if you can add it into Nerd Font!

**Comment by Finii** [comment]
@remi-guan 

The filled bun in in #1691 which will most likely come in the next ... days :grimacing: 

![image](https://github.com/user-attachments/assets/46673bf2-24fe-4d0f-8f62-f7cd002c6a71)

At the moment I'm tackling a problem with the CommitMono font, which has a bug upstream of upstream, trying to fix it there (i.e. `opentype.js`) :grimacing:

**Comment by Finii** [comment]
> From the above, I personally would probably add
>
>   * Vitruvian Man (because it is just an abstract and no project at all)
>   * The 12 progress indicators
>   * Chuck, because I like music 😆

So lets tackle the last two after done the progress things.
