### ISSUE TITLE
Should CaskaydiaCove (nerd version of Cascadia) be replaced with the official nerd version?

### ISSUE THREAD

**Issue by yuantao313** [ryanoasis/nerd-fonts#1622]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
Microsoft has released a new version of Cascadia font recently. In this release, they gave an official version of nerd fonts.

**Describe the solution you'd like**
I think the old version should be replaced with the official version.
We can also just add the official version and add a tag to inform.

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by hasecilu** [comment]
Source? What license have their font, can be redistributed? It could be that some glyphs have different sizes or are displaced from center.

**Comment by Finii** [comment]
I just discussed something similar at the `Delugia` repo, as that was the first Nerd Font version of `Cascadia Code`. The `Caskaydia Cove` came only later.

See
* #https://github.com/adam7/delugia-code/issues/83#issuecomment-2090009778

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/cdbdb4af-8c90-4535-8274-62e61cf3e3e9)

So you see there is no `CascadiaCove NF` variant for each of the `CaskaydiaCove` variants.

And then:

> It could be that some glyphs have different sizes or are displaced from center.

That is indeed the case, the glyphs have a bit more margin than Nerd Font has. I _personally_ like that more, but I know that there are people out there who would hate that change. Nonetheless, for example #1564 is a direct product of the Nerd Fonts team (i.e. me) working together with Saja Typeworks (i.e. Aaron) on `CascadiaCodeNF` (not that I could add much apart from comments and reviews).

So let me list the differences, as I know them in an ad hoc manner
* `CascadiaCodeNF` is what we call `Nerd Fonts Mono`, there is no other variant
* Albeit the font is `Nerd Font Mono`-like the icons do not fill the cell completely but have a small 'border'
* `CascadiaCoveNF` implements `Nerd Fonts v3.1.1` and I do not know of any update schedule
* PowerlineExtra scaling ideas differ (because `CascadiaCodePL` used some `Nerd Fonts v2.x` or something)

So I guess we can/should not drop `CaskaydiaCove`, but we should maybe add a link and documentation that there is `CascadiaCodeNF` (which I personally like very much).
