### ISSUE TITLE
Large glyphs in MesloLGS NF  for catppuccin/tmux

### ISSUE THREAD

**Issue by ctretyak** [ryanoasis/nerd-fonts#1625]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ ] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

I've just installed https://github.com/catppuccin/tmux and found that some glyphs looks bad (MesloLGS NF in alacritty term)

Experienced behavior:
set -g @catppuccin_window_left_separator " "
set -g @catppuccin_window_right_separator ""
these symbols looks oversized

![image](https://github.com/ryanoasis/nerd-fonts/assets/4935982/2966379f-6d14-4f42-b524-e810cfbb4483)

Expected behavior:
in JetBrainsMono NF they looks good

![image](https://github.com/ryanoasis/nerd-fonts/assets/4935982/6c246390-3a60-45be-8f5a-737ca60ea57c)

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - 
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - 
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   -

**Comment by Finii** [comment]
Sorry to hear of (and see) your problem.

Trying to reproduce, can not see it with Tilix

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/8899a324-9c3a-4b0f-80d8-d2de1beda047)

Rummaging around to find `alacritty`...

Can not see there either. Which font size do you use?

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/454d2610-7b4c-449b-9a61-c71b35bfe01a)

```console
$ cat alacritty.yml
font:
  normal:
    family: 'MesloLGS Nerd Font'
    style: Regular
  size: 14.0
```

Can you show your configuration file?
Which OS are you on?

**Comment by ctretyak** [comment]
I've tried windows in powershell, windows in wsl in alacritty, Pop!_Os in alacritty

![image](https://github.com/ryanoasis/nerd-fonts/assets/4935982/a287a969-64e1-4099-be0d-e4511c19f3ff)

**Comment by Finii** [comment]
I think this can not be fixed because the reason lies in the font rendering engine and that a (colored) blank and a real glyph can not be guaranteed to be of the same height. The blank is just the font size (pixel height) that the terminal emulator uses for that specific line (it will wary from line to line because in general one line is not an integer number of pixels high). The glyph on the other hand is also scaled and subpixel rendered. Here the hints are used to pull some subpixels up or down, but we can not do that for the powerline glyphs.

See more for example at
* #1629

Sorry, but that is just a limitation. Maybe use a small change in font size like 14.1 or 13.9 px.

**Comment by ctretyak** [comment]
Switched to JetBrainsMono NF. Now it's ok

**Comment by Finii** [comment]
> Switched to JetBrainsMono NF. Now it's ok

Thanks for the feedback @ctretyak
