### ISSUE TITLE
ShureTech Mono font overlapping with other characters when rendered in bold in terminal

### ISSUE THREAD

**Issue by tukykarmakar** [ryanoasis/nerd-fonts#1638]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

When using the `ShureTechMonoNerdFont-Regular` font in Konsole, the "intense colours" are being rendered in bold and overlapping with the characters that seem to be a tab-space away from them.
The issue goes away when the setting "Draw intense colours in bold fonts" option is unchecked. 

Expected behavior:

Characters should be spaced correctly and not overlapping. The expected behaviour is demonstrated in the 3rd screenshot below with `AnonymicePro Nerd Font`.

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - ShureTechMonoNerdFont-Regular.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://www.nerdfonts.com/font-downloads
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Konsole
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Linux

#### ℹ️ Some points to note
I've been told that `ShureTech Mono Nerd Font` _doesn't have any bold variant_ and thus, it _shouldn't be rendering in bold_. However, as you can see in the screenshots below, it really is ShureTech Mono being rendered in bold. In fact, it is rendered in bold in a _rich text editor like OnlyOffice_ too (see [ShureTech Mono Nerd Font Bold.docx](https://github.com/ryanoasis/nerd-fonts/files/15362735/ShureTech.Mono.Nerd.Font.Bold.docx)). The same boldness can also be observed in Windows 10, where the Regular variant is rendered in bold (see last 3 screenshots).

Also, this isn't the only font with that can render in bold despite not having a bold variant. I specifically installed `AnonymicePro Nerd Font Regular` only, so that I can show how it can also be rendered in bold in the terminal (4th screenshot below).

#### ★ Screenshots (Optional)

![Konsole-Bold-Spacing-03](https://github.com/ryanoasis/nerd-fonts/assets/42614682/daa2a856-58b3-4265-8d56-5bef5a3f7aea)
![Konsole-Bold-Spacing-04](https://github.com/ryanoasis/nerd-fonts/assets/42614682/f45e9d43-9f68-41ca-abe5-d3d51a108848)
![Konsole-Bold-Spacing-02](https://github.com/ryanoasis/nerd-fonts/assets/42614682/4b9f1f03-d2d8-4d53-b199-0b95f0c5bab8)
![Konsole-Bold-Spacing-05](https://github.com/ryanoasis/nerd-fonts/assets/42614682/40d11a8f-c758-453e-a9c9-be9653bfe1c3)
![Windows_Screenshot](https://github.com/ryanoasis/nerd-fonts/assets/42614682/fc279cb8-d3fa-4f56-be71-9e0e239691a9)
![Windows-Terminal-01](https://github.com/ryanoasis/nerd-fonts/assets/42614682/6416f2fb-3512-4239-8ce3-bcb44d20a5ee)
![Windows-Terminal-02](https://github.com/ryanoasis/nerd-fonts/assets/42614682/4afc2438-7a4d-49f3-94a4-ceb31984ee94)

**Comment by Finii** [comment]
Well, artificially expanding a single font to a complete RIBBI set is a "feature" that also existed in Windows 3 and probably before that. So for example; MS Word had these BOLD and ITALIC buttons, and they always worked, even if the selected font was an ornamental one, where it did not really make sense. If no Bold or Italic could be found on the system the font was "invented from this air" by transmogrifying the Regular variant.
Back than everyone knew, do not select Bold (or Italic) in Word if you do not have that font, because it kind of renders but looks very ugly.
So this is a "convenience" function that imho should not be there at all.

But well, people seems to like it, or application programmers think people like it, or whatever, but that questionable feature is still available as of today - as you found out.

An autogenerated Bold or Italic can not be good - or font designers would never need to bother designing these.

Also the Italics version was of course an Oblique instead, but people might think they are the same?

Whatever, that is part of what you noticed: There are programs out there that take a Regular font and allow the user to select Bold or Italic even if there is no such font installed and autocreate it on the fly.

Well, as there is no Bold font, how should it be fix it here? If you have issues with the font that some system autogenerates, surely you should raise an issue over there (wherever that is)?

---

Here, in Tilix:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/5bbd6835-cb2c-4981-a172-7cc55edda3ce)

Here, in Writer:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/c477b7a4-6aba-4d35-9a45-e0d941a1f044)

And here a particularly bad example: Gyre Chorus itself is already a slanted / oblique font, and they just slap their artifical "Italic" on top of it, making it more slanted :laughing: :sob: 

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ec2bc671-6888-4d3e-a878-7ac926affe13)

Regular is Italic with this font

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ac42cd0b-9d71-4482-b9a3-818a767c90d0)

**Comment by tukykarmakar** [comment]
I just don't understand why it was working fine previously, I didn't change any settings other than selecting ShureTech for monospace fonts from the KDE Settings app. This issue only happens when there's a tab after the bold characters, and I wasn't able to reproduce it in any other editor or text output.

Also, why does it not happen with wider fonts like Source Code Pro and Anonymice Pro?

**Comment by Finii** [comment]
Hmm, probably Konsole got an update and that introduced a new bug?

Can you roll back a version? You don't specify which Linux you use (so I can't check), but maybe you should check when Terminal had been updated last and if that coincides with the behavioural change.

It seems Konsole has some problems with the Bold stuff, like for example
https://bugs.kde.org/show_bug.cgi?id=432898 (which is open since 2021?!)
or https://bugs.kde.org/show_bug.cgi?id=470059

You could also try if the problem persists with the Nerd Font Mono (or Nerd Font Propo) variant.

If this happens only with Konsole it's unlikely to be a Nerd Fonts problem ;-)

**Comment by tukykarmakar** [comment]
I'm using [Nobara](https://nobaraproject.org/), a distro based on Fedora, if you want to try reproduce it yourself.
I can't find anything on how to rollback Konsole versions. I'll go ask in the KDE discussion forum about rolling back and about the font issue in Konsole.

Thanks for looking into this.

**Comment by tukykarmakar** [comment]
I tried out other terminals and it doesn't seem to happen in those. But I also tried out the Konsole Flatpak and it's happening there again. Closing it as it seems to be a KDE issue.

**Comment by Finii** [comment]
Thank you; hope this will be ironed out somewhen
