### ISSUE TITLE
Bluetooth Battery Outline Icon

### ISSUE THREAD

**Issue by ZaheenJ** [ryanoasis/nerd-fonts#1645]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
There is no way to represent 0 (or close to 0) battery on Bluetooth devices with icons. I can use nf-md-battery_outline for regular empty battery representation, but there is no such nf-md-battery_bluetooth_outline.

**Describe the solution you'd like**
I would want a nf-md-battery_bluetooth_outline icon, a battery outline with a Bluetooth symbol next to it. No idea how easy it is, but would think it's reasonably easy.

**Describe alternatives you've considered**
I could just use the regular battery icon and the Bluetooth battery icon next to it, but this is clunky and inconsistent since for all other battery levels for Bluetooth devices I have a corresponding singular icon representation.

**Additional context**
Empty battery icon
![image](https://github.com/ryanoasis/nerd-fonts/assets/31298082/855c36d2-f697-4e1e-bbe5-ff9f81632c00)
No corresponding empty battery icon for bluetooth
![image](https://github.com/ryanoasis/nerd-fonts/assets/31298082/4af9fde5-b24f-4710-a002-b1f9af62616a)

**Comment by Finii** [comment]
Well, although your problem is understandable, that would need to be fixed upstream (i.e. with Material Design Icons [1]) because we just pull their icons in.

I guess if the bluetooth attached device has 0% battery it can not communicate anymore (i.e. is off), maybe that is the reason they did not include an empty bat symbol, even in the most up to date version? [2]

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/dfce1e74-06d0-400c-873b-5f3b04c6fd37)


Sorry, but there is not really a way to add icons under `nf-md-`

[1] https://github.com/Templarian/MaterialDesign
[2] https://pictogrammers.com/library/mdi/
