### ISSUE TITLE
Add icon for Cloudflare

### ISSUE THREAD

**Issue by brainwo** [ryanoasis/nerd-fonts#1646]
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

FA does have the icon https://fontawesome.com/icons/cloudflare, I wonder why isn't this in Nerd Fonts. Would love to see this being added, thanks :)

**Comment by Finii** [comment]
* Not all icons are included [1]
* Cloudflare is in the remix file, but in the commented-out section [2]
* Fontawesome codepoint of the glyph is `E07D` (see https://fontawesome.com/icons/cloudflare)
* That icon is in "Region C" and therefore not added [3] because we just have no space left (codepoint wise)

For the reasons see this commit f089ee8a6ed1778c983182472f175d6e110cca67 and PR #1563 

### Ref 1
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/6a3d5539-7233-43e6-91a5-da86b3899245)

### Ref 2
https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/font-awesome/remix_mapping

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/d86cdd7b-77d5-45e1-bcd5-0e91afffcd27)

### Ref 3
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/07f1a3c5-7765-4c39-a05c-3230f1ed4aab)

**Comment by Finii** [comment]
That is all not easy ;-)

Firstly Nerd Fonts is an icon pack aggregator, that means we take other collections and throw them into the target font.
Of course it would be ideal to keep the original codepoint, as that is advertised on the upstream website etc.
That worked for the first some years.
Then we had an overlapping set, where one of the sets has been moved (as a block) a bit up in number.
Meanwhile the number of icons grew exponentially. That means all the sets grew so big they do not really fit anymore in the (very small) range that is allowed for custom icons.
Furthermore people understandably hate when codepoints change.

That as background.

For the update of the FontAwesome icons we already take a complicated route. We keep codepoints of old versions stable; but they (FA) dropped some old icons completely. These vacant codepoints are reused for new FontAwesome icons that they put somewhere else, so there is already some codepoint movement.
That is what these mapping files and so on is all about.
To keep the Icons still in one manageable window of numbers (instead of strewing them around like THEY did with the updates). But then, we have other sets that also need space, so we had to make some (arbitrary) choice how big the window should be, and stuff that window full of icons (with moving the codepoints), but when that window is full there is no place for the remaining new icons to go. They would need to take codepoints from other sets. And/or become extremely fragmented, which is not maintainable.

How the sets are distributed is documented here:
https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points#overview

There is just no space to have all icons that possibly exist. So we had to make a choice what to drop from the FontAwesome update, and affected where a lot brand icons.

I understand that you really need this icon, but for us, that is a special rule that is disrupting all automatisms and has to be kept forever, even if you stop using cloudflare in half a year ;-)

So, sorry, I guess it is not good to open this door. Maybe there is some other cloud-y icon that you could use instead?

**Comment by brainwo** [comment]
Nah, it's okay. I have found an alternative I can use. It's not a big deal. I was just curious since you pointed all this.

Thanks for the clarification though, this is very informative.
I have been using Nerd Fonts for years and I did notice the breaking change that was introduced some years ago, it was painful. Your information is so valuable to understand what can/cannot we request. Perhaps this could be a part of FAQ since I didn't read anything regarding to this prior to submitting my issue. Thanks again.

**Comment by Finii** [comment]
> I did notice the breaking change that was introduced some years ago, it was painful

Yes. The reason was that - because there were so few 'free' codepoints - we used codepoints that are reserved for Chinese, Arab and other "exotic" languages. _Who needs those glyphs, what can go wrong when we patch them over with useful icons._ ... There were hardly any fonts with that glyphs anyhow - back then.

But of course that raised complains from people who were missing the glyphs and really soon it became clear that we needed to change it. But still the preparation for the actual breaking change took literally years.
