### ISSUE TITLE
GohuFont question mark is upside-down

### ISSUE THREAD

**Issue by dsvoid** [ryanoasis/nerd-fonts#1652]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior: GohuFont 14 Nerd Font Propo Regular has an upside-down question mark. This may be the case for the variants.

Expected behavior: Right-side up question mark.

Example symbols: "?"

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - GohuFont14NerdFontPropo-Regular.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Gohu.zip
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Alacritty. Also replicated in dmenu and other tools.
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Asahi Fedora Remix 40. Appears to be in the ttf itself, however, when opened with fontforge.

#### ★ Screenshots (Optional)

![Untitled](https://github.com/ryanoasis/nerd-fonts/assets/7375973/84363f7b-af88-4223-a714-c13ebefbafe0)

**Comment by Finii** [comment]
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/31ba7867-7cda-46d6-9d9f-934d2b91d6c9)

**Comment by Finii** [comment]
@allcontributors please add @dsvoid for bug

**Comment by kierun** [comment]
[⸮ is the irony mark, isn't it?](https://en.wikipedia.org/wiki/Irony_punctuation)

**Comment by Finii** [comment]
Yes, it is the spanish start-a-question-symbol ... like _**¿Hablas español?**_

In the 11 px variant all is well:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/6175045a-cadc-43e6-a2a2-22489360d48f)

but in the 14 px variant the upside-down one replaces the ordinary question mark, while the upside-down slot remains empty.
The reason is that both glyphs have the same name (`question`) in the definition file, but the mapping of outlines to codepoints is by name, so it is coincidence which goes where (on build time). That is a bug in the font definition file, where the upside down question mark's outline should have a different name, for example `sMoFu` or the standard `inverted`, so that on building there is no ambiguity.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/8b1e5ede-a267-476e-abbd-f61583dbdb39)

Also noticed now that the micro symbol is missing :unamused: Did not try to find the reason for that.
