### ISSUE TITLE
Nerd font alignment issues in vte3 terminal when using it as a fallback font

### ISSUE THREAD

**Issue by 64-bitman** [ryanoasis/nerd-fonts#1676]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have checked the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

### Experienced Behavior

Nerd font symbols that are bigger than the cell clip each other when using [ddterm v54](https://github.com/ddterm/gnome-shell-extension-ddterm), which is vte3 based. For symbols that are smaller than the cell, they are aligned to the left. I also noticed that when the cursor is over the nerd symbol, it covers the entire symbol, but after moving it defaults to the normal width, overlapping the symbol.

### Expected Behavior

Large width symbols should not overlap each other, and the cursor should move the entire character width over. Small symbols should be centered? (not sure if this is normal)

### Example Symbols or Text

I used symbols like these ` ` to test, but symbols like these ` ` are not aligned in the middle but on the left side.

### Font Used

SymbolsNerdFontMono-Regular.ttf and CommitMono-400-Regular.otf

### Source of Font File

https://archlinux.org/packages/extra/any/ttf-nerd-fonts-symbols-mono/ and https://aur.archlinux.org/packages/otf-commit-mono

### Terminal Emulator (and the title of the terminal window)

gnome-shell-extension-ddterm

### Operating System and Version

Arch Linux 6.9.8-arch1-1 (GNOME 46.3.1 DE)

### Screenshots

[Screencast from 2024-07-11 01-42-09.webm](https://github.com/ryanoasis/nerd-fonts/assets/60551350/fc97a77b-bfb1-4c2d-b665-918e7af698bf)

/etc/fonts/local.conf:
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
    <alias>
        <family>monospace</family>
        <prefer>
            <family>CommitMono</family>
            <family>Symbols Nerd Font Mono</family>
        </prefer>
    </alias>
    <alias>
        <family>sans-serif</family>
        <prefer>
            <family>Inter</family>
            <family>Symbols Nerd Font</family>
        </prefer>
    </alias>
    <alias>
        <family>serif</family>
        <prefer>
            <family>Liberation Serif</family>
            <family>Symbols Nerd Font</family>
        </prefer>
    </alias>

    <match target="font">
        <edit mode="assign" name="antialias">
            <bool>true</bool>
        </edit>
        <edit mode="assign" name="embeddedbitmap">
            <bool>true</bool>
        </edit>
        <edit mode="assign" name="hinting">
            <bool>true</bool>
        </edit>
        <edit mode="assign" name="hintstyle">
            <const>hintslight</const>
        </edit>
        <edit mode="assign" name="lcdfilter">
            <const>lcddefault</const>
        </edit>
        <edit mode="assign" name="rgba">
            <const>rgb</const>
        </edit>
        <edit mode="assign" name="autohint">
            <bool>false</bool>
        </edit>
    </match>

    <match target="font">
        <test name="family" compare="eq" ignore-blanks="true">
            <string>Inter</string>
        </test>
        <edit name="fontfeatures" mode="append">
            <string>calt on</string>
            <string>dlig on</string>
            <string>case on</string>
            <string>ccmp on</string>
            <string>ss02 on</string>
            <string>ss03 on</string>
        </edit>
    </match>


    <match target="font">
        <test name="family" compare="eq" ignore-blanks="true">
            <string>CommitMono</string>
        </test>
        <edit name="fontfeatures" mode="append">
            <!-- disable ligatures -->
            <string>calt off</string>  
        </edit>
    </match>
</fontconfig>
```

**Comment by Finii** [comment]
> Large width symbols should not overlap each other, and the cursor should move the entire character width over.

a) This is not defined by the font; in the font the individual glyphs all have their advance width (how much the cursor should advance) the same as the individual bounding box / visual width. (This is true only the Symbols Only font you refer to; the Mono font has all advance width the same.)
b) If you have symbols wider than one 'cell' and they should not overlap that means that the next 'cell' is not on the 'grid' anymore. Most terminals, albeit allowing individual glyphs to extract out of the 'cell' keep the monospace 'grid', which in turn results in the behaviour you observe.

> Small symbols should be centered?

In the font the glyphs are always 'centered' within the (advance) width they report, which individually different for each glyph. How the terminal handles that in respect to some abstract 'grid' of characters it wants to guarantee is their decision. Most, if not all, terminal left align 'too small' glyphs.
The extra-complication here is that you get the glyphs only as fallback; how terminals handle fallback glyphs is jet another design decision on their side - and that is the reason why we still have the individually patched fonts, because only then you can place the glyphs in the relative position you want and do not depend on terminal emulator designer decisions.

Maybe compare how that is handled by a proportional font application like LibreOffice Writer.

So in summary:
* Nerd Font has (almost) no influence on placement (size and position wise) when used as fallback fonts
* Even with patched fonts
  * Symbols are expected to be left aligned
  * Depending on which Nerd Font flavour used you get the same exact extrusion and cursor advance effects, some write up of the reasons can be found in #1103

Maybe you should try the prepatched CommitMono font [1] with the `Nerd Font Propo` flavour. Technically it is exactly what you expect - and check how your terminal handles it. Usually terminals do not handle stuff the way you expect and that is not due to the font. Always compare to how proportional-aware applications (e.g. Writer) show the font.

So I believe this is no bug in the font and your expectation just does not match the expectation of the terminal emulator programmer's idea how it should work. Closing this, but we can discuss further and possibly reopen if it turns out the be really a bug.

[1] https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CommitMono
