### ISSUE TITLE
Add icon for Matlab

### ISSUE THREAD

**Issue by vcurdia** [ryanoasis/nerd-fonts#1693]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

At the moment there is no icon for Matlab. This would be extremely helpful for example when using Nerd Fonts in emacs to place icons associated with file types (using the nerd-icons package).

### Desired Solution

The solution I believe would be to add a Matlab logo looking icon to Devicons to make it available to users. 

### Alternatives Considered

The Emacs All The Icons Package (https://github.com/domtronn/all-the-icons.el) has an icon for Matlab. For most icons the formatting of Nerd Fonts/Nerd Icons Emacs package seem like a better choice for me so it would be great if I could get the Matlab icon via Nerd Fonts.

**Comment by Finii** [comment]
> The solution I believe would be to add a Matlab logo looking icon to Devicons to make it available to users.

Well, [Devicons](https://github.com/devicons/devicon) is another project. Did you try there already?

> For most icons the formatting of Nerd Fonts/Nerd Icons Emacs package seem like a better choice for me

Ah that is interesting. Can you explain why? I have no clue about the other package and how they do it (all-the-icons).
Maybe with an image.
This is just curiosity.

**Comment by vcurdia** [comment]
@Finii Thanks for the clarification.

I didn't realize until now that there is a separate project for Devicons. I was referring to the "nf-dev-..."  icons, which I thought was devicons, as a subset of Nerd Fonts. Do I get it right that those icons are instead a subset of Devicons that have been patched and available through Nerd Fonts?

In the Nerd Icons Emacs Package (https://github.com/rainstormstudio/nerd-icons.el) they refer to the "nf-dev-..." icons, so I guess they are referring to the patched icons in the Nerd Fonts project. 

From what I just looked at the Matlab icon exists in the actual Devicons project, but not in the NF patched subset. Unfortunately I have no idea on how to use the Devicons font with the Emacs Nerd Icons package. I'll ask in there.

Now regarding the All The Icons vs Nerd Icons it's just how some scaling and defaults comes up and liking some icons used by default in one vs the other. If I attempt to go deep enough into the settings I can probably get similar results using either but that is more time than what I can afford.

**Comment by Finii** [comment]
Nerd Fonts just aggregates icons from different projects and patches then into files - positioning them in a way we believe can be useful. There is a very small number of icons that Nerd Fonts itself collects; but the usual way is to have an icon added to some of the upstream sets. Nerd Fonts pulls the set from upstream and updates from time to time (rather infrequent I must confess).

See here https://github.com/ryanoasis/nerd-fonts?tab=readme-ov-file#features

![image](https://github.com/user-attachments/assets/451db5c4-f091-408b-8461-9f0828db795b)

> From what I just looked at the Matlab icon exists in the actual Devicons project

This is great, because the Devicons are just about to be updated in Nerd Fonts: #1691
And yes, in the test-patching in that PR you see matlab :tada: 

![image](https://github.com/user-attachments/assets/e931163f-39ca-4dff-9f16-135c94726aff)

This situartion is of course very uncommon, but you are lucky :grimacing: 
The icon will come with Nerd Fonts v3.3.0 which I expect to happen mid/end September.
I was not aware of which icon are included in the set, that's why I did not tell you outright.

> Now regarding the All The Icons vs Nerd Icons it's just how some scaling and defaults comes up and liking some icons used by default in one vs the other.

As described earlier, Nerd Fonts positions the glyphs in a way that 'we' think can be useful. Unfortunately that is just one opinion and getting feedback from Nerd Font users is very hard. That is the reason for the question. Obviously we must do something 'right' for you, and it would be interesting to see what that is that is out=of=the=box better for you ;)

_Changing tags accordingly_

**Comment by Finii** [comment]
> use the Devicons font with the Emacs Nerd Icons package

Although that might be possible this approach has a stability problem. Devicons (as most other upstream icon sets) target web-usage and as such have drawbacks when used as a terminal font. Font files can be tailored to different use-cases.

If you use command line emacs the feasibility depends on your terminal emulator and to some extend to the OS you use.
If there is a GUI emacs and you use that, then of course emacs is the right place to ask.

**Comment by vcurdia** [comment]
Thank you for all this information! Very helpful.

**Comment by Finii** [comment]
Closing this as it will come with the FontLogos update with v3.3.0, and I just try to work through all Issues right now...
