### ISSUE TITLE
Icons overlap other text, Propo doesn't work

### ISSUE THREAD

**Issue by keliss** [ryanoasis/nerd-fonts#1703]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have checked the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

### Experienced Behavior

Hello. Maybe someone raised this in the past, but I couldn't find a definitive answer.
The only font with icons I'm using is JetBrainsMono installed through the Arch package repository. This font is set to be used by my terminal (foot):
![image](https://github.com/user-attachments/assets/9f1fa99a-00a2-48e3-92e9-0a415eef8418)

And for some reason, I cannot get rid of icons overlapping with other symbols in my terminal:
![image](https://github.com/user-attachments/assets/bad9356e-610e-4397-b18c-ab932baed12b)

Note that I tried the "plain" variant of that font as well (without the word Propo) and the result doesn't change. If I set the font to Mono, the icons become too small:
![image](https://github.com/user-attachments/assets/09f480ca-9e6a-46a4-be8c-1c681c37eaae)

### Expected Behavior

Icons are big enough when using Propo/normal font variant, and they don't overlap any other symbols.

Thank you.

### Example Symbols or Text

\uf269 - firefox icon is a good example.

### Font Used

JetBrainsMono Nerd Font Propo/JetBrainsMono Nerd Font/JetBrainsMono Nerd Font Mono

### Source of Font File

https://archlinux.org/packages/extra/any/ttf-jetbrains-mono-nerd/

### Terminal Emulator (and the title of the terminal window)

foot

### Operating System and Version

Arch Linux (btw)

**Comment by keliss** [comment]
By the way, setting the Symbols font as the first one to be used (downloaded from https://archlinux.org/packages/extra/any/ttf-nerd-fonts-symbols/) as advised here https://github.com/polybar/polybar/issues/991 doesn't help either, still getting the icon overlap.

**Comment by Finii** [comment]
Sorry to hear of your problem!

Hmm, the glyph itself is not defective; the cursor advance width is indicated by the two vertial black helper lines:

<img width="624" alt="Screenshot 2024-09-02 at 06 29 59" src="https://github.com/user-attachments/assets/2220d176-7698-4232-b2ff-754a4ae7f4d6">

_Nerd Font Propo_

<img width="624" alt="Screenshot 2024-09-02 at 06 32 58" src="https://github.com/user-attachments/assets/983d08e0-474d-4c7a-942e-24086f730f50">

_Nerd Font ("normal")_

I do not know `foot`. Maybe you can try the proportional font in a non-terminal application like Libreoffice Writer.
Terminals usually can not **by design** have glyphs wider than one 'cell' because that would break the row-and-columns grid that people expect from terminals.
So what you want is in principle not possible and does not have anything to do with the font.
That is the reason why we have `Mono`. If the icons are too small the only possibility for environments where the cursor advance width is fixed (like in terminals) is to add a blank after the icon if it is bigger than one cell.
But that is a limitation of the terminal or this is what is expected of terminals.

Maybe some more light can be shed on the issue with https://github.com/ryanoasis/nerd-fonts/discussions/1103

Maybe you can report back your findings of the Writer test.

Another thing to try is using `JetBrainsMono NFP` as family name instead of the long form `JetBrainsMono Nerd Font Propo`. I doubt that that is the problem; I expect you just hit on a terminal emulator limitation.

**Comment by keliss** [comment]
Thank you for the detailed response @Finii, apparently, this is indeed a terminal issue, because nothing helps. I think we close this.

**Comment by powerman** [comment]
@keliss I've updated https://github.com/powerman/wcwidth-icons for foot terminal (added utf8proc_charwidth hook). For me foot now works with non-Mono Nerd Fonts: icons are 2-cell wide.

The only issue I still have with foot - if icon itself is not square and does not use full width then foot render it left-aligned in cell (unlike urxvt, which render it center-aligned and this way icons looks much better). But I suppose this can be fixed only in font itself. 😞
