### ISSUE TITLE
Ligature support in ComicShannsMono 

### ISSUE THREAD

**Issue by Sensex00** [ryanoasis/nerd-fonts#1711]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

Now the font has almost everything except for ligature 

### Desired Solution

Please add ligature to the comic shanns nerd font

### Additional Context

I already checked this issue has been created before and found there is font https://github.com/wayou/comic-mono-font
With ligatures support but it did not have other things like nerd Braille character 
You can add seperate font in the zip with ligatures named please add

**Comment by Finii** [comment]
The heritage and who-forked-what for the Comic font(s) is complicated. The font has been forked and modified so often...

We use https://github.com/jesusmgg/comic-shanns-mono here, because it had some essentials fixed and a somewhat active developer. The font you mention is based on one a repo one generation "older". That means while it has arrow ligatures (and those use Fira glyphs and NOT Comic glyphs making them look kind out of style)

The scope of Nerd Font is to add icons to existing fonts. If you want ligatures added that should be suggested/implemented upstream at the font source (i.e. Comic Shanns Mono).

But I would suggest you just take _ComicShanns Nerd Font_ and run it through the [Ligaturizer](https://github.com/ToxicFrog/Ligaturizer) which is quite simple. And nothing else has Wayou done (according to the readme).

> not have other things like nerd Braille character

There is no Nerd Braille?

P.S. If you have problems running the Ligaturizer I might be able to help, or ask at their repo
