### ISSUE TITLE
JetBrains Mono, symbol desktop is wider than others.

### ISSUE THREAD

**Issue by tnlanh** [ryanoasis/nerd-fonts#1734]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related or helpful
- [ ] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ ] I have checked the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

### Experienced Behavior

The desktop icon is wider than other icons.

### Expected Behavior

The desktop icon should be as wide as other icons.

### Example Symbols or Text

```
drwxr-xr-x     - tnlanh 23 Dec  2023  .tmp
drwxr-xr-x@    - tnlanh  9 Nov 03:49  .tmux
lrwxr-xr-x@    - tnlanh 10 Nov 02:57  .tmux.conf -> dotfiles/.tmux.conf
drwx------     - tnlanh 16 Nov 02:03  .Trash
drwxr-xr-x@    - tnlanh 13 Nov 17:37  .vim
.rw-------@ 8.3k tnlanh 13 Nov 18:13  .viminfo
drwx------@    - tnlanh 31 Oct 20:44  .vnc
drwxr-xr-x@    - tnlanh  6 Nov 17:28  .volta
drwxr-xr-x     - tnlanh 27 Apr 23:57  .vscode
.rw-r--r--@  63k tnlanh 16 Nov 13:07  .zcompdump
.rw-r--r--@  63k tnlanh 16 Nov 13:07  '.zcompdump-Lanh’s MacBook Pro-5.9'
.rw-------@  18k tnlanh 16 Nov 13:07 󱆃 .zsh_history
lrwxr-xr-x@    - tnlanh 10 Nov 02:57 󱆃 .zshrc -> dotfiles/.zshrc
drwxr-xr-x@    - tnlanh 15 Nov 17:10  Applications
drwx------@    - tnlanh 16 Nov 00:15  Desktop
drwx------@    - tnlanh  3 Nov 18:24  Documents
drwxr-xr-x@    - tnlanh 15 Nov 16:24  dotfiles
drwxr-xr-x@    - tnlanh  6 Nov 17:40  dotfiles-backup
drwx------@    - tnlanh 16 Nov 02:03 󰉍 Downloads
lrwxr-xr-x@    - tnlanh 12 Jun 09:08  Dropbox -> /Users/tnlanh/Library/CloudStorage/Dropbox
drwx------@    - tnlanh 12 Sep 01:18  Library
drwx------     - tnlanh 17 Oct 00:18 󰿎 Movies
drwx------     - tnlanh 29 Sep 18:57 󱍙 Music
drwxr-xr-x     - tnlanh 16 Nov 00:18  OrbStack
drwx------     - tnlanh  7 Nov 14:06 󰉏 Pictures
drwxr-xr-x     - tnlanh 13 Nov 01:52  Projects
drwxr-xr-x     - tnlanh 24 Nov  2023  Public
```

### Font Used

JetBrains Mono

### Terminal Emulator (and the title of the terminal window)

iTerm2

### Operating System and Version

macOS 15.1

### Screenshots

<img width="922" alt="SCR-20241116-bepk" src="https://github.com/user-attachments/assets/4ce5b5cf-ad36-4fe3-9cb1-f1cba93ca603">

**Comment by Finii** [comment]
Can you copy and paste the text of the screenshot into a comment, well as text? To find out the codepoint of the desktop icon. 

You might not see the icon in the browser, but we can still find out the code. 

Sent from Nine
________________________________
From: Lanh Trần ***@***.***>
Sent: Friday, November 15, 2024 18:17
To: ryanoasis/nerd-fonts
Cc: Subscribed
Subject: [ryanoasis/nerd-fonts] JetBrains Mono, symbol desktop is wider than others. (Issue #1734)

Requirements
I have searched the issues for my issue and found nothing related or helpful
I have searched the FAQ for help
I have checked the Wiki for help
Experienced Behavior
The desktop icon is wider than other icons.
Expected Behavior
The desktop icon should be as wide as other icons.
Example Symbols or Text
No response
Font Used
JetBrains Mono
Source of Font File
No response
Terminal Emulator (and the title of the terminal window)
iTerm2
Operating System and Version
macOS 15.1
Screenshots

**Comment by tnlanh** [comment]
Hi @Finii, I have updated the issue to attach the text. Thanks.

**Comment by Finii** [comment]
Codepoints

* Desktop U+F108
* Folder U+E5FF

## Desktop - Font Awesome set

![image](https://github.com/user-attachments/assets/61097a1d-9670-4d74-b93d-ab8bee2c7100)

## Folder - Custom set

![image](https://github.com/user-attachments/assets/45ef0ceb-461f-48d4-bd93-2ec1cc067179)

## Comparison detail

![image](https://github.com/user-attachments/assets/6cbea6b7-5bf8-4a6e-9001-5c7acf54536f)

Ah, this has already been fixed in
* #1722

New release `Nerd Fonts 3.3.0` will be out soon-ish ;)
