### ISSUE TITLE
icons and symbols not redering on cli as expected to be done by the test-fonts.sh script

### ISSUE THREAD

**Issue by jagdishadusumalli** [ryanoasis/nerd-fonts#1735]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have checked the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

### Experienced Behavior

i see all unicode characters being printed instead of icons

### Expected Behavior

i wanted the script to prints the icons and sysmbols but it does not as shown in screen shot
printf '\uF013 \uF120 \uF121 \uF126' ...Works perfectly..shows symbols
echo "\uF013 \uF120 \uF121 \uF126" ...Works perfectly..shows symbols

### Font Used

Fira-code-nerd-font

### Terminal Emulator (and the title of the terminal window)

iterm

### Operating System and Version

macos sequoia 15.1 with bash, zsh and fish (tested on all)

### Screenshots

<img width="1536" alt="test-fonts" src="https://github.com/user-attachments/assets/d9656bf9-00b3-4aa0-b664-089b6cb09bd1">

**Comment by Finii** [comment]
The problem is MacOS' ancient `bash` version.

```console
$ bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin24)
Copyright (C) 2007 Free Software Foundation, Inc.
```

Almost 18 years old will just not work ;) It's old enough to drive a car and drink alcohol.
 If you use Homebrew try pouring a recent version of bash.

See for example [1]. With that it is no problem:

<img width="822" alt="Screenshot 2024-11-17 at 09 08 04" src="https://github.com/user-attachments/assets/7dcea313-2851-481f-bd50-de22b1a7c8de">

_I have no Nerd Font selected in iTerm_

```console
$ /opt/homebrew/bin/bash --version
GNU bash, version 5.2.37(1)-release (aarch64-apple-darwin24.0.0)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

There are several scripts here that require at least bash version 4. Of course we could rewrite the scripts for zsh (which I use, and which is the default on many systems nowadays), but that would take a considerable amount of time, so please understand that users are just required to use something more recent.

[1] https://dev.to/bphogan/use-modern-bash-shell-on-macos-22a6
