### ISSUE TITLE
Installation denied because of invalid fonts

### ISSUE THREAD

**Issue by duytrung** [ryanoasis/nerd-fonts#196]
#### Subject of the issue

Invalid font files

#### Your Setup

3270 Nerd fonts
#### Optional

![image](https://user-images.githubusercontent.com/2046672/30464619-adf25f02-9a11-11e7-9cbd-01564a6583be.png)

Could anyone please check for this bug? I have tried on my Windows 10 desktop.

Thanks

TN

**Comment by ryanoasis** [comment]
@duytrung Thanks for the report!

I really must apologize because I am aware that 3270 has a name issue on Windows.

For more information see my comment here: https://github.com/ryanoasis/nerd-fonts/issues/12#issuecomment-282446635

This is why it is showed as unknown/unsupported/untested status in the table: https://github.com/ryanoasis/nerd-fonts#patched-fonts

---

@duytrung Were you able to install any other of the fonts on Windows?

**Comment by ryanoasis** [comment]
Almost positive related to #12 (Windows not liking the 3270 font name)

**Comment by ryanoasis** [comment]
Source of issue: https://github.com/rbanffy/3270font/issues/1

I am going to grab the latest 3270 font and repatch.. that should take care of this issue

**Comment by ryanoasis** [comment]
This should now be fixed. Tested on Windows 7 but I was able to replicate the same issue that you gave before.
