### ISSUE TITLE
Fonts from 2.0 release are not being correctly identified as Monospace

### ISSUE THREAD

**Issue by notrev** [ryanoasis/nerd-fonts#270]
#### 🎯 Subject of the issue

**Initial issue description (from 23/May/2018)**
I use Meslo LG M for Powerline and want to use the Nerd Fonts patched version. I tried all Meslo LG M in the repository, but none of them appeared in the gnome-terminal's fonts list. they were listed in the system, thought (in the fonts application).

I also downloaded the original ones, without any patches, and they got listed.

Anyone has any clue about how to fix this?

**Update 24/May/2018**
I have also tried `Droid Sans`, and it is not being listed too.
I downloaded Terminator to see if it lists them, and it did.

**Update 31/May/2018**
With other people experiencing the same issue with other fonts, the issue's title was updated from "Meslo fonts not being listed on gnome-terminal" to the current one, as suggested by @gargoyle.

#### 🔧 Your Setup

- Meslo LG M forPowerline, trying to change to Meslo LG M Nerd Fonts
- Gnome terminal
- Ubuntu 18.04

**Comment by gargoyle** [comment]
I have the same with the three I have tried so far:- Hack, Anonymous Pro and Bitstream Vera. 

I've installed "Font Manager" which has a bit more functionality than the standard Gnome "Fonts" app, and it it showing all three of these as having proportional spacing - which is why Gnome Terminal will not list them.

I downloaded the files from the release archive (https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.0.0) as per the instructions.

**Comment by joke2k** [comment]
I tried with Fura, and I found the same issue.
The gnome terminal ignore fonts with "proportional spacing".
the font became proportional after the patch?

**Comment by matjam** [comment]
So, try this

sudo rm /etc/fonts/conf.d/70-no-bitmaps.conf

I know its not a bitmap font but I have had more luck since I did that.

**Comment by joke2k** [comment]
Could be works, but I don't like this solution.
This package says: 

> Monospaced (fixed-pitch, fixed-width) or double-width (non-monospaced) glyphs version of each font

And it would be awesome to have them works without this fix

**Comment by notrev** [comment]
@matjam, I tried your solution, but it did not work or me. It listed a lot of new fonts, but not `Meslo LG M`, which is the one I want

**Comment by gargoyle** [comment]
Workaround = Goto Releases, Click Tags, Select 1.2, Download.

**Comment by joke2k** [comment]
@gargoyle it seems to work, with Fira font at least.
Is there a bug with 2.0?

**Comment by gargoyle** [comment]
Yes. Something has gone wrong with the build process for 2.0 and none of the fonts (None of the 6-8 that I have tried, anyway) have the correct "spacing" parameter, so they are not being recognised as monospaced fonts when they are installed.

The 1.2 ones all seem fine.

**Comment by notrev** [comment]
The workaround proposed by @gargoyle works, but the glyphs are small. I read that this is known and there is not much to be done because of the _mono_ font type.

My way of solving this was to change from gnome-terminal to ROXterm, as it is very much like gnome-terminal and accepts the non-_mono_ version of the Meslo font.

Should I close this issue, or should I leave it open, as the issue still persists for gnome-terminal?

**Comment by gargoyle** [comment]
My gut feeling is that it would be @ryanoasis decision to close or not. 

However, you might want to re-name the title since it's not only an issue with gnome-terminal. The 2.0 versions will not show anywhere when you are searching for Monospaced fonts.

Title suggestion: "Fonts from 2.0 release are not being correctly identified as Monospace"

**Comment by ryanoasis** [comment]
Hey thanks everyone this is definitely a big issue that I have been following along with quietly. I won't be able to contribute too much to this project for the next several months but if I get some time and there are quick wins or PRs I will do my best :smile:

**Comment by xasx** [comment]
They do not appear in the selection box, however, with any gconf editor one can set the font of the respective profile manually.

I used dconf-editor and modified the value in the respective profile found beneath `org/gnome/terminal/legacy/profiles:`

**Comment by gargoyle** [comment]
I'm not sure I would recommend that, @xasx. The developers of gnome-terminal have deliberately put measures in place to make sure only monospaced fonts are used. 

If you use a gconf editor to "get round" that limitation, then you are opening yourself up to possible problems/issues which the developers have tried to avoid or would not expect to happen.

**Comment by xasx** [comment]
@gargoyle I'd not generally recommend this. However, it is a way I found to make something work that should be actually working - that said, keep in mind that the bug is actually on NerdFonts side making it impossible for gnome-terminal to correctly detect it as being monospaced (or usable, whatever counts).

**Comment by westernmagic** [comment]
Reverting 31d7524 and recompiling fonts seems to solve the issue (with Fura Code and Qterminal).

**Comment by philFernandez** [comment]
I downloaded Terminator, which I believe is a fork of Gnome Terminal, and nerd fonts show up and work perfectly there. The functionality and settings options of Terminator and Gnome Terminal are very similar.

**Comment by phcerdan** [comment]
Hitting this from aur package in ArchLinux, which uses latest release. Gnome terminal does not recognize most of the fonts as monospace, so they are not showing up.

**Comment by haasosaurus** [comment]
i fixed this in my fork, i did a pull request. i'm new at this, sorry.

**Comment by zfil** [comment]
@haasosaurus you need to do a pull request on this project not on your fork.

**Comment by haasosaurus** [comment]
you can use the fonts in this branch of my fork for the time being, let me know if they work if you try them please. https://github.com/haasosaurus/nerd-fonts/tree/regen-mono-font-fix

**Comment by mrcush** [comment]
There's a way to get around this with everything working for the Gnome-Terminal.  Start up "dconf-editor" in the terminal.  Then go to org>gnome>terminal>legacy>profiles:>profile id>font and change the custom value to the font you wish to use.  So far the Meslo LGL font you would put in MesloLGL Nerd Font Regular 12
12 being the font size.

**Comment by gargoyle** [comment]
@mrcush Already mentioned above why that might not be a good idea. 

If you mess with dconf-editor manually, you could get the application into states the developers didn't anticipate.

**Comment by mrcush** [comment]
@gargoyle
Sorry, read through almost the whole thread and missed someone else recommending the same thing. I do think the fonts and the patcher should get fixed so that there doesn’t have to be a workaround however I don’t see any issues that could really arise except for issues with spacing if you are trying to use a non monospaced font. If you’re throwing in a monospaced font there shouldn’t be an issue. 

I could be wrong though, what issues do you think could arise?

**Comment by weilbith** [comment]
@haasosaurus I've gone for your fork while waiting for the PR. Works well, except that some special Unicode characters are super small. Since they have a lot of details (at least more than ASCII ones), this makes them unusable. Example for [this character](https://unicode-table.com/en/2460/) in comparison to the rest of the prompt:
![1545908301](https://user-images.githubusercontent.com/12543647/50478271-9d64fe80-09d0-11e9-8f98-2ae3c1c0e047.jpg)

**Comment by gymgle** [comment]
Nerd fonts, Awesome fonts couldn't list in terminal, so we couldn't select the font we want.

You can set any font using `dconf-editor`, under `/org/gnome/terminal/legacy/profiles:/:<profile-id>/font`.

e.g. Custom value : `DroidSansMono Nerd Font Book 13`

https://askubuntu.com/questions/1046871/nerd-font-not-fond-in-terminal-profile/

**Comment by gargoyle** [comment]
@mrcush / @gymgle, yes `dconf-editor` can be used for a work around and in this instance the risk is probably limited to character spacing issues.

However, it shouldn't become habit to use such a tool without due consideration. Today it's just a font issue, tomorrow it could be something a bit more critical.

As an example, make a mental node of this little gem which seems to becoming an increasingly popular way to tell users to install some bit of software:-

`wget https://my.web.address/projectx/installer.sh | sudo bash`

Yes, it's a one liner that any fool can copy and paste. But it doesn't stop it being dumb.

**Comment by villasenor** [comment]
The fork that @haasosaurus has worked immediately for me with a Gnome 3 Terminal / Ubuntu 18.04 setup. Are we waiting for a PR at this point @brennanfee?

**Comment by ryanoasis** [comment]
Thanks all. Getting back up to speed on things

**Comment by mg979** [comment]
All ttf fonts are broken in Windows (they don't show up with `:set guifont=*`). otf fonts work.

**Comment by brennanfee** [comment]
@villasenor I don't have a pending PR for this.  However, I can report that I have verified the fork and patch that @haasosaurus created and the fonts work on windows for the console and various editors.  @mg979  I was also able to verify that the fonts show up in gVim (on windows) when using :set guifont=*

**Comment by ryanoasis** [comment]
Thanks @brennanfee and @mg979

**Comment by mafuba** [comment]
Any update here? Really looking forward to this fix.

**Comment by Jaykul** [comment]
Anything we can do to get this released? Could be lots of interest in NerdFonts after the demos of the new Windows Terminal at \\Build\ conf this week 😉

**Comment by ryanoasis** [comment]
The only thing blocking is me (https://github.com/ryanoasis/nerd-fonts/pull/283#issuecomment-480559848) testing out the #283 PR specifically the possible issue that https://github.com/ryanoasis/nerd-fonts/pull/283#issuecomment-465654029 brings up. If someone else wanted to test out the issue brought up and either fix it or be unable to replicate then I'd be inclined to merge.

Perhaps we could even just merge knowing the side effect. I am torn.

I won't be able to do much on the project until June unfortunately. Thanks for the patience

**Comment by Jaykul** [comment]
The actual built fonts in from [regen-mono-font-fix/patched-fonts](https://github.com/haasosaurus/nerd-fonts/tree/regen-mono-font-fix/patched-fonts/FiraCode/Retina/complete) seem to have some issues with ligatures. I'm getting this:
![image](https://user-images.githubusercontent.com/192942/57575767-0b114480-741f-11e9-9454-f7f7975df23b.png)

**Comment by krokofant** [comment]
@ryanoasis Merge it, seems weird to wait so long to fix something that is broken. If it introduces another bug then let's have at it.

**Comment by BlueDrink9** [comment]
It does seem like this is preventing many programs from recognising the fonts as usable, which affects a lot of people hugely. The blocking bug only affects those that use ligatures/diacritics, and even then they can still use the rest of the font.
Utilitarianism suggests merge

**Comment by ryanoasis** [comment]
#283 has been merged, sorry for the wait. Let's move forward :smile:

**Comment by damnskippy** [comment]
@ryanoasis is there a way to download patched fonts with this fix?  Thank you.

**Comment by ryanoasis** [comment]
@damnskippy Not at the moment. We need to run the rebuild script to re-patch all the fonts (takes a few hours). This isn't an issue but I'd like to batch several source font changes in too (since we are rebuilding anyway to avoid having to rebuild the source fonts for each change). E.g. #289 will likely be done before re-patching everything. Thanks

**Comment by errantepiphany** [comment]
Hi @ryanoasis . I'm sorry to bug you, as I'm sure you're very busy. But may I please ask when you might be able to run the rebuild script to re-patch all the fonts, now that https://github.com/ryanoasis/nerd-fonts/pull/283 has been merged? Even if the fix for https://github.com/ryanoasis/nerd-fonts/issues/289 is not ready yet, I think getting re-patched fonts sooner will help a lot of people. Thank you very much - we appreciate it!

**Comment by ryanoasis** [comment]
@errantepiphany No worries, I am going to try to push out `2.1.0` release this month, so I will be re-patching all the fonts at least once if not multiple times until things appear to be correct. Thanks!

**Comment by errantepiphany** [comment]
@ryanoasis Awesome news - thank you!

**Comment by BlueDrink9** [comment]
Hi Ryan, would you mind giving a status update here please?

**Comment by ryanoasis** [comment]
@BlueDrink9 I am updating the changelog for `2.1.0` as I type this
