### ISSUE TITLE
Gap in separator when defining custom icon in powerlevel9k

### ISSUE THREAD

**Issue by boolim** [ryanoasis/nerd-fonts#272]
🎯 Subject of the issue
I am running ubuntu 18.04, and using Tilix. I have installed powerline patched fonts from their github. Tilix is configured to use powerlevel 9k with mode="nerdfont-complete" and i have defined a custom logo section to be show in prompt element. The font i am using is Hack NerdFont Regular, however the custom logo element's separator is showing a gap.
I tried using the powerline Hack font, the gap is gone, but it has problem showing certain glyphs. 

With Gap
https://user-images.githubusercontent.com/11088527/40609298-c9d413f2-62a0-11e8-85b0-2d42027ea05a.png

Glyph not showing for github
https://user-images.githubusercontent.com/11088527/40609397-17f1b922-62a1-11e8-8e46-c6655ffc4383.png

🔧 Your Setup

-  Hack Nerd Font Regular
- Tilix
- Ubuntu 18.04

**Comment by ryanoasis** [comment]
@boolim Thanks for the details. I will follow up when I get a chance but that'll be a while to be honest

**Comment by GohioAC** [comment]
I am having similar issues with Inconsolata NF Medium in tmux statusline.
![tmux status with gap](https://user-images.githubusercontent.com/35570967/41818370-19ff63b0-77cb-11e8-9f6d-5614162c27e9.png)

**Comment by cata0309** [comment]
Is there any solution to this ?? I am facing this problem and I can't find a solution

**Comment by budimanjojo** [comment]
I'm also having the same problem. And I don't think there's any solution for this. This is very sad

**Comment by Finii** [comment]
With gap you mean these lines?

![image](https://user-images.githubusercontent.com/16012374/215464041-56313445-6557-4512-be63-5759f76638f2.png)

![image](https://user-images.githubusercontent.com/16012374/215464151-a57fa6c9-9e2e-49ae-af5f-18396de49b2d.png)

That's an antialiasing problem.

* There have been several commits regarding this problem, maybe you can live with the current master?
* If not, try switching to monochrome instead of RGB pixel antialiasing.
* There is a pending #780 but I guess we do not need that (and it has adverse effects elsewhere)

Please reopen with screenshots if current master still is so bad :grimacing:
