### ISSUE TITLE
2.0 Hasklug fonts have mixed font names

### ISSUE THREAD

**Issue by brennanfee** [ryanoasis/nerd-fonts#273]
#### 🎯 Subject of the issue

Some of the Hasklug fonts are still using "Hasklig" while others are correctly using "Hasklug".

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_

Specifically the Hasklug family, 2.0 versions.  Not sure about previous versions.

**Comment by ryanoasis** [comment]
Thanks again @brennanfee . It'll be a while before I can make any meaningful contributions to be honest but when I get time I'll try to push this project forward bit by bit.

**Comment by brennanfee** [comment]
@ryanoasis As always your excellent project is much appreciated.  If I can get some time myself I may attempt a PR.  Best wishes.

**Comment by ryanoasis** [comment]
Hey @brennanfee I am not seeing this. I know it's been a while, I wanted to see if we could quickly resolve this issue. The current patched fonts seem correct and I did spot check on the files in the zip from 2.0 release and so far they look correct as well...

Well I do see a difference between `Family` and `Preferred Family` :thinking:

**Comment by brennanfee** [comment]
So, after the 2.1 release I decided to re-check the Hasklig(lug) font to see if things are fixed.

Turns out no.  It seems that a lot of the fonts are still being referred to as Hasklig rather than HaskLug.  I also discovered that many of the "Mono" versions do not have the "Mono" designation in the name so if the fonts are installed side-by-side they will conflict with the non-mono versions.

I have checked both Windows and Linux and it seems to a problem in both OSes (I haven't used my Mac in ages but would assume it would be affected as well).

Here are the font files that are incorrect (for each of these listed the mono and non-mono version are incorrect):

Black
Black Italic
ExtraLight
ExtraLight Italic
Light (these two, Light and LightItalic actually override each other only the italic version gets registered)
LightItalic
Medium
Medium Italic
Semibold
Semibold Italic

So, it seems that all but the standard 4 weights are the problem.  Regular, Bold, Italic, and Bold Italic all seem to be fine.

**Comment by ryanoasis** [comment]
That's unfortunate, thanks for checking on it!

**Comment by unikitty37** [comment]
I seem to be falling victim to this in JetBrains IDEs — I have to disable "show only monospaced fonts" to get Hasklug to show up in the font selection menu, and the IDEs are unable to switch to the italic version, meaning comments show as a load of boxes with question marks in them.

(I notice that the fonts where italics work for me have the word "Regular" in their names for the regular weight, whereas Hasklug is "Hasklug Nerd Font Complete" rather than "Hasklug Regular Nerd Font Complete". I don't know enough about the working of the font system to know if that's significant, though…)

If I try activating all weights of the non-mono version, I get a warning from Font Explorer X on macOS when trying to activate Hasklug Light Italic Nerd Font Complete, stating that it has the same PostScript name as Hasklug Italic Nerd Font Complete.

![Screenshot 2020-07-12 at 13 23 17](https://user-images.githubusercontent.com/139183/87246134-21f86000-c443-11ea-91bf-d8b7d5dc0b20.png)

**Comment by Finii** [comment]
Thanks for reporting.

The naming is indeed broken:

![image](https://user-images.githubusercontent.com/16012374/216761300-178c763e-f825-4093-874c-534066b42f43.png)

Well, which is expected - we have a fix that is at the moment in the final test phase and will be active for all fonts with `v3.0.0`.

If you can self-patch, try specifying `--makegroups`, which will enable the alternative naming engine.

**Comment by Finii** [comment]
* #1028

**Comment by Finii** [comment]
Release is in repo, release as packages pending.
