### ISSUE TITLE
Material Design Icons missing some icons

### ISSUE THREAD

**Issue by Hnaguski** [ryanoasis/nerd-fonts#279]
#### 🎯 Subject of the issue

It appears that some of the icons from the Material Design Icons set are missing, the ones I've found to be missing are:
* `battery-charging-outline`
* `battery-charging-10`
* `battery-charging-50`
The icons are not listed in the cheat sheet on [the nerd-fonts website](http://nerdfonts.com/#cheat-sheet) but they are on [the MDI website](https://materialdesignicons.com/) if you search for 'charging'

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ 
Sauce Code Pro Nerd Font Complete.ttf
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ 
st
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ 
Debian 9 Testing

#### ★ Optional
As you can see there are missing icons here
![Missing Icons on website](https://user-images.githubusercontent.com/29007712/41813879-c36c094a-770c-11e8-9f65-bdc5b45ce876.png)

Here are what all the charging icons should be
![All the correct icons](https://user-images.githubusercontent.com/29007712/41813890-eb4df31a-770c-11e8-8350-2a5e1a27b305.png)

**Comment by ryanoasis** [comment]
Thanks for bringing this up, I am trying to get my arms back around Nerd Fonts :smiling_imp:

**Comment by MaienM** [comment]
All of the wifi strength icons also seem to be missing (for example `wifi-strength-0`).

**Comment by CountZukula** [comment]
I'd like to see the wifi-strength icons as well! Very much liking the nerd-fonts packaging so far.

**Comment by skipmeister123** [comment]
I'm running into this too.


    Which font are you using (e.g. Anonymice Powerline Nerd Font Complete.ttf)?
    Hack Regular Nerd Font Complete.ttf
    Which terminal emulator are you using (e.g. iterm2, urxvt, gnome, konsole)?
    FluentTerminal
    Are you using OS X, Linux or Windows? And which specific version or distribution?
    Windows 10 Pro October 2018 update => WSL (Ubuntu 18.04.1 LTS)

**Comment by maxnordlund** [comment]
Same here, Sauce Code Pro Complete, iTerm2, OS X. I thought I should make a PR but I can't grok how this works. Then there's the question of existing code points, since you don't want to break old stuff. I'm not sure to amend a couple of runes like this.

Also, thank you for this awesome package, makes my daily life much nicer ❤️

**Comment by NomisIV** [comment]
This might be a necro bump, but I've done some research: 

The reason the charging battery icons are missing is that the ttf-file from which the material design icons are copied from does not include them. I went upstream to search for them in their latest ttf-file, and successfully found them at U+F089C to U+F089F. I have also found better Wi-Fi symbols.

I will try to update the ttf-file and adjust the ranges between which the icons are stored. If it works, I'll gladly try to make a PR.

I have attached the new ttf-file below.
[MaterialDesign-Webfont-master.zip](https://github.com/ryanoasis/nerd-fonts/files/4681839/MaterialDesign-Webfont-master.zip)

**Comment by skipmeister123** [comment]
You, sir, are a true everyday hero.

**Comment by maxnordlund** [comment]
Indeed, some true detective work right there.

**Comment by NomisIV** [comment]
I have dug around some more, and I now have a (not very good) fix. [This repo](https://github.com/Templarian/MaterialDesign-Font) is where I got the updated font where I found the missing symbols. I have been hesitant to download and install the TTF, as I am on arch and would rather find an AUR for it. Which is what I just found: [here](https://aur.archlinux.org/packages/ttf-material-design-icons-git/).

Yeah, that's the fix.

Since the font stores the glyphs in the private use area on plane 15, it can safely be used as any fallback font. However, in programs which does not load fallback fonts, or which only load a single font, or which cannot handle UTF-16 fonts, NerdFont is still the best bet.

For me this almost enough. I use alacritty for my terminal, and it seems to render the icons just fine. However, my statusbar (lemonbar) currently only supports UTF-8, and I have not got it working with the Material Design Font.

To conclude my research: it is not possible to add the missing symbols _in a sensible way_ without a massive reshuffle of all glyphs, or without sacrificing other unicode categories (like CJK Unified Ideographs).

If anyone with some experience with the font-patcher could modify it to implement the reshulle and use the new Material Design Icons font, I would be very grateful. I do not care about backwards compatibilty. Could this new version be added as a separete branch?

**Comment by skipmeister123** [comment]
Excellent work!  I'm glad that I'm not the only one annoyed by this problem.  Hopefully somebody steps up and Does The Things™.  (Hint: it won't be me. 🤣)


—
Hans Kokx

**Comment by ryanoasis** [comment]
Yeah. A major reshuffle (perfect way to describe it by the way 👍) won't happen anytime soon and will be at 3.0 release. There were terrible choices (by me) for some of the codepoints and we are paying the price 😅

**Comment by Animeshz** [comment]
`chart-box` and `chart-box-outline` are also missing 👀
