### ISSUE TITLE
Add Iosevka Term Slab

### ISSUE THREAD

**Issue by aswinmohanme** [ryanoasis/nerd-fonts#281]
It would be nice if you guys could support Iosevka Term Slab Officially, this would complete the Iosevka Family.

**Comment by ryanoasis** [comment]
Great suggestion, thanks

**Comment by aswinmohanme** [comment]
Thank you for the awesome fonts :D

**Comment by ryanoasis** [comment]
Thanks! They are already awesome fonts we just patch 'em :blush: and aggregate a bunch of things but I know what you mean :smile:

**Comment by neo-anderson** [comment]
I think slab version of this font has not been added to the collection. Why was this issue closed?

**Comment by mfiano** [comment]
Can we please get Slab added? Thanks!

**Comment by ankitp4t3l** [comment]
In case you want the font and don't want to wait. You can use the nerd fonts patching tool as describe [in the readme](https://github.com/ryanoasis/nerd-fonts#user-content-option-8-patch-your-own-font).

Note, the patcher tool does not work for .ttc collections, so you'll want to "extract" the .ttf(s) you are interested in and use the font patching tool on the .ttf(s).

**Comment by typkrft** [comment]
> In case you want the font and don't want to wait, you can use the nerd fonts patching tool as describe [in the readme](https://github.com/ryanoasis/nerd-fonts#user-content-option-8-patch-your-own-font).

From my understanding the patcher doesn't work on ARM.

**Comment by eggbean** [comment]
Has anyone nerdified this font which they can share?

**Comment by Finii** [comment]
@eggbean Supply links to the exact font files you like to have patched and I can upload them in a branch ;-)

**Comment by Finii** [comment]
> Note, the patcher tool does not work for .ttc collections

@ankitp4t3l Well, one could use #783 ;-D

**Comment by Finii** [comment]
The 'source' is on Github, like ,,, https://github.com/be5invis/Iosevka/releases/tag/v15.0.1

You see that there are trillions of different font sets :roll_eyes: 

Thought you would like `ttf-iosevka-term-slab-15.0.1.zip`.

Or if you can work with `ttc`s `super-ttc-sgr-iosevka-term-slab-15.0.1.zip`

Or ... whatever. That's why I ask, there are too many to choose from. With a lot of 'burnt in' SS (stylistic sets)....

Your links are for `Iosevka Slab` `Regular` and `Medium`.
This Issue was about `Iosevka Term Slab`
Hmm.

?? :-D

**Comment by eggbean** [comment]
@Finii Oh, well Iosevska Term Slab (Regular and Medium) would actually be what I would prefer, of course. I just didn't realise that it existed, as I couldn't find it. And I didn't realise that they were already in the repository.

What are super-tcc fonts? Do they include HJK characters or something like that?

**Comment by Finii** [comment]
`ttc` = true type collection. Instead of having multiple files with one style/weight (i.e. bold, italic, ...) each, one file that contains all styles/weights of a family. In principle they all can share glyphs, which is ... not utilized at least by us.

Just easier to manage. I do not know if all OSs support them, probably yes.

`super` ... I have no clue.

The patch run for ~~all~~ most of `ttf-iosevka-term-slab-15.0.1.zip` is running right now.
Had to build `fontforge` first, that took some time, was debugging something in ff :-}

**Comment by eggbean** [comment]
Thanks for the help.

**Comment by Finii** [comment]
* Did the patching with `fontforge` version `20201107-246-g0bf72b2f8` (`HEAD` at the moment) (i.e. with 16 bit field fix that corrupted Iosevkas).
* Did it with the new naming scheme, because the old naming is broken esp with fonts that have lots and lots of family members.
    * Use #723
    * Add `config_patch_flags="--makegroups"` to `src/unpatched-fonts/Iosevka/config.cfg`

Patch results can be found here:
https://github.com/Finii/nerd-fonts/tree/feature/Add-Iosevka-Term-Slab-patched/patched-fonts/Iosevka

(Obviously I forgot Bold-Oblique ... sigh)

Note: Just the `Term Slab` variants were patched by me now, the other ones are untouched and can (i.e. will) contain errors.

Then, @ryanoasis: I believe we should change the directory structure:

At the moment we have
```
src/unpatched-fonts/Iosevka/Bold:
        iosevka-bold.ttf
        iosevka-term-bold.ttf
        iosevka-term-slab-bold.ttf
src/unpatched-fonts/Iosevka/Bold-Italic:
        iosevka-bolditalic.ttf
        iosevka-term-bolditalic.ttf
        iosevka-term-slab-bolditalic.ttf
```
which results in an equally set up `patched-fonts/` result.

Usually - I believe - people do not mix different Iosevkas and would rather have one Family in one folder like so:

```
src/unpatched-fonts/Iosevka/Standard:
        iosevka-bold.ttf
        iosevka-bolditalic.ttf
src/unpatched-fonts/Iosevka/Term:
        iosevka-term-bold.ttf
        iosevka-term-bolditalic.ttf
src/unpatched-fonts/Iosevka/TermSlab:
        iosevka-term-slab-bold.ttf
        iosevka-term-slab-bolditalic.ttf
```

And/or with the `Bold/` and `Bold-Italic` as sub folders.

I guess the reason for the `Bold` etc folders is, that the result will have 4 fonts for each input font, which can become confusing.

But then again, it is unlikely that people want a windows-compatible AND a normal font, so why are they grouped together?

What about
```
patched-fonts/
              standard/
              mono/
              windows-compat/
              mono-windows-compat/
```
And then the individual fonts below these?

Whatever. ;)

**Comment by eggbean** [comment]
It's insane how many variants this typeface has. Thanks a lot!
