### ISSUE TITLE
"FontForge module is probably not installed" but on Windows WSL

### ISSUE THREAD

**Issue by jcklpe** [ryanoasis/nerd-fonts#284]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

I'm running into an issue that looks to be the same as this one: https://github.com/ryanoasis/nerd-fonts/issues/225

Except that I am on Windows using WSL. I am a designer learning to code so I'm not totally up on the differences between Mac and WSL but from what I can tell I don't think their solution will work for me because of file path differences.  Any suggestions on what I should do?
#### 🔧 Your Setup

- Input Mono
- Hyper 2
- Windows 10 WSL Ubuntu 18.04

I also tried installing fontforge but the ppa provided by fontforge is not been put out for Ubuntu 18. I tried to compile it from source (something I've never done before) and I almost got there until the compile make threw an error that I didn't understand. I also tried installing it via a deb package I found online but it said it was unable to locate the package even though I was in the exact same folder as it. 

Any help would be appreciated. I'm going to go try and do this on my Linux machine but it would be nice to have access to fontforge on my windows machine and it seemed worth reporting.

**Comment by thedonquixotic** [comment]
Okay I'm trying this on a straight Kubuntu machine and it is not working.... same error.

**Comment by thedonquixotic** [comment]
Okay I got this to work. I opened up the file and I saw that it was in python and that the thing that was throwing the error had to do with psMat. I don't know what that is but from what I can tell it has something to do with fontforge being installed in python 3 but not 2 on Ubuntu so in order to run the script I had to use my command like this:  https://stackoverflow.com/questions/29441053/importerror-psmat-is-not-a-built-in-module

`fontforge -script script.py {{name of font to be changed}}`

This also required me to rename font-patcher to font-patcher.py

This fixed my issue as far as I can tell. I'm now trying to install the fonts which I can't because the owner is set to root. So I'm trying to figure out how to do this. 

I'm not closing this issue yet as I haven't received a response and I think this case should be included in the documentation. I was using a fresh install so I doubt this would be a unique occurrence. @ryanoasis can of course close this issue as he wishes, but I think some kind of information should be included in the instructions.

**Comment by efade** [comment]
I had the same issue with openSUSE. Your solution worked for me. Looks like the script needs to be updated.

**Comment by jrhalchak** [comment]
I couldn't get past this issue on Windows 10 proper, but this seems to have worked for WSL.

I had to install `pip` and `config-parser` as well, and then run:
`fontforge -script font-patcher {flags} {font-filename}`

**Comment by AkechiShiro** [comment]
I've had the same issue on Linux, PopOS 20.04 (Kinda of similar to Unbuntu 20.04) but it's probably because my default `python` binary refers to `python3`, your solution worked as well for me.

**Comment by chrisant996** [comment]
Same problem on Windows 10.0.19041. Installed FontForge, but the fontpatcher.py script can't import psMat and I'm left to manually figure out how to placate the fontpatcher.py script.

**Comment by Finii** [comment]
Thanks for reporting and the information.

To be honest I never ever run the script directly, always through `fontforge`. And you are right the messages and docu on the web page could be improved.

**Comment by Finii** [comment]
Fixed:
* ac60053b3a57  `font-patcher: Correct python module missing message`
* d083aa654  `docs: Improve self-patching instructions`

**Comment by chrisant996** [comment]
Thanks, @Finii !
