### ISSUE TITLE
Some font spacing is too large or can not be aligned

### ISSUE THREAD

**Issue by ihexon** [ryanoasis/nerd-fonts#290]
![z](https://user-images.githubusercontent.com/14349453/44512640-d2dda080-a6ed-11e8-8e8d-8bfd4e6fb72b.png)

and

![z](https://user-images.githubusercontent.com/14349453/44512766-25b75800-a6ee-11e8-87a8-2b8399851d87.png)
I'm using termite and `Ubuntu Nerd Font Mono:style=Book(first screenshot)` and `Ubuntu Nerd Font:style=Book`, Xterm and other terminal also has same issue...
I know I just change other font let the display be normal again...
but could this issue can be solve ?

**Comment by piersy** [comment]
@ryanoasis I'm also seeing this.  I downloaded the following 2 fonts

https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Ubuntu/Medium/complete/Ubuntu%20Medium%20Nerd%20Font%20Complete%20Mono.ttf

and

https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Ubuntu/Regular/complete/Ubuntu%20Nerd%20Font%20Complete%20Mono.ttf

I'm running
```
5.3.0-51-lowlatency #44~18.04.2-Ubuntu SMP PREEMPT Thu Apr 23 15:14:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
I installed the fonts with gnome-font-viewer v3.28.0 by double clicking them and selecting install. But even the font viewer preview was showing the extended spacing.

**Comment by Finii** [comment]
@MrJmpl3 

Hmm, here I compare `Ubuntu Mono 0.80` and UbuntuMono Nerd Font 0.80;Nerd Fonts 2.3.0-RC`.

![image](https://user-images.githubusercontent.com/16012374/206008004-76fb615c-19ca-4fb6-85e1-18ea58e0fdb9.png)

This looks like both are 500 wide.

Can you show a screenshot, give the version numbers and concrete font file names, and maybe download links?

**Comment by Finii** [comment]
@piersy @ihexon 

It is another story with `Ubuntu Nerd Font Mono` (not to be confused with `UbuntuMono Nerd Font` or `UbuntuMono Nerd Font Mono`.

`Ubuntu` is a proportional font. It has slim small-`i` letter and very wide capital-`M` letter.

![image](https://user-images.githubusercontent.com/16012374/206012885-d9c3dfde-7191-4f29-9d0e-790eb383eea4.png)

The `i` is 253 and the `M` is 871 wide.

The `Nerd Font Mono` variants of fonts are strictly monospaced. That means that all letters and symbols have the same width. In this case it means that the existing `i` needs to grow to fill the whole 871 which will look very ugly. You usually can not create a monospaced font from a proportional font without a lot of work (done by font designers).

This is the reason why finally the `Nerd Font Mono` variants are no longer created from proportional source fonts.
See more explanations at

* #912 

Further down you see some examples.
Note that this is because of the contradicting design goals of proportional and monospaced fonts. This can not be solved.

If you want to use a monospaced `Ubuntu` variant you can/have to use `Ubuntu Mono` (i.e. `UbuntuMono Nerd Font`).

P.S. You might say: Why so drastic; just patch in the symbols monospaced and leave the font as it was (i.e. proportional). But which width shall the symbols be scaled to? The `i` or the `M`? Or in between?
It also would break the property that all `Nerd Font Mono` fonts can be installed in terminals that only support monospaced fonts (like Gnome Terminal). So that is not really a solution.
