### ISSUE TITLE
Operator Mono Powerline Symbols

### ISSUE THREAD

**Issue by MatthewCushing** [ryanoasis/nerd-fonts#293]
After patching the operator mono medium font using the font-patcher (Thanks so much for this tool by the way).  I came up with the issue a lot of people have, the powerline symbols not matching up by being too small.  Is there a specific way to go about this and fix it?  I don't mind fixing it myself, I just don't really know what tool to use to do it.

**EDIT:** I opened up the font in font forge.  Now my issue is locating the actual powerline symbols out of the (it seems thousands) of locations it could be in.  Is there a simple way to find the location of the powerline font symbols?  Thanks!

**EDIT2:** Actually, looking through twice now I don't think they are in there.  I assumed patching a font gave it all of the icon packs but I think I really only see the devicons pack.  Is this normal?

Appreciate the help.

**Comment by mrcush** [comment]
No problem.  Looking at the font patcher file I may have found the issue.  Under `PATCH_SET` it lists the glyphs.  Devicons is labeled with `'Enabled': True` while every other font is labeled with a variable that you have set as true if it satisfies the if statement.  The if statement being:
`if args.complete:`
`    args.fontawesome = True`
`    args.fontawesomeextension = True`                                                                  
`    args.fontlinux = True                `                                                             
`    args.octicons = True               `                                                               
`    args.powersymbols = True    `                                                                      
`    args.pomicons = True          `                                                                    
`    args.powerline = True         `                                                                    
`    args.powerlineextra = True`                                                                        
`    args.material = True `                                                                             
`    args.weather = True`
I'm assuming this is the issue because devicons successfully patches into the font but that's because it doesn't have an `args.devicons` but rather is just set to `True`
I'm going to try some testing around.  But figured I'd let you know what I just saw.
