### ISSUE TITLE
config_has_powerline in config.cfg might not have the intended effect

### ISSUE THREAD

**Issue by segevfiner** [ryanoasis/nerd-fonts#307]
#### 🎯 Subject of the issue

I think the `config_has_powerline` option in the `config.cfg` files used in the `gotta-patch-em-all-font-patcher!.sh` script might not have the intended effect, as the `--complete` flag to the font patcher already includes power line, so simply omitting the power line flag is not enough to get it to avoid patching the powerline glyphs.

This can lead to clobbering pre-existing powerline glyphs which are likely better aligned/looking.

**Comment by ryanoasis** [comment]
Hey yeah you are right. Well I think the font-patcher probably needs to handle that the same way it is for the ['removeligatures' ](https://github.com/ryanoasis/nerd-fonts/blob/2.0.0/font-patcher#L157).

The 'gotta patch em all' script seems to only use it for logging out the combinations and assumes 'complete'. It does correctly look for a config.json file and use it if found but then the problem is in the font-patcher to look for that value as I said above.

Thanks!

**Comment by Finii** [comment]
I always wondered what that was intended for. Only thing I could find was the variants counting thing.

Anyhow.

> This can lead to clobbering pre-existing powerline glyphs which are likely better aligned/looking.

In fact the opposite is true. We determine the 'cell' width and height in a certain way. The powerline glyphs must fill this cell completely (and or overfill for some given percentage). It is undefined if the original-font-powerline symbols would have the same cell size and overlap.

If you have a concrete instance where the patched in powerline symbols look worse we can certainly have a look at that font and reconsider (for that font). But as a general change I believe this will not always result in better scaling and makes the patching less reliable.
Think about people who self-patch font A, where we have that special rule for A in effect here. That rule will not be followed for self-patching and thus have a strangely different looking font.

So I would do that only in very exceptional cases. Please reopen if there is a concrete font that really needs it.
