### ISSUE TITLE
Wrong codepoints for Font-Awesome beginning on f00f in table

### ISSUE THREAD

**Issue by dritter** [ryanoasis/nerd-fonts#31]
Hi there!

When I use "Sauce Code Powerline Plus Nerd File Types Mono Plus Font Awesome Plus Octicons" the codepoints starting from `f00f` are off by one.
Example: The codepoint for [home-icon ](http://fontawesome.io/icon/home/) on the [table](https://github.com/ryanoasis/nerd-filetype-glyphs-fonts-patcher/wiki/screenshots/v0.4.0/fontforge-glyph-set-font-awesome-1.png) is `f015`. This should be the correct one, but if I do an `echo "\uF015"` it shows the wrong symbol. In the patched version the home-symbol has the codepoint `F014`. This is the case for all subsequent glyphs (seems to get worse with ongoing icons).

**Comment by ryanoasis** [comment]
Hey thanks for this info. I will look into it. 

I was taking a break but now wanting to work on projects again here and there. 

On this one I am reorganizing the patched folders to make fonts easier to find and then I want to merge in the 2 open PRs (hack font, fixes, and script refactoring)

**Comment by CestDiego** [comment]
@ryanoasis thank you for the awesome work. This fix would be greatly appreciated  :)

**Comment by ryanoasis** [comment]
@CestDiego Thanks it is appreciated.
***
@dritter You are 100% correct
***
@dritter , @CestDiego 
Ah I see what is going on here. I define the start and end range but quite a few of the glyphs in that range in font awesome are empty (e.g. `f010` zoom_out [fa-search-minus]). So that point on its off by one and then each time another empty glyph is encountered its off-by-1++ :blush: 

I will get to this after a bit of re-organization of the folders and merging in the 2 PRs :sweat_smile:

**Comment by CestDiego** [comment]
@ryanoasis no problem...I'm developing a package similar to fontawesome.el for emacs in which one can easily add the unicode symbols with autocompletion backends :) looks like this:
https://i.imgur.com/hP3Jyg0.png

**Comment by ryanoasis** [comment]
@CestDiego Ah I see. That looks very cool and useful! I can see that being very helpful especially if you are using font awesome heavily in a project.

I would have made a plugin for emacs similar to my vim plugin ([vim-devicons](https://github.com/ryanoasis/vim-devicons)) but I am a Vim guy :laughing: and I don't even know where to begin

If you need anything to make the font easier to use let me know (I see you already have one issue (#32) you opened :sweat_smile: )

**Comment by CestDiego** [comment]
@ryanoasis well yeah #32 is to make it easier to me to make Nix Expressions for NixOS packages :P but it would also be nice to download only the font one wants.

**Comment by ryanoasis** [comment]
@CestDiego I might ask you on #32 for more info on that subject. :blush: 

Yeah thats one problem right now with the directory structure. I was creating more subfolders for each family style but maybe I need subfolders for each glyphset variation because the names are very long

Website and interaction to let users pick is a very cool idea! I like it. :+1: 

The way I feel about this project right now is that there are a lot of little issues and a few big ones. I would love to get most of those ironed out and if this project starts to become more heavily used before creating a website. If/when those things happen then yeah definitely! :smile:

**Comment by CestDiego** [comment]
awesome :) I look forward to the merging of the Hack Font PR :P btw, how to know if I'm downloading powerline-extras with the name of fonts? it looks like the font I downloaded doesn't have it. Also regarding Octicons seem to have the same `shift` as font awesome... and I think there is some overlapping :(

**Comment by ryanoasis** [comment]
@CestDiego 'powerline-extras' is currently missing :disappointed: (see #30)

Yeah it looks like it will have the same off-by-* issue as font-awesome. Fix should be the same.

For Octicons I decided to put it in a different range because font-awesome starts at the same unicode but I think what I should do is if you choose Octicons without font-awesome THEN it could start it its original place. Obviously at some point there is a limitation into which glyphs can be included and some needing to be moved when you want to include a bunch into one font :worried:

**Comment by CestDiego** [comment]
So is Octicons kinda like >> fontawesome? it looks like github supports it natively...

**Comment by ryanoasis** [comment]
Yes similar in some ways. Yep it is the one used on GitHub :smile:
