### ISSUE TITLE
Monaco Nerd Font display is not normal

### ISSUE THREAD

**Issue by glepnir** [ryanoasis/nerd-fonts#333]
## Environment
* mac os 10.13.6 
## terminal
* iterm 2
##  Neovim
* neovim 0.3.4
## Problem
@ryanoasis  Hi your issue template is too complicated for me.Please allow me to break it.i use this [monaco nerd font](https://github.com/Karmenzind/monaco-nerd-fonts). Is its height abnormal? How to solve it？ like this pic
![13](https://user-images.githubusercontent.com/41671631/54203541-67361600-450d-11e9-9d8a-423dac2f7216.png)
I noticed that this problem has been around for a long time. I asked a question in [this issue](https://github.com/ryanoasis/nerd-fonts/issues/210). Unfortunately, I didn't get your reply. Is it because the copyright of monaco's font belongs to Apple company and it makes it difficult to fix it?

**Comment by ryanoasis** [comment]
Thanks for the report

**Comment by taigacute** [comment]
@ryanoasis   thanks for your work

**Comment by taigacute** [comment]
@ryanoasis   hi any update?

**Comment by ryanoasis** [comment]
@taigacute Sorry no not yet. Trying to catch up with everything

**Comment by ryanoasis** [comment]
@glepnir Just wondering if this was solved somehow or you just moved on :disappointed: ?

**Comment by fragilelambda** [comment]
@ryanoasis  This issue happens on mac too, any ideas to fix it?

**Comment by ranelpadon** [comment]
On my end, figured-out that in **iTerm2**, I could combine **Monaco** as main text font with **Melco Nerd Font** (or any nerd font) as the icon font. Then, adjusted some property of Monaco (e.g. the **94** value in the screenshot), so that the 2 fonts will align properly:

<img width="927" alt="Screen Shot 2020-08-13 at 6 47 31 AM" src="https://user-images.githubusercontent.com/4292088/90076565-ab48ce00-dd32-11ea-8502-d75b6496fb9f.png">
<img width="1418" alt="Screen Shot 2020-08-13 at 6 50 44 AM" src="https://user-images.githubusercontent.com/4292088/90076571-af74eb80-dd32-11ea-93d8-600750de76fe.png">

Which is comparable to when I'm using purely the **Melco Nerd Font**:
<img width="1440" alt="OMZ" src="https://user-images.githubusercontent.com/4292088/90076699-011d7600-dd33-11ea-8e0e-ab3adfe2b22e.png">

**Comment by fingertap** [comment]
> <img alt="OMZ" width="1440" src="https://user-images.githubusercontent.com/4292088/90076699-011d7600-dd33-11ea-8e0e-ab3adfe2b22e.png">

@ranelpadon  What is your colorscheme? What produces that Apple icon?

**Comment by ranelpadon** [comment]
@fingertap I'm using `Alacritty` now, not `iTerm2`. The big Apple logo is from `neofetch`, the small Apple icon in the command prompt is from [Oh My Zsh](https://github.com/ohmyzsh/ohmyzsh) framework.

**Comment by fingertap** [comment]
Thanks.

**Comment by fingertap** [comment]
For me, changing the fontsize solves the problem. For iterm2, I have to use fontsize=13 to get a perfect appearance. For smaller font, the icons seems not synchronize well with the text:
↓ fontsize = 12
<img width="100" alt="image" src="https://user-images.githubusercontent.com/7274689/165117414-28d3c68a-cf02-4696-b964-a69ca6743197.png">
↓ fontsize = 14
<img width="279" alt="image" src="https://user-images.githubusercontent.com/7274689/165118171-97929641-c2e9-4cb9-8d48-b0eceecc2844.png">

**Comment by Finii** [comment]
Hmm, **Monaco** has a rather unproblematic PPEM.

![image](https://user-images.githubusercontent.com/16012374/165124451-42bcc306-d733-4926-9901-edba368e33cf.png)

**Menlo** has a PPEM of 8, which is preserved by `fontforge`.

But then there are other flags that concern small rendering, maybe they are wrong. The picked commits also handle `ppem_to_int` ... Maybe worth a try for you, to see if that fixes it.
