### ISSUE TITLE
Folder Icons not showing up

### ISSUE THREAD

**Issue by EverWinter23** [ryanoasis/nerd-fonts#359]
#### 🎯 Subject of the issue
Every icon except the folder icon is working. Can't make it work. Changed fonts, still the problem persists.

#### 🔧 My Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ RobotoMono Nerd Font
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ urxvt
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Manjaro bspwm

**Comment by EverWinter23** [comment]
From Issue https://github.com/ryanoasis/vim-devicons/issues/59, the fix works, but I don't know why.  The docs explicitly say that it should work out of the box.
```
let g:WebDevIconsUnicodeDecorateFolderNodes=1
```

**Comment by ryanoasis** [comment]
Hey @EverWinter23 I think this issue should've been posted to VimDevIcons repo but no big deal. I know there is a lot of overlap/confusion at times.

Yes by out of box it means the basics but that was probably misleading. I have enabled folder nodes to show glyphs by default since you posted your issue. See: https://github.com/ryanoasis/vim-devicons/commit/69028519c368304a6bf95f629b924c2ea85c69db

I will close this for now. Please re-open if you still need help. Thanks
