### ISSUE TITLE
Operator Mono - Patched font displays artifacts with powerline glyphs - URxvt and Alacritty

### ISSUE THREAD

**Issue by ronasimi** [ryanoasis/nerd-fonts#370]
After patching Operator Mono, I get artifacts in the powerline glyphs.  Is there any easy way to specify glyph height/width using the patcher?
![window-20190821-14:12:52](https://user-images.githubusercontent.com/3991859/63458094-24fbf380-c420-11e9-9fd7-520c9e2586d2.png)

**Comment by ryanoasis** [comment]
Thanks @ronasimi . Sorry there currently is no easy way (or even a way at all) to specify specific glyphs height or width. It would be an interesting feature though!

**Comment by kgraefe** [comment]
I have the same effect caused by font smoothing (see https://github.com/mintty/mintty/issues/943 ).

Did you manage to fix your font manually?

**Comment by Finii** [comment]
@ronasimi Do you mean the small (colored) line?

![image](https://user-images.githubusercontent.com/16012374/216771128-9d08f52a-7c6c-4aa1-8b5a-aec28fc7668e.png)

This is caused by the antialiasing. Switch to greyscale antialiasing to prevent it.
There have been fixes that make it less obvious, though. Maybe try the latest release (`v2.3.3`)?

Otoh we also have the open PR
* #780 

But that has negative effects for other people so I would try to avoid that.
