### ISSUE TITLE
Use opentype stylistic alternates for easier entry

### ISSUE THREAD

**Issue by Chaz6** [ryanoasis/nerd-fonts#393]
Insteading of having to copy and paste from another program or use an alt sequence, it would be useful to be able to simply type for exampe `#books` and have the equivalent character appear using stylistic alternates. Another font which does this is Wayfinding Sans Symbols - https://fdi-type.de/fonts/wayfinding-sans-symbols/

**Comment by ryanoasis** [comment]
Oh that is very interesting

**Comment by Finii** [comment]
Thanks for the excellent idea!

This works with `Ligatures`. The problem is we need to set this up in a way that does not break the preexiting ligs in the source font. Albeit that might be possible (automatically, manually .. of course), we would add a rather big ligature table.

I will set the future tag and close.
