### ISSUE TITLE
CodeNewRoman: NerdTree icons are incorrect

### ISSUE THREAD

**Issue by lambda0xff** [ryanoasis/nerd-fonts#398]
When opening NerdTree, displayed icons are incorrect
![Screenshot 2019-10-30 at 09 18 19](https://user-images.githubusercontent.com/38687176/67840755-d7be9100-faf6-11e9-8842-dc801bcda108.png)

#### 🔧 Your Setup

- _Which font are you using : CodeNewRoman
- _Which terminal emulator are you using : iterm2
- OSX 10.15.1

**Comment by liuyinz** [comment]
same problem.

**Comment by Finii** [comment]
I guess you are using `CodeNewRoman`, as you provided in the description above.
You should instead use `CodeNewRoman Nerd Font`?

A lot information is missing here. If the issue is still existing, please open a **new Issue** and fill in all the fields. Also give/show your iterm setup, font selection etc. Please copy and paste the wrong glyphs as text into the issue. Afterwards we would be able to debug on your machine via for example `fc-list :charset=` but we need the wrong codepoint for that.
