### ISSUE TITLE
Change font naming convention (or allow custom names during conversion)

### ISSUE THREAD

**Issue by eugenesvk** [ryanoasis/nerd-fonts#42]
Currently both font file names and internal font names are a bit unwieldy.
The file names are too big and font names are unique for each style, which prevents Font Book from displaying them under one family group.
I understand the need to differentiate between many variants, though would prefer a simple
__SourceCodePro-Medium-mNOP__ instead of
__Sauce Code Pro Medium Plus Nerd File Types Mono Plus Octicons Plus Pomicons__
for file names and something similar for font names (e.g. __Source Code Pro mNOP__ font family while retaining original style names like __Regular__ instead of __Book__).

Would it be possible to adjust the naming convention during conversion or allow some user input (e.g. sourcing a file with "original font names:new font names" that could be used for naming instead)? I'm most interested in font names since file names are much easier to change.
Thank you!

**Comment by ryanoasis** [comment]
@eugenesvk 

These are good points and I agree with you pretty much!

I have actually been in the process of reorganizing the directory structure a bit to make ad hoc downloading easier (spurred from #32).

* Changing the family name to be consistent across variations *should* be one of the easier fixes you suggest.
* The variation tacking on the included glyphs is yes very ugly. A partial solution at least is underway where I am going to rename the one with EVERYTHING as: **< font name > Nerd Font Complete** since this is probably the variation that is going to be most used. Would this be useful? You probably downloaded the font that has all the glyphs anyway?
* User input: Yeah this could be an option and may help. It sounds like the other points you made are more of a concern but this might be a nice option to have as well.

**Comment by eugenesvk** [comment]
Yes, having a simple name for an all-inclusive font is a good idea since it is indeed typically the most useful variant. I would suggest though a slightly shorter name (e.g. __< font name> Nerd__ or __NerdAll__ if you insist on indicating everything is packed), since I've already run into trouble in Windows with long font names (I know you have an option to force shorter names, but would like the default to be work).
And then all other incomplete variations can be indicated though additional file name modifications (I'd suggest abbreviations as indicated above to keep the name short, but it's not critical since I'm only using the complete font type).

**Comment by ryanoasis** [comment]
@eugenesvk That is a good suggestion to keep it as short as possible. I was going with **Nerd Font** because it is the project name. I can see where having 'Font' part of a font name is a bit redundant however. **All** could also work in place of **Complete**.

I am not sure about those but I will definitely consider them :+1:

**Comment by ryanoasis** [comment]
Closing for now as this is partially implemented on v0.6.0. If it is not good enough we can discuss and implement on a later version :+1:
