### ISSUE TITLE
Some symbol glyphs show up as clipped.

### ISSUE THREAD

**Issue by ffernand** [ryanoasis/nerd-fonts#442]
#### 🎯 Some symbole glyphs show up as clipped.

v2.0.0 of the _Ubuntu Mono Nerd Font Complete_ (double-width version, not mono-version) now truncates/clips certain glyphs.

An example is the battery glyph (which I think comes from font-awesome). The top of the image below represents the font generated by nerd-font v2.0.0... and the bottom image with the clipped glyphs represents the font generated using nerd-font v2.1.0
 
![20200216T151526_maim](https://user-images.githubusercontent.com/69479/74621019-2c6b3380-5109-11ea-9a4c-554ccb1b340e.png)

Using git-bisect, I was able to trace the problem to this commit: https://github.com/ryanoasis/nerd-fonts/pull/283/commits/cf625d46b5018615efc2049b3c52585443ef2eaa

After playing with the content of the commit against v2.1.0 of `font-patcher`, the following patch fixes the problem for me.  It removes the negative bearings *after* setting the glyph width (undoing the partial change in that commit).  But at this point, I'm out of my element.  I'm not sure why this fix works for me, or if it introduces other problems.

```
diff --git a/font-patcher b/font-patcher
index b30b0a0c..8ec21c8f 100755
--- a/font-patcher
+++ b/font-patcher
@@ -762,10 +762,6 @@ class font_patcher:
             align_matrix = psMat.translate(x_align_distance, y_align_distance)
             self.sourceFont.transform(align_matrix)
 
-            # Ensure after horizontal adjustments and centering that the glyph
-            # does not overlap the bearings (edges)
-            self.remove_glyph_neg_bearings(self.sourceFont[currentSourceFontGlyph])
-
             # Needed for setting 'advance width' on each glyph so they do not overlap,
             # also ensures the font is considered monospaced on Windows by setting the
             # same width for all character glyphs. This needs to be done for all glyphs,
@@ -773,6 +769,10 @@ class font_patcher:
             # it should come after setting the glyph bearings
             self.set_glyph_width_mono(self.sourceFont[currentSourceFontGlyph])
 
+            # Ensure after horizontal adjustments and centering that the glyph
+            # does not overlap the bearings (edges)
+            self.remove_glyph_neg_bearings(self.sourceFont[currentSourceFontGlyph])
+
             # reset selection so iteration works properly @TODO fix? rookie misunderstanding?
             # This is likely needed because the selection was changed when the glyph was copy/pasted
             if symbolFontStart == 0:
```

The only clue for the change was a comment included in the original commit that *suggested* the opposite messed up glyph widths somehow...
```
# moved this after changing the bearings because i think it was
# messing up the glyph width to have it before
sourceFont[currentSourceFontGlyph].width = font_dim['width']
```

#### 🔧 Your Setup
* ArchLinux (i3wm)
* SublimeText 3, i3blocks, xfce-terminal

1. _Which font are you using?_
  Ubuntu Mono Nerd Font Complete.ttf (double-width)

2. _Which terminal emulator are you using?_
  xfce4-terminal

3. _Are you using OS X, Linux or Windows? And which specific version or distribution?_
  ArchLinux (latest updates)

**Comment by ryanoasis** [comment]
thanks for all the details and even digging into this! really appreciate it

**Comment by arbaes** [comment]
It seems I just ran into the same issue myself, it seems some glyphs are slightly off center for some reasons, resulting in a clipping when rendered:
![image](https://user-images.githubusercontent.com/34744917/81997931-7785db80-9651-11ea-80df-ad5f6199eac7.png)

**Comment by fabricio7p** [comment]
why this seems to happen with people using arch linux and some twm? 
Every nerd font except Fira Code is having the 'fi' ligature bug that shkws a telefone icon

**Comment by AntonFriberg** [comment]
On Sway and using Waybar I am having issue with Fira Code as well, although it is slightly better than Hack. (Notice the Battery icon "")
![scrn-2020-05-25-13-31-01](https://user-images.githubusercontent.com/14290517/82809287-11d4f300-9e8c-11ea-8f1c-ce8e5e737c68.png)

**Comment by GladOSkar** [comment]
I think i have the same issue. I just updated from an ancient version of `Fura Code Regular NerdFont Complete` (where double-width actually took up double the space of a character in the text) to the latest version (which is now called `Fira Code Regular NerdFont Complete`) but not even the double-width glyphs only move the cursor by one (mono) width, requiring a space after every double-width glyph.

Since a picture speaks a thousand words:
Before:
![image](https://user-images.githubusercontent.com/9497832/108920745-7ef10100-7635-11eb-8684-f5743cd9a9c4.png)
Now:
![image](https://user-images.githubusercontent.com/9497832/108920764-887a6900-7635-11eb-9fb3-4b09ad608eda.png)

Would be glad about any tips :)

**Comment by siduck76** [comment]
> On Sway and using Waybar I am having issue with Fira Code as well, although it is slightly better than Hack. (Notice the Battery icon "")
> ![scrn-2020-05-25-13-31-01](https://user-images.githubusercontent.com/14290517/82809287-11d4f300-9e8c-11ea-8f1c-ce8e5e737c68.png)}

looks fine for me : 

![image](https://user-images.githubusercontent.com/59060246/119211316-03391000-bacf-11eb-98bc-bb717c54679a.png)

**Comment by omar2205** [comment]
I managed to fix this clip by attaching an invisible char at the end
![image](https://user-images.githubusercontent.com/1373867/128448488-394e6f82-1d84-4e7d-91e5-7fdc768df088.png)

**Comment by omar2205** [comment]
I fixed this issue by adding an extra character 
![image](https://user-images.githubusercontent.com/1373867/128464490-6964f91d-5198-4cc8-9a1f-d292b861cde1.png)

I then copied the output (2 characters).
<sub> Note there might be `warn: Dropping unmatched character`</sub>

**Comment by siduck76** [comment]
> I fixed this issue by adding an extra character
> ![image](https://user-images.githubusercontent.com/1373867/128464490-6964f91d-5198-4cc8-9a1f-d292b861cde1.png)
> 
> I then copied the output (2 characters).
> Note there might be `warn: Dropping unmatched character`

same :)

**Comment by siduck76** [comment]
@ffernand do you still face this issue?

**Comment by ffernand** [comment]
@siduck76 In my original post, I have a patch that I used to rebuild nerd-fonts and had no issues since then.

I found the problem using git-bisect, but I was reluctant to create a PR out of the patch because it's not clear to me why it works.  Not that the patch is suspect, just that I know little of how font-patcher works :sweat_smile: 

So I leave the patch here as a clue for devs on how to fix this problem.

**Comment by siduck76** [comment]
ughh

> @siduck76 In my original post, I have a patch that I used to rebuild nerd-fonts and had no issues since then.
> 
> I found the problem using git-bisect, but I was reluctant to create a PR out of the patch because it's not clear to me why it works. Not that the patch is suspect, just that I know little of how font-patcher works 
> 
> So I leave the patch here as a clue for devs on how to fix this problem.

ughh when's the next release :( . Been waiting for it since ages now lol. It'll come with updated version of linux distro logos which I needed so kinda excited.

**Comment by fuegoio** [comment]
I have been using this patch for a year now, and never saw any issue. The fonts are working perfectly. I even changed my icon font several times, and they all worked perfectly. Great work, and I think it could be merged :)

**Comment by petermarks** [comment]
@Finii, is there a set of zips like https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/*.zip built with your patch? I'm using NixOS, so can alter the package spec to pull a patched release, but don't have the setup to build the fonts myself. I'd really like to test whether this solves the issue I experienced. I'm currently pinned to 2.0.0 as 2.1.0 is unusable for me.

**Comment by Finii** [comment]
@petermarks 

> I'm currently pinned to 2.0.0 as 2.1.0 is unusable for me.

Unfortunately no. Which font are you after?

**Comment by petermarks** [comment]
@Finii 
> Which font are you after?

I use DejaVu Sans Mono Nerd Font in Polybar and Hasklug in my terminal and editor. However, the NixOS package installs the whole set of fonts.

Don't worry about it, I have no need for anything that 2.0.0 doesn't have. I just thought I'd test it out to see if this resolves the issue for me.

**Comment by petermarks** [comment]
> I can create you these, so you can try them

Sure, if you can send me URLs where the package manager can pull them from, I'll give it a try.

**Comment by Finii** [comment]
Probably fixed with `v2.2.2`

**Comment by patrick96** [comment]
Can anyone confirm that this fixed it for them?

In xfce4 terminal, I am still getting clipped icons with UbuntuMono 2.2.2:

![2022-09-27-203603_726x209_scrot](https://user-images.githubusercontent.com/2452038/192609365-596617dd-4168-4a03-8fe4-67f5f4446900.png)

In addition, in polybar, UbuntuMono and Hack (non-mono) also still have the clipping, see https://github.com/polybar/polybar/issues/991

*Hack:*

![hack](https://user-images.githubusercontent.com/2452038/192610580-679ec584-6bd4-4ace-b6ba-cb736ad9e971.png)

*UbuntuMono:*

![ubuntu](https://user-images.githubusercontent.com/2452038/192610583-5624c3c5-c307-4e4e-b783-24abf02e0906.png)

**Comment by fiskhest** [comment]
I'm still seeing issues in polybar.

**Comment by Finii** [comment]
@patrick96 From the images you provided that is _not_ clipped.

What you miss is to insert a blank after the symbol like
```
$ echo "a\uf240 abc"
```

* You use a `Nerd Font` variant (not `Nerd Font Mono`) which means you want symbols bigger than one 'cell'
* These symbols need to extend into the next cell
* Any char in the next cell will overwrite the symbol (partially) of course

@fiskhest I must admit I do not know `polybar`. I guess that is a GUI thingy? Screenshots would always be helpful. Possibly the explanation in #940 is useful for these use in proportional contexts. Is the font 'hard coded' in that `polybar`, or did you choose that somehow?

**Comment by Finii** [comment]
Maybe we should (really, soon) add a `Nerd Font Proportional` for people who want big symbols in proportional contexts (like GUI elements). Otoh these GUIs should rather use the Symbols-Only font for the symbols, this is kind of a misconception.

**Comment by patrick96** [comment]
@Finii Thanks for the clarification, #940 cleared up some things for me. Do I understand correctly that the non-mono fonts basically have wide icons that extend over more than one cell (but still single cell text characters) and it's the terminal emulator's job (or any other application wanting to display them) to add the appropriate spacing after the wide icons?

[polybar](https://github.com/polybar/polybar) is a status bar where the user can basically put arbitrary text. Just so you can get an idea, here is a screenshot of my polybar:

![2022-09-28-222457_767x36_scrot](https://user-images.githubusercontent.com/2452038/192883277-80ad6097-4ee5-4ea5-a7e3-69d758b6eca9.png)

Many of our users use nerd fonts because they get a font that has all the icons they want and can also render text. Text and icons can be arbitrarily mixed, so conceptually polybar has to do a similar job as terminal emulators (just on a single line).

The fonts used by polybar are user-defined, so we can easily advise people to adapt their font choices. If I understood everything correctly, advising people to use a non-nerd-fonts font for text rendering and add `Symbols Nerd Font` as a fallback would fix this issue (and from my limited local testing this is indeed the case).

What I don't quite understand is why `Symbols Nerd Font` (non-mono) doesn't have the same issue. Do the symbols not extend into the next cell because the cells are bigger?

**Comment by Finii** [comment]
@patrick96 Thanks for the Polybar explanations and link. I will have a look there.

> Many of our users use nerd fonts because they get a font that has all the icons they want and can also render text. Text and icons can be arbitrarily mixed, so conceptually polybar has to do a similar job as terminal emulators (just on a single line).

Well, I do not know for sure, but I guess Polybar is more like an 'proportional' environment. Which means that the Symbols should have an advance-width that covers the full symbol, and not more. If you would go the terminal emulator way, a bigger symbol would be 2 'calls' wide in advance width, but only cover 1.5 widths in reality, left aligned. So you can never _center_ anything properly.

Another data point is maybe this comment: https://github.com/ryanoasis/nerd-fonts/issues/731#issuecomment-1008293952

I believe the 2-font-setup (one 'normal' text font and the `Symbols Only` font as fallback) is kind of ... something for Nerds ;-D
Technically this is possible of course, but if it has to be done by the end-user (as opposed to maybe the Polybar maintainers) this is something I would not expect.
Rather I guess what is needed is a 3rd variant of fonts. Let me restate the possible variants:
* **A)** Text monospaced (i.e. 'i' and 'M' same width), symbols scaled down to also fit into that width (`Nerd Font Mono`)
* **B)** Text monospaced, symbols big (but pretend to be small, left aligned) (`Nerd Font v2.1` and `v2.2.2`)
* **C)** Text spacing does not care, symbols proportional (advance width equals visible size) (`Nerd Font v2.2.0`)

**A** and **B** are useful in terminal emulators or other 'strict text grid' usecases. **C** is good for proportional context like 'create a presentation' or 'MS word text file' or 'A book with symbols' or often GUI contexts.

In the past we had Issues that people expect B and got C; while in other times people expected C and got B. I see a roughly equal request for B and C, it is just a different audience. **Technically** the C people could obtain their goals in different ways, while B can not be achieved easily and consistently by other means (then providing it here).

Historically Nerd Fonts came from the terminal emulator (A/B) context, but meanwhile GUI use is not uncommon anymore. For this reason my ... target would be to provide all 3 variants here - in the future. And then educate users which font they really want. And even then this would have side effects that need careful planning and code changes and maybe a different distribution model.

Well. Interesting as it is, let me first answer this question

> Do the symbols not extend into the next cell because the cells are bigger?

The `Symbols Only` font is proportional. The 'cell' size is different for each glyph in that font, and the size/width matches the symbol's width. This is like a 'normal' (say _Times Roman_) font in a Libre-Writer text. The `M` is wide and the `i` is small, and there is never overlap, the cursor advances exactly behind the letter you just typed in.

The `Symbols Only` font is created with the `font-patcher` option `--variable-width-glyphs`, that is used nowhere else (in the prepatched fonts). It is needed there, because there are no 'preexisting letters' or something that we can use to determine the cell width. We would need to come up with some cell width. That would be possible, but as that font is _specifically_ there to fulfill different needs including GUI usage, it has the advance width of each individual symbol set to that symbol's width - i.e. it is not monospaced at all.

If we want to provide the **C** fonts, or if someone wants to self-patch them, it is easy by just adding that `--variable-width-glyphs` option to the call.

See also
* https://github.com/ryanoasis/nerd-fonts/issues/898#issuecomment-1230144415
* https://github.com/ryanoasis/nerd-fonts/issues/731#issuecomment-1003071050 (another idea on font naming A/B/C)
* https://github.com/ryanoasis/nerd-fonts/issues/746#issuecomment-1003694798
* https://github.com/ryanoasis/nerd-fonts/issues/746#issuecomment-1003734095 (same issue, other comment)

These are more comment for ME, so that I do not forget
* Need meaningful and different family name suffix (to avoid chaos in font management)
* Would this make `--makegroups` even more relevant?
* Think about different (more directed) packaging: #919 #716
* Drop `Windows Compatible` fonts (they needlessly complicate everything, and take up space) #891 If we drop them and add C we have 3 fonts vs 4 fonts before :-}

**Comment by Finii** [comment]
> What I don't quite understand is why Symbols Nerd Font (non-mono) doesn't have the same issue.

When you write this here, I wonder how `Symbols Nerd Font Mono` is generated. I never thought much about it. Just have an (almost) empty font that is normally (*) patched, in all 4 flavors.

Connect #658
