### ISSUE TITLE
Question: Where are the licenses for each font?

### ISSUE THREAD

**Issue by FredHappyface** [ryanoasis/nerd-fonts#463]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

I am unable to find the license.txt/ license.md for each patched font, however, these appear to be included in a previous release

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ Any
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ N/A
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Windows 10

**Comment by FredHappyface** [comment]
My bad, turns out they are under the unpatched font directory. Would it be possible for you to automate dumping these in the patched fonts directory?

**Comment by ryanoasis** [comment]
> My bad, turns out they are under the unpatched font directory

No worries, yes!

> Would it be possible for you to automate dumping these in the patched fonts directory?

Yes we could do that. Curious if you were just curious or you see some potential licensing issue?
It would probably be a good idea to error on the side of copying rather than not copying them.. they could/should probably also propagate to the downloadable archive zip file as well...

**Comment by polyzen** [comment]
Generally licenses are required to be distributed along with what they're licensing.

**Comment by ryanoasis** [comment]
Thanks for looking out. Yeah there is a potentially major issue here.. I guess I know what I'll be working on next

**Comment by ryanoasis** [comment]
This will be fixed in the archives from now on in any future releases. Also the licenses should now be present in the patched directories as siblings to the actual font files, for example: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/BigBlueTerminal/complete

**Comment by polyzen** [comment]
Looks like for each font found to have a license, a copy of every type of license found was added to their patched fonts dir, and not just their own license.

Also found these to be missing with `rg -l copyright src/unpatched-fonts`:
`OFL.txt, OpenDyslexic/README.txt, Terminus/terminus-ttf-4.40.1/COPYING`

**Comment by ryanoasis** [comment]
@polyzen thanks for checking my work!

hmm yeah it definitely wasn't perfect, I found that [OpenDyslexic](https://github.com/antijingoist/open-dyslexic) doesn't have a separate license file, so I'll make one from it's readme.

> Also found OFL.txt and Terminus/terminus-ttf-4.40.1/COPYING to be missing with rg -l copyright src/unpatched-fonts

Let me tweak the script so that gets copied as well...

--

Okay I _think_ I've got them all now.. :crossed_fingers:

**Comment by polyzen** [comment]
> @polyzen thanks for checking my work!

Was rebasing my PR over master and then sorta absentmindedly went looking at the log. :p Noticed there weren't any `COPYING` license files being copied over, which are somewhat common. Was surprised to only find the one, then figured I'd do a search for "copyright".

> hmm yeah it definitely wasn't perfect, I found that OpenDyslexic doesn't have a separate license file, so I'll make one from it's readme.

I had noticed `patched-fonts/OpenDyslexic/` already had the readme files with the license in it -- think that's sufficient.

**Comment by ryanoasis** [comment]
> I had noticed patched-fonts/OpenDyslexic/ already had the readme files with the license in it -- think that's sufficient.

Yeah I agree but I think that'll be hard to automate so I pulled out the license part of the readme and put it in a separate license file, so that we don't have to think about it too much or have to copy all readme files.

> Noticed there weren't any COPYING license files being copied over

Hmm right, should those be? Can you point to an example? The ones that I've seen also had a separate license file.

**Comment by polyzen** [comment]
`unpatched-fonts/Terminus/terminus-ttf-4.40.1/COPYING` is the one I had found. There's a `LICENSE.txt` in there as well, but they slightly differ:
```
1c1
< Copyright (c) 2010 Dimitar Toshkov Zhekov,
---
> Copyright (c) 2012 Dimitar Toshkov Zhekov,
3,5c3
< 
< Copyright (c) 2011 Tilman Blumenbach,
< with Reserved Font Name "Terminus (TTF)".
---
> Copyright (c) 2013, Kim Silkebækken, Nikolay Pavlov and Carl X. Su.
```
