### ISSUE TITLE
Patching Cascadia Code changes font height in Windows Terminal

### ISSUE THREAD

**Issue by BladeMF** [ryanoasis/nerd-fonts#519]
#### 🎯 Subject of the issue

When patching Cascadia Code 2008.25, whether the static ttf version or the static otf version, the font height changes significantly in Windows Terminal (both Ubuntu and Console). For TTF version the size change is visible in font settings in Notepad also. This was not true for the 2005 version of the font. The TTF version appears visibly larger than the OTF version which in turn is larger than the orignal font.

I appologise in advance if this is not a problem caused by Nerd Font's font patcher, I will take this up with the Microsoft guys if needed.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
[Cascadia Code 2008.25](https://github.com/microsoft/cascadia-code/releases/tag/v2008.25)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
Windows Terminal Version: 1.3.2382.0
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Windows 2004 (OS Build 19041.450)

#### ★ Optional

_Please view the full size screenshots, otherwise the difference is not so obvious._

## Original font
![Annotation 2020-08-27 100846](https://user-images.githubusercontent.com/12109622/91408916-52f2ef80-e84d-11ea-9c08-3bfb9abc1dac.png)

## v2005 TTF
![2005 TTF](https://user-images.githubusercontent.com/12109622/91409334-f217e700-e84d-11ea-8c0a-149fb3ee6526.png)

## v2008 OTF
![2008 OTF](https://user-images.githubusercontent.com/12109622/91409376-fe9c3f80-e84d-11ea-83e7-e1cb8d5e14fd.png)

## 2008 TTF
![2008 TTF](https://user-images.githubusercontent.com/12109622/91409393-052ab700-e84e-11ea-8708-5bc545909438.png)

**Comment by BladeMF** [comment]
Also, now I've noticed, the dot in the letter "i" in the OTF version is visiby closer to the stem.

**Comment by Ririshi** [comment]
Cascadia Code has since attempted to fix the issue by supplying additional font height attributes in ttfautohint (which I am not familiar with, so I can sadly not be of assistance on that front), but it did not seem to help. My comment on the issue in their repo highlights very well what the issue is: https://github.com/microsoft/cascadia-code/issues/371#issuecomment-782911325. I'm hoping we can find a fix for it, as I'd love to use oh-my-posh and powerlevel10k with Cascadia Code!

**Comment by trallnag** [comment]
Hey @Ririshi, I was just attempting to patch Cascadia, but I guess there's no point in it as this issue still persists. Can you recommend a nerd font does not have this issue?

**Comment by trallnag** [comment]
Here is another screenshot of the issue with the newest version of Cascadia Code:

Without patch:

![image](https://user-images.githubusercontent.com/24834206/135676789-3a0faf2d-4085-49ac-bf94-428b2b6e777c.png)

After patching

![image](https://user-images.githubusercontent.com/24834206/135676738-330b64e9-f3a5-4cdd-986f-ff1b62750b1d.png)

**Comment by Finii** [comment]
The problem are the hints in the static fonts we use. They are already 'bad' in the Cascadia Code release files. This has nothing to do specifically with Nerd Fonts.

Compare yourself the Cascadia Code variable font (that obviously everyone compared to) to the parallel installed original Cascadia Code PL static fonts.

That it once worked and now doesnt is because the hints were manually created in the beginning, but later the static fonts became 2nd class citizens and were only autohinted. We reuse the existing not-so-good hints.

For interested see https://github.com/microsoft/cascadia-code/issues number 371 `Improve ttfautohint hinting`
(I don't want to create a backlink, so you have to search the issue yourselves.)
