### ISSUE TITLE
Issues in the name of Fira Code font

### ISSUE THREAD

**Issue by felipecrs** [ryanoasis/nerd-fonts#532]
The Fira Code font available in this repository has two issues in its name:

1. The official Fira Code font is called `Fira Code` (with spaces), while the one here is called `FiraCode`.
2. The font name of the Windows version is `FiraCode NF` while the font name of the other version is `FiraCode Nerd Font`. They were supposed to be equal, right?

![image](https://user-images.githubusercontent.com/29582865/95503947-ef3a0700-0960-11eb-93c5-dbf493297983.png)

**Comment by dsbert** [comment]
I ran into this issue tonight after setting up a new environment. I pulled in old configuration files which used `Fira Code` and didn't understand why my fonts were not working. I guess I had the original version of FiraCode installed in my old environment.

**Comment by MikeVensel** [comment]
This is very annoying when using VS Code on both Windows and Mac when using Fira Code.

**Comment by pho3nixf1re** [comment]
I will second this. Is there a way to make the Windows and MacOS built names the same? Or perhaps create an alias for the font in at least one of those platforms?

**Comment by Finii** [comment]
About the removed blank (`Fira Code` -> `FiraCode`):

This is deliberate. We 'fight' for every character in the name, because the name fields are limited to ridiculously short lengths. And it makes it a bit more obvious that this is a changed font.

If you set everything up for `Fira Code` also `Fira Code Nerd Font` will be a different font and not be accepted. So it does not make any difference if it is `FiraCode Nerd Font` or not.

---

Then we have `FiraCode Nerd Font` and `FiraCode NF`.

The first is the 'general' version while the later is the 'Windows Compatible' version.

They can not be somehow 'unified' or 'linked to each other', because the only difference between a 'Windows compatible' and a 'normal' font ARE the names. Names for Windows Compat needs to be even shorter, thus `Nerd Font` becomes `NF` (and also reason to drop the blank from `Fira Code` `FiraCode`).

> I will second this. Is there a way to make the Windows and MacOS built names the same?

I really really want to drop 'Windows Compat', as that sounds like Windows needs something special. Which is not the case.
Probably both will be unified somehow, but that needs some more research. See also
* #891 
* https://github.com/ryanoasis/nerd-fonts/discussions/1074#discussioncomment-4970164

**Comment by Finii** [comment]
Ah, btw, on 'current' Windows system there is no reason to use the `Windows Compatible` fonts. Just use the normal fonts.

The `Windows Compatible` fonts (the label is misleading) are for example needed for `MS Word 2011 on Mac` (!!) or `IE 8` (or something, I did not look up the actual revisions).
