### ISSUE TITLE
How do I install/use fontforge on Windows?

### ISSUE THREAD

**Issue by ndavidpsi** [ryanoasis/nerd-fonts#546]
Where do I download the script? The instructions for Windows are missing.

**Comment by ChiefMikeK** [comment]
What script are you looking for?
https://fontforge.org/en-US/downloads/windows-dl/
remember that you must install the `.exe` as admin under windows

**Comment by Astrophizz** [comment]
The Windows FontForge installer does not add its bin folder to `PATH` like it is for other operating systems. I'm not sure that FontForge works on Windows outside of the `fontforge-console.bat` console due to its use of a bundled version of Python. So far I haven't even been able to successfully run `font-patcher` from within `fontforge-console` either.

https://github.com/fontforge/fontforge/issues/2166
https://github.com/fontforge/fontforge/issues/3221

**Comment by ryanoasis** [comment]
closing as this is beyond project scope I feel. thanks
