### ISSUE TITLE
Font-patcher config: disable overwriting of certain glyphs --careful doesn't work for some glyphs

### ISSUE THREAD

**Issue by poetaman** [ryanoasis/nerd-fonts#576]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

The `--careful` option for [font-patcher](https://github.com/ryanoasis/nerd-fonts#font-patcher) doesn't seem to work all glyphs. It is replacing the "box drawings light vertical glyph" (unicode: 0x2502) `│` glyph (among other box drawing glyphs) that is already available in the font with a shorter glyph from one of the fonts in the [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) source files.

There are multiple workarounds possible: scale the line drawing glyphs to the height of glyphs in original font or remove the top/bottom/left/right font side-bearings from box drawing glyphs before/after patching (this will be ideal I guess), provide a config file example on how one can skip overwriting some glyphs, move the original glyphs to another location in the font file or some magic with stylistic sets (though I don't know how terminals could handle latter).

#### 🔧 Your Setup

- _Operator Mono (commercial)_
- _Apple Terminal_
- _macOS 11.2 ARM64_

#### ★ Optional

Screenshot comparing the heights of original (left), and new glyph (right):

<img width="173" alt="Screen Shot 2021-02-05 at 3 16 36 PM" src="https://user-images.githubusercontent.com/71736629/107100036-0cc09580-67c8-11eb-92ac-34edea92608d.png">

After running font patcher:
<img width="297" alt="Screen Shot 2021-02-05 at 3 40 01 PM" src="https://user-images.githubusercontent.com/71736629/107100176-7771d100-67c8-11eb-951b-f0ab26782dc1.png">

Before running font patcher:
<img width="297" alt="Screen Shot 2021-02-05 at 3 38 48 PM" src="https://user-images.githubusercontent.com/71736629/107100208-86588380-67c8-11eb-803f-30963d377e54.png">

**Addendum**
The same issue does not show up on [iTerm 2](https://iterm2.com) or [Alacritty](https://github.com/alacritty/alacritty) terminal emulators. What is confusing is the fact that before patching Operator font, it does not have this issue on Apple's inbuilt Terminal.app... I checked the linespacing setting in Terminal.app, and it is its usual 1.0 (100%) value. This is how patched font looks like on [Alacritty](https://github.com/alacritty/alacritty)

<img width="297" alt="Screen Shot 2021-02-06 at 12 49 49 AM" src="https://user-images.githubusercontent.com/71736629/107113912-de1ddb80-6816-11eb-9d9d-073ae034ed3c.png">

**Comment by edwintorok** [comment]
Alacritty by default uses a built-in font for box drawing (the advantage is that the built-in one is always self-consistent) https://github.com/alacritty/alacritty/blob/ad3ebba53233fdc61584b341be970a1828d09013/alacritty.yml#L181-L186, try turning that setting off to have it load the glyphs from your font instead.

**Comment by Finii** [comment]
Without really diving into this, I am sure `--careful` **does** work 100% of the time.

Check the output for something like `Found existing Glyph at XXX. Skipping...` with XXX = `0x2502` or something.

What you experience is most likely a change in general font height i.e. line height (without overwritten glyphs). You can use `showttf` or `ttfdump` to see the abstract font internals. The most likely reason for the increased height are the powerline synbols added by `font-patcher`. Because some terminal applications have problems with horizontal gaps between consecutive powerline lines the powerline glyphs are slightly (2% or so) taller than the 'normal' font height, making consecutive lines overlap. Well, other terminal applications handle that differently, and allow for zero overlap. Then of course all other glyphs are 'not tall enough' anymore.

If you are in experimentation mode you could edit `font-patcher` and set all `'overlap' : 0.0x` parameters to `0.0` and see if that fixes it.

**Comment by Finii** [comment]
Just checked, there are no

> It is replacing [unicode: 0x2502] that is already available in the font with a shorter glyph from one of the fonts in the nerd-fonts source files.

This is a screenshot of all the ranges that are patched in, you see some are at `23xx` and `26xx` but nothing at `25xx`.

![image](https://user-images.githubusercontent.com/16012374/169683109-40f0f539-c8a1-47bc-82a8-257690731a33.png)

The output in the previous comment will then of course not be there, as there is no glyph at `2502` that we even try to replace.
