### ISSUE TITLE
JetBrains mono font doesn't provide otf varient despite readme recommendations 

### ISSUE THREAD

**Issue by WilliamBehrens** [ryanoasis/nerd-fonts#685]
#### 🗹 Requirements
- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

The JetBrains mono font doesn't provide an otf varient, I mainly just noticed this after reading the [github readme](https://github.com/JetBrains/JetBrainsMono) for the font and they recomend using the otf version

#### 🔧 Your Setup

- _Which font are you using?_ Jetbrains Mono
- _Which terminal emulator are you using?_ Foot
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Void linux

**Comment by Finii** [comment]
Lets see what they say:

> If your IDE supports OpenType we recommend installing the default version of the font. If you prefer not using ligatures you can turn them off manually in the settings.

Well, the TrueType font files also come with Ligatures, so that is no real reason to use the OpenType variant. I do not know of any other OTF features one might want for IDEs (although for typesetting I personally like stylistic alternatives and swashes and whatnot, that OTF fonts usually have above TTF variants, but then almost NO program supports them properly sigh).

The ligatures are present in the ligatures variant ;->

![image](https://user-images.githubusercontent.com/16012374/143821555-363f5200-2425-4371-8bb7-cd2e2601c5b9.png)

Lets have a look on the OTF features that **are** present in the original font ('Font Features'):

![image](https://user-images.githubusercontent.com/16012374/143822400-c6a4afc4-22b7-4f76-8e65-ac1d02e55820.png)

This is meager. Maybe Slashed-Zero is interesting, but the other stuff? Do you need it, and which program are you using, that can utilize the features?

I would close this now. Please reopen if you need a OTF feature that is not present in the TTF variant.
