### ISSUE TITLE
https://github.com/caskroom/homebrew-fonts

### ISSUE THREAD

**Issue by kevinSuttle** [ryanoasis/nerd-fonts#72]
Would love to be able to install the fonts in this repo via 
https://github.com/caskroom/homebrew-fonts cc @phinze

**Comment by ryanoasis** [comment]
Sounds interesting, been busy so just no replying :sweat_smile:

**Comment by jrolfs** [comment]
I definitely have had my eye on that as well. They don't seem too particular over there as there are quite a few Powerline patched fonts in `master` already but I figured it would be worth waiting until [0.7.0](https://github.com/ryanoasis/nerd-fonts/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.7.0) until we start making PRs to Homebrew Fonts.

**Comment by kevinSuttle** [comment]
👍🏼

**Comment by ryanoasis** [comment]
I have [created a shell script to create the casks](https://github.com/ryanoasis/nerd-fonts/commit/d2ee06bdfdcf4822b8ba9f93e48bb744fad54ccc) :smile: in [0.9.0](https://github.com/ryanoasis/nerd-fonts/milestone/14) but not sure how to test them without being on macOS :cry: 

Also not sure if these are even supposed to work without the source being an archive file.. anyone know? I will try to ask for some help on the homebrew fonts :smile:

**Comment by kevinSuttle** [comment]
Ping @vitorgalvao

**Comment by vitorgalvao** [comment]
> They don't seem too particular over there

We’re not.

> but not sure how to test them without being on macOS

Travis can do it. Submit one of them (the most typical) and ping me. I’ll look into into it a see any changes. If needed, you may then revise your script (rinse and repeat).

> Also not sure if these are even supposed to work without the source being an archive file

You mean you have links to the naked `ttf` or `otf`? Not a problem, it works the same.

**Comment by vitorgalvao** [comment]
Almost forgot, the thing we’re particular about is the naming. See the [docs](https://github.com/caskroom/homebrew-fonts/blob/master/CONTRIBUTING.md#font-cask-fields).

**Comment by jrolfs** [comment]
I'm happy to help test this on a Mac although it sounds like getting it working on CI would be preferable.

@vitorgalvao does it make sense for all of the names to include a `nerd-font` suffix or the like since there will most likely be conflicts for all them seeing as they are patched versions of existing fonts? The other solution would be to use the pseudonym for the patched font that is used in this repo (eg: `source-code-pro` ➡ `sauce-code-pro`) which once patched would theoretically be the canonical name according to the **Caskroom-fonts** `README`:

![example](http://d.pr/i/eJh9+)

- `font-sauce-code-pro-nerd-font` (original with suffix)
- `font-source-code-pro-nerd-font` (post-patch name with suffix)
- `font-sauce-code-pro` (post-patch name without suffix)

Also, there are multiple patch variants – I'm assuming you probably would prefer we don't contribute too much noise but only submitting the "complete" patch variant? Otherwise it would have to be something like:

- `font-[canonical name]-complete`
- `font-[canonical name]-minimal`

... maybe ...
- `font-[canonical name]-plus-pomicons`
- `font-[canonical name]-plus-octicons`
- `font-[canonical name]-plus-font-awesome-plus-octicons`

... etc.

/cc @ryanoasis

**Comment by vitorgalvao** [comment]
When casks have conflicting tokens, we add a prefix, not a suffix. But those names in your screenshot seem acceptable. If the font itself as `Nerd Font` in the name, adding that as a suffix to the cask makes sense.

And yes, if you could submit something as complete as possible (i.e. with the few number of casks as possible), that would be preferable.

**Comment by ryanoasis** [comment]
@kevinSuttle Thanks for pinging the appropriate people in :blush: 

--

> You mean you have links to the naked ttf or otf? Not a problem, it works the same.

Yes. I think right now the download URL points to the main folder but then each individual `font` stanza points to each a subdirectory for each font family for that font.

--

@jrolfs For the patch variants except for "complete" I have removed the generating of those going forward. So yeah we will only create casks for the "complete" variations as well :smile: 

--

@vitorgalvao Thanks for replying and providing some more info. I actually did read the contributing docs and it really helped me build some test casks :smile: . That being said I could probably go through and read it again a bit more thoroughly :stuck_out_tongue: . 

1. Would it be acceptable to submit you something "complete" for just one font for now (e.g., Hack)?
2. By 'submit' I assume you mean a WIP PR or some other means until it is ironed out?

--

@jrolfs @vitorgalvao I am using `fc-query` in the script currently to help build the name to use.

--

@jrolfs If you have time and want you can actually run [the script](https://github.com/ryanoasis/nerd-fonts/commit/d2ee06bdfdcf4822b8ba9f93e48bb744fad54ccc) to see how I am currently generating the cask for 'Hack'. I am not able to run it currently and have not pushed the example it generates

Thanks all.

**Comment by vitorgalvao** [comment]
> 1. Would it be acceptable to submit you something "complete" for just one font for now (e.g., Hack)?
> 2. By 'submit' I assume you mean a WIP PR or some other means until it is ironed out?

Yes on both counts.

**Comment by ryanoasis** [comment]
If some one wants to test this... Hack (Knack) should now be available :smile: but seems like it should work just fine (ref: https://github.com/caskroom/homebrew-fonts/pull/913)

---

Will submit one more individual font PR before submitting the rest. The rest is dependent on #32 (we have a [script to generate the archives](https://github.com/ryanoasis/nerd-fonts/blob/0.9.0/bin/scripts/archive-fonts.sh) but not done with the upload/release script -- surely don't want to upload them manually)

**Comment by jrolfs** [comment]
Working for me, though do we actually need `Mono`?

![Cask Install](http://d.pr/i/F0gW+)

**Comment by ryanoasis** [comment]
@jrolfs Thanks for testing it out

> Working for me, though do we actually need Mono?

Good question. Well I do know there is a fair number that prefer or have to use mono in their terminal. I think maybe we could create a separate one for mono. something like `font-hack-nerd-font` and `font-hack-mono-nerd-font`. 

--

Does anyone else have a strong preference regarding including variable width and mono together in the same cask?

My gut says to keep it as is but perhaps take it up in the next release because I feel this release is fairly large and long going already :stuck_out_tongue:

**Comment by ryanoasis** [comment]
@vitorgalvao Do you see any preference regarding this: 
> I think maybe we could create a separate one for mono. something like font-hack-nerd-font and font-hack-mono-nerd-font.

**Comment by vitorgalvao** [comment]
@ryanoasis No preference.

**Comment by ryanoasis** [comment]
Thanks

**Comment by gwerbin** [comment]
Would it make more sense to maintain a separate Tap for these? It might be easier than dumping them all in the core fonts repo.
