### ISSUE TITLE
FiraCode NF Retina not being recognized as a distinct font

### ISSUE THREAD

**Issue by mtsitzer** [ryanoasis/nerd-fonts#744]
I'm seeing an issue with FiraCode NF Retina not being recognized as a distinct font.

After installing FiraCode NF (all faces), I see this:

This suggests its part of the FiraCode NF Family
<img width="549" alt="image" src="https://user-images.githubusercontent.com/28517224/147736019-9ba59525-ec9d-4746-a7db-193062a9304d.png">

But when I go into the fonts folder, I don't see Retina as a distinct font, nor do I see it as part of the family
<img width="434" alt="image" src="https://user-images.githubusercontent.com/28517224/147735890-7fe310f3-a749-490d-be3e-b8ffdc331dd2.png">

Compare this with the standard (non Nerd Font) Fira Code:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/28517224/147735955-a2698d1f-e61f-4f00-8f68-7cc156e9ea53.png">

Also, why does the standard Fira Code install give me specific font face options but FiraCode NF is singluar?
In MS Word:
<img width="225" alt="image" src="https://user-images.githubusercontent.com/28517224/147736637-24f98a28-f654-46c0-9f16-24a82b9757e7.png">

_Originally posted by @mtsitzer in https://github.com/ryanoasis/nerd-fonts/issues/440#issuecomment-1002929459_

**Comment by Finii** [comment]
**Word** would be fixed with #717, at the moment the font grouping is wrong and all weights get the same name :unamused: 

The _Retina_ is not a separate font in the Fira we have in the `src/unpatched-fonts/` I believe. Where exactly did you download your Fira-Originals?

If Retina has to be a different face, this could be fixed, but the original Fira I have does not suggest that.

**Comment by mtsitzer** [comment]
I got the originals from https://github.com/tonsky/FiraCode
![image](https://user-images.githubusercontent.com/28517224/147738211-cb8d2b35-ace8-439c-9698-246750aecee7.png)

**Comment by Finii** [comment]
Hmm, 6.2 has this naming scheme:
![image](https://user-images.githubusercontent.com/16012374/147738879-1c9e2b7b-5723-4c6b-92b6-45576bd89a6b.png)

_Retina_ is no other typographic Family here. It's also not called 'Retina Medium'; not sure why it turns up as such in your font folder (never looked into the font folder).

Apart from grouping, you real issue is that you can not access 'Retina' in VS, right?

**Comment by mtsitzer** [comment]
Correct --- and in other applications as well (such as Word)

Interestingly, I'm checking on another PC (with Fira Code 5.2 Installed), and I see the same breakdown 
![image](https://user-images.githubusercontent.com/28517224/147739441-cc27003f-4de4-4be2-82e3-3af9374d139b.png)

![image](https://user-images.githubusercontent.com/28517224/147739495-5bd847aa-4783-478b-b2e6-d95732066d4d.png)

**Comment by Finii** [comment]
They (Fira) say Retina is a weight ;-)

![image](https://user-images.githubusercontent.com/16012374/147739553-85753325-d762-4384-9b3a-dddcb566374a.png)

I personally have no clue what Retina means.

**Comment by mtsitzer** [comment]
Here's some description for Retina:
https://github.com/tonsky/FiraCode/issues/872#issuecomment-544480764

**Comment by Finii** [comment]
> Correct --- and in other applications as well (such as Word, Windows Terminal, etc.)

Unfortunately the fix is ... not hard but involves changing a lot fonts. In principle the PR (#717) is ready but I wanted to add more documentation and explanation stuff.

If you can self patch, maybe use that branch (`git checkout feature/rewrite-setup_font_names`) and patch with `--parser` given to `font-patcher`. That will result in more accurate naming...

**Comment by Finii** [comment]
> Here's some description for Retina

Ah great! Thank you!

So Retina is the Apple-Fanboy name for Book :-D

**Comment by mtsitzer** [comment]
I'm good to wait for you to finalize 717. I just followed the rabbit hole a littler further than I'd intended, and figured I should make an issue out of it.

As for the "Retina" name --- yeah, I guess so (I don't use any apple products haha).

**Comment by Finii** [comment]
Self-Patch this with `--makegroups`.
This will be the repo wide default with `v3.0.0`.
