### ISSUE TITLE
Nerd Fonts Repo is too big, any plan for fixing it ?

### ISSUE THREAD

**Issue by GulajavaMinistudio** [ryanoasis/nerd-fonts#751]
Today I'm try to clone this repository. But i found that this repository are too big because of some fonts included inside src/unpatched-fonts . And also fonts on src/patched-fonts make it more large too. Any plan to fix this ? 

Maybe you can try to separate patched-fonts from repository, and just upload it in files on Release Page only. And also, you can try to .gitignore what inside /unpatched-fonts , and upload source fonts on different repo or cloud storage, or maybe just redirect to font source, so user or contributor can download it on different source from repository. And  i think if you can do that, this repository become more lightweigh.

**Comment by Finii** [comment]
There are plans to separate the patcher from the fonts, https://github.com/NerdFonts, but the migration will take some time and ideas.

Putting the patched fonts into release files instead of the repo itself, I guess Ryan is working on that at the moment, this will be all automatized with CI blah.

Gitignore ... inclusion of the sources is not by accident.

Splitting is especially complicated because one wants to keep the issues where they belong. At the moment in this repo the issues span over the patcher and sources etc, and are referenced in commit messages. If you reorganize all this it will break (increase a boundary for git blame etc) that you can not cross easily.

Well this is just my private thoughts on it.

**Comment by Finii** [comment]
BTW, did you do a shallow clone as suggested [here](https://github.com/ryanoasis/nerd-fonts#option-5-clone-the-repo)?

At least it's only half as big as a complete clone then.

**Comment by GulajavaMinistudio** [comment]
> BTW, did you do a shallow clone as suggested [here](https://github.com/ryanoasis/nerd-fonts#option-5-clone-the-repo)?
> 
> At least it's only half as big as a complete clone then.

Thanks, i try shallow clone and it successful. But still the repo too large for font patcher tools. Its size around 800 Mb, because of font files inside it.

**Comment by Finii** [comment]
I would include the source fonts as git submodule, so ppl can clone this repo and need an additional step to further fetch the fonts. But often people shed away from git submodules, at least at work - one can be happy if the colleagues know basic git, submodules is beyond them :-(

Anyhow, I believe your issue is fully valid. Just have seen Ryan is in full restructuring at the moment, lets wait a bit :-)

**Comment by Finii** [comment]
Completely off-topic ...

Your font, I think I do not understand how `Ubuntu` is in SS12 (and so on), I can not see anything:

![image](https://user-images.githubusercontent.com/16012374/148254527-e55c4886-b3a8-41dd-8502-1dde041879cd.png)

The used glyphs are the same (for `TEST`, regardless of SS12 on or off. I thought somehow you embedded `Ubuntu` and one can switch fonts without switching fonts ;-)

**Comment by ryanoasis** [comment]
@GulajavaMinistudio If you just want the patcher itself, feel free to try out the RC release: https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/FontPatcher.zip and let me know your thoughts. Thanks
