### ISSUE TITLE
Update codepoint ranges

### ISSUE THREAD

**Issue by jmederosalvarado** [ryanoasis/nerd-fonts#762]
#### 🎯 Subject of the issue

After the addition of various symbols like `codicons`, codepoint ranges in the wiki are outdated. Could we please update it? It would be great to update the website as well.

I'd be happy to submit a PR if someone pointed out how to extract codepoint ranges from the patcher script.

**Comment by Finii** [comment]
I'm not sure if Ryan's thumps-up means it will be fixed or it would be great to create a PR.

Anyhow, the ranges are given on lines 562+

```python
"Seti-UI + Custom",         'Exact': False,                               'SymStart': 0xE4FA, 'SymEnd': 0xE531, 'SrcStart': 0xE5FA, 'SrcEnd': 0xE631
"Devicons",                 'Exact': False,                               'SymStart': 0xE600, 'SymEnd': 0xE6C5, 'SrcStart': 0xE700, 'SrcEnd': 0xE7C5
"Powerline Symbols",        'Exact': True,                                'SymStart': 0xE0A0, 'SymEnd': 0xE0A2, 'SrcStart': None,   'SrcEnd': None  
"Powerline Symbols",        'Exact': True,                                'SymStart': 0xE0B0, 'SymEnd': 0xE0B3, 'SrcStart': None,   'SrcEnd': None
"Powerline Extra Symbols",  'Exact': True,                                'SymStart': 0xE0A3, 'SymEnd': 0xE0A3, 'SrcStart': None,   'SrcEnd': None
"Powerline Extra Symbols",  'Exact': True,                                'SymStart': 0xE0B4, 'SymEnd': 0xE0C8, 'SrcStart': None,   'SrcEnd': None
"Powerline Extra Symbols",  'Exact': True,                                'SymStart': 0xE0CA, 'SymEnd': 0xE0CA, 'SrcStart': None,   'SrcEnd': None
"Powerline Extra Symbols",  'Exact': True,                                'SymStart': 0xE0CC, 'SymEnd': 0xE0D4, 'SrcStart': None,   'SrcEnd': None
"Pomicons",                 'Exact': True,                                'SymStart': 0xE000, 'SymEnd': 0xE00A, 'SrcStart': None,   'SrcEnd': None
"Font Awesome",             'Exact': True,                                'SymStart': 0xF000, 'SymEnd': 0xF2E0, 'SrcStart': None,   'SrcEnd': None  
"Font Awesome Extension",   'Exact': False,                               'SymStart': 0xE000, 'SymEnd': 0xE0A9, 'SrcStart': 0xE200, 'SrcEnd': 0xE2A9
"Power Symbols",            'Exact': True,                                'SymStart': 0x23FB, 'SymEnd': 0x23FE, 'SrcStart': None,   'SrcEnd': None  
"Power Symbols",            'Exact': True,                                'SymStart': 0x2B58, 'SymEnd': 0x2B58, 'SrcStart': None,   'SrcEnd': None
"Material",                 'Exact': False,                               'SymStart': 0xF001, 'SymEnd': 0xF847, 'SrcStart': 0xF500, 'SrcEnd': 0xFD46
"Weather Icons",            'Exact': False,                               'SymStart': 0xF000, 'SymEnd': 0xF0EB, 'SrcStart': 0xE300, 'SrcEnd': 0xE3EB
"Font Logos (Font Linux)",  'Exact': self.fontlinuxExactEncodingPosition, 'SymStart': 0xF100, 'SymEnd': 0xF12D, 'SrcStart': 0xF300, 'SrcEnd': 0xF32D
"Octicons",                 'Exact': self.octiconsExactEncodingPosition,  'SymStart': 0xF000, 'SymEnd': 0xF105, 'SrcStart': 0xF400, 'SrcEnd': 0xF505
"Octicons",                 'Exact': self.octiconsExactEncodingPosition,  'SymStart': 0x2665, 'SymEnd': 0x2665, 'SrcStart': None,   'SrcEnd': None  
"Octicons",                 'Exact': self.octiconsExactEncodingPosition,  'SymStart': 0X26A1, 'SymEnd': 0X26A1, 'SrcStart': None,   'SrcEnd': None
"Octicons",                 'Exact': self.octiconsExactEncodingPosition,  'SymStart': 0xF27C, 'SymEnd': 0xF27C, 'SrcStart': 0xF4A9, 'SrcEnd': 0xF4A9
"Codicons",                 'Exact': True,                                'SymStart': 0xEA60, 'SymEnd': 0xEBEB, 'SrcStart': None,   'SrcEnd': None  
```

* `Src` is the to-be-patched font, `Sym` is the symbols font.
* The values are closed ranges (i.e. both values including)
* If no `Src` values are given the symbols are not shifted
* For Octicons and Font Logos it is more complicated

Sorted by range start in `--complete`:

 Name | Codepoints | Comment |                                                                                                                     
|---|---|---|    
| Power Symbols           | `23FB` - `23FE` |
| Octicons                | `2665`          |
| Octicons                | `26A1`          |
| Power Symbols           | `2B58`          |
| Pomicons                | `E000` - `E00A` |
| Powerline Symbols       | `E0A0` - `E0A2` |
| Powerline Extra Symbols | `E0A3`          |
| Powerline Symbols       | `E0B0` - `E0B3` |
| Powerline Extra Symbols | `E0B4` - `E0C8` |
| Powerline Extra Symbols | `E0CA`          |
| Powerline Extra Symbols | `E0CC` - `E0D4` |
| Font Awesome Extension  | `E200` - `E2A9` |
| Weather Icons           | `E300` - `E3EB` |
| Seti-UI + Custom        | `E5FA` - `E631` |
| Devicons                | `E700` - `E7C5` |
| Codicons                | `EA60` - `EBEB` |
| Font Awesome            | `F000` - `F2E0` |
| Font Logos              | `F300` - `F32D` | _or `F100` - `F12D` if neither_ Font Awesome _nor_ Octicons _present_ |                                 
| Octicons                | `F400` - `F505` | _or `F000` - `F105` if_ Font Awesome _not present_ |                                 
| Octicons                | `F4A9`          | _or `F27C` - `F27C` if_ Font Awesome _not present_ |                                 
| Material                | `F500` - `FD46` |

The actual ranges could be smaller (did not check), because empty glyph slots are ignored, i.e. filled glyphs are 'compressed' in the patched font.

And then you might have noticed, that Octicons end at 0xF505 but Material starts at 0xF500 :roll_eyes:
One would need to check what is really patched in in the overlapping region.

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/149288986-bc75695e-757a-4749-8990-9f809d93b00b.png)
_https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points_

Hmm, from my table above the `F27C` should be `F4A9`?

**Comment by jmederosalvarado** [comment]
I just made the necessary changes to the codepoint ranges wiki page based on [this code in the font patcher](https://github.com/ryanoasis/nerd-fonts/blob/877887cac2d6ccc7354a8d95e8c39fff10bf120b/font-patcher#L561-L584).

I've never contributed to a project wiki before, so I don't really know the workflow here, I've been reading and it seems to be no way for me to open a pr for this. So [this is a link to my branch containing the changes](https://github.com/jmederosalvarado/nerd-fonts-wiki/tree/codepoint-ranges-update). In case a simple patch is easier for you I'll also attach one.

**Comment by Finii** [comment]
\*laugh\* Yes. I also wondered how the workflow is, and ... probably there is none.

I will review your branch (excellent idea!) and come back later.

**Comment by Finii** [comment]
That worked very well! (The workflow).
Followed this here [https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github](https://stackoverflow.com/a/11481887)

Pushed your commit (and a small change of mine): https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points/_history

Thank you!
