### ISSUE TITLE
include font awesome 6

### ISSUE THREAD

**Issue by Nachtpfoetchen** [ryanoasis/nerd-fonts#789]
Font awesome 6 was released - would be cool to update font awesome in nerdfonts.
https://github.com/FortAwesome/Font-Awesome/releases/tag/6.0.0

**Comment by Finii** [comment]
Related: #727 (kind of duplicate)

**Comment by Finii** [comment]
Related: #793

**Comment by OldWorldOrdr** [comment]
I want this too.  I need a good cpu icon.

**Comment by 0ptim** [comment]
I, too, am interested in fa6 support.
I'm not exactly sure if it's already possible as described [here](https://github.com/ryanoasis/nerd-fonts/discussions/727#discussioncomment-2223877).
@phdpe Can you confirm?

**Comment by Finii** [comment]
At the moment `font-patcher` takes all Font Awesome 4.007 glyphs in the range `F000` - `F2E0` and patches them into the target font at the same codepoints. It has only very few 'gaps'.

To have the 'same' glyph set you need to
* patch `Font Awesome 6 Brands-Regular-400.otf` an then
* over-patch with `Font Awesome 6 Free-Solid-900.otf`

With these settings, both:
```
'Exact': True,
'SymStart': 0xF000, 'SymEnd': 0xF2E0,
'SrcStart': None, 'SrcEnd': None,
'ScaleGlyph': FONTA_SCALE_LIST, 'Attributes': SYM_ATTR_FONTA
```

@0ptim But that will not add all the additional symbols that FA now has. Would it be helpful to test this? Are you interested in any specific (renovated?) glyphs? Please give the codepoints.

**Comment by Finii** [comment]
FA6 has glyphs 'everywhere' but at least the 'core range' seems to be `F000` - `F8FF`. That overlaps with codepoints used by Nerd Fonts for other fonts, ... That is the reason I suggested to keep the 'old FA4 range'.

**Comment by Finii** [comment]
FA6 seems to ... ignore/not provide inverted icons?

![image](https://user-images.githubusercontent.com/16012374/158412761-711b9376-4d29-4fb2-8c6a-9275e448b57b.png)

And what happened with the talk-bubble circled blue?

**Comment by 0ptim** [comment]
@Finii Thanks for your quick response. Please forgive my inexperience, when in comes to fonts.

My goal is to have some font like `CaskaydiaCove-Regular` or the like and patch it with `Font Awesome 6 Brands-Regular-400` and `Font Awesome 6 Pro-Solid-900.otf`.

> That is the reason I suggested to keep the 'old FA4 range' in the comment above

What are the implications of this? Does this mean that if I copy and paste glyphs from the [FA-website](https://fontawesome.com/v6/search?s=brands%2Csolid), the glyphs won't display because they are not in the same range?

> Are you interested in any specific (renovated?) glyphs? Please give the codepoints.

Sorry, but I don't understand your question here.

> FA6 seems to ... ignore/not provide inverted icons?

I guess they just no longer provide the inverted versions because it can simply be achieved by setting the font color.

> And what happened with the talk-bubble circled blue?

Good spot! I don't understand what happened there either.

**Comment by Finii** [comment]
Closed because moved to https://github.com/ryanoasis/nerd-fonts/discussions/1095

**Comment by Finii** [comment]
Continued in
* #1550

**Comment by Finii** [comment]
Done.
