### ISSUE TITLE
Vue Icon cut off

### ISSUE THREAD

**Issue by pwang2** [ryanoasis/nerd-fonts#795]
#### 🗹 Requirements

![image](https://user-images.githubusercontent.com/1592014/155232229-68c36131-874f-4dc2-912d-2ba9358663c3.png)

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Vue icon is cutoff but others looked okay. 

![image](https://user-images.githubusercontent.com/1592014/155228747-e609611b-1478-4615-88cb-933904ab7145.png)
Might be a Neovim thing as it looks okay if I output via Unicode. 
![image](https://user-images.githubusercontent.com/1592014/155230257-32fc8856-1910-4be4-9715-65d7708c0ce6.png)
If I use Unicode to input in neovim and append a space , still not okay. 
![image](https://user-images.githubusercontent.com/1592014/155230487-697899b3-b99f-404b-bda7-6177d90943db.png)

a few more icons have the same issue
![image](https://user-images.githubusercontent.com/1592014/155231596-ea4a057d-3310-400d-9576-d0206689b14c.png)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_
      __JetBrainsMono NF (JetBrains Mono Light Nerd Font Complete Windows Compatible.otf)__
   - _Where did you get the file from (download link, self patched, source downloaded from link...)_
     I tried both the one in the patched folder in the repo and the one download from 
     __https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip__
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
    __Windows Terminal__
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
    __Microsoft Windows [Version 10.0.19042.1466]__

Expected behavior:
aligned. also quite appreciated if anyone could provide guidance for a self-patch solution.

**Comment by Finii** [comment]
Complete 'your setup' section missing.

**Comment by pwang2** [comment]
@Finii , Sorry about that, I have updated in the issue detail.

**Comment by Finii** [comment]
I believe Windows Terminal, is that not prescribing fixed widthes?

> I tried both the one in the patched folder in the repo and the one download from
https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip

I can not find the `Light` font in the release 2.1.0 download.

Tried from the repo and ended up with this:
https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/Ligatures/Light/complete/JetBrains%20Mono%20Light%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf

![image](https://user-images.githubusercontent.com/16012374/155274900-336cf76c-76aa-4fff-919f-e3b0a97ba3bd.png)


The font has the icons added 'big', i.e. more than one monospace-space wide (Note 832 vs 600 in image above). Windows Terminal scales them down for you, depending on glyph range.

From the 2.1.0 release here the `Regular` as example:

![image](https://user-images.githubusercontent.com/16012374/155276283-81194d89-ca27-4bf8-9ef6-39e766c9d244.png)

There both are 600 wide, but the symbol extrudes a bit to the right (into the next character). That is preserved by Windows Terminal.

Some explanations about the differences can be found in #731 and #764.
There is also an Issue where I examine the Windows Terminal behavior to some length (with source code snippets), but I can not find it :unamused: 


Your expected behavior, I guess, can be achieved by using _Font Flavior 1_, the `BlahBlah NF Mono` variant, i.e. [JetBrains Mono Light Nerd Font Complete Mono Windows Compatible.ttf](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/Ligatures/Light/complete/JetBrains%20Mono%20Light%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf) (note two times `Mono` in the name).

If you try things out,
* remove all 'old' fonts (i.e. from a different source) from that font family first (do not install over old fonts)
* install the least amount of family member (ideally only one), because there are still family grouping issues (PR is ready)

**Comment by Finii** [comment]
P.S. You run `neovim` within `Windows Terminal` or this GUI thing? If there is an issue related to a specific (sub-) application a description of the setup would be helpful.
Hmm, is there even a neovim-GUI-Windows build? Who knows ;-) I use `neovim` Appimage inside `tilix` under Gnome ;-D

**Comment by Finii** [comment]
> But still, it'd kinda bizarre as this only affects some of the icons. icons like NPM here is not affected.

I guess NPM is in the 'wide' area and therefore 2 slots wide. Here you can check if Windows Terminal thinks the glyph is narrow or wide (or ambiguous):
https://github.com/microsoft/terminal/blob/main/src/types/CodepointWidthDetector.cpp

**Comment by pwang2** [comment]
vue hex is fd42 which is Unspecified.     
>UnicodeRange{ 0xf900, 0xfaff, CodepointWidth::Wide },
>UnicodeRange{ 0xfe00, 0xfe0f, CodepointWidth::Ambiguous },

npm hex is e71e which is Ambiguous.
>UnicodeRange{ 0xe000, 0xf8ff, CodepointWidth::Ambiguous }

I guess the unspecified is causing this issue.  All icons in range fdxx have the same rendering issue which proves it. 

Thanks for the investigation and I really learned a lot.

**Comment by Finii** [comment]
> it is the guibg in highlight group in the colorscheme mask the right part

Ah, I remember someone wrote that "the 'aligning' is done only on color changes".

Here: https://github.com/ryanoasis/nerd-fonts/issues/746#issuecomment-1003429782
> Konsole apparently only realigns to the grid on color changes.

While `Konsole` != `Windows Terminal` of course... hmm.

Terminal emulators get more and more 'smart' :roll_eyes: Guess we soon need a Terminal Emulator Issues FAQ.
