### ISSUE TITLE
CaskaydiaCove with Light/ExtraLight font faces

### ISSUE THREAD

**Issue by xinxilas** [ryanoasis/nerd-fonts#802]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Make font faces Light and ExtraLight for CaskaydiaCove Nerd Font too:
Original:
![image](https://user-images.githubusercontent.com/38674705/156774396-66f11adb-c92b-473c-81e2-bd0a2f163955.png)
CaskaydiaCove:
![image](https://user-images.githubusercontent.com/38674705/156774737-8accd1c2-f1a7-45ce-833f-b80db8705e47.png)

**Additional context**
Uggly:
![image](https://user-images.githubusercontent.com/38674705/156774467-4c782e4b-1689-4807-a116-298a84e93381.png)

**Comment by Finii** [comment]
Well, `light` and `extralight` are in the set we patch:

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode/ExtraLight/complete

I assume you installed the `light` files as well? Because shown is only regular.

I'm not sure (i.e. I doubt) if they are in the v2.1.0 release, if you happen to use that. 

If you are using any Nerd Font release fonts please deinstall and use the direct repo files instead (see link above).


Otoh there is a bug in the family naming.
PR #723 sets out to fix them. Until that is pulled (and probably released) you can find the patched font sets... somewhere. Searching on mobile...

**Comment by Finii** [comment]
Probably here... https://github.com/Finii/nerd-fonts/tree/feature/cascadia-2111.01/patched-fonts/CascadiaCode, that is just the test for the PR.
Try it out and report ;-)

**Comment by xinxilas** [comment]
Thank you 

Used this one:
https://github.com/Finii/nerd-fonts/blob/feature/cascadia-2111.01/patched-fonts/CascadiaCode/ExtraLight/complete/Caskaydia%20Cove%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible%20ExtraLight.otf

Its better now:
![image](https://user-images.githubusercontent.com/38674705/156806038-9a81ed09-7e92-4516-9f14-af7afbe00596.png)

The font joined each other is due my vscode is zoomed out to get a smaller interface

**Comment by Finii** [comment]
That means this Issue is solved / will be solved with #723?
Then we could add this issue to be autoclosed by 723.
