### ISSUE TITLE
Caskaydia Cove does not contain arrow support.

### ISSUE THREAD

**Issue by bend-n** [ryanoasis/nerd-fonts#854]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

What happens:
Arrows are nonexistent.

Expected behavior:
![arrows](https://user-images.githubusercontent.com/70787919/176395073-fb8d5bc8-0a37-4600-8e68-1ee6cd7b686b.png)

Example symbols:
```
<-----< | ---->---> <<---<< | ---->>--->>--|| ||----<<
___|___ ## ### #### #####
//===:===/
```

#### 🔧 Your Setup
- file name: CaskaydiaCove Nerd Font
- got from: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip
konsole
ArchLinux x11 5.18.7

#### ★ Screenshots (Optional)
- [delugia-code](https://github.com/adam7/delugia-code): 
![delugia](https://user-images.githubusercontent.com/70787919/176396030-a0fafb1a-dc03-4698-a739-86955403a296.png)
- [cascadia-code](https://github.com/microsoft/cascadia-code): 
![cascadia](https://user-images.githubusercontent.com/70787919/176396375-2af38015-5d36-43d8-9a28-ad2b58e1809e.png)
- [caskaydia](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode) 
![image](https://user-images.githubusercontent.com/70787919/176396867-35e6b694-03cf-4dd0-a61d-7e5533189545.png)

**Comment by Finii** [comment]
Nerd Font does not patch in the arrows, it is only there if it is in the source font.

Fira Code's infinite arrows have been introduced into Cascadia Code with release 2102.03.

Delugia (:+1:) is always based on the latest Cascadia Code release (i.e. 2111.01).
That is automatized. It is possible because Delugia cares only about one font, while Nerd Fonts has a lot of different source fonts, each with its own peculiarities.

Cascaydia Cove v2.1.0 is based on Cascadia Code 1909.16
Cascaydia Cove v2.2.0 is based on Cascadia Code 2007.01
Cascaydia Cove PR #723 is based on Cascadia Code 2111.01 (download [here](https://github.com/Finii/nerd-fonts/tree/feature/cascadia-2111.01-patched/patched-fonts/CascadiaCode))

**Comment by Finii** [comment]
Hmm, this step with the roundish-powerline-things

![image](https://user-images.githubusercontent.com/16012374/176618126-4bd63b78-2fda-4d9d-94c3-77ad44e0dade.png)

has also a fix in the PR pipeline somwehere.

**Comment by bend-n** [comment]
If these fixes are all already made, when will the releases page be updated?

**Comment by Finii** [comment]
Hmm
Just downloaded both...:

![image](https://user-images.githubusercontent.com/16012374/176699232-eee22eec-694b-4e0b-a643-1d121c99413f.png)

My terminal does not support ligatures, so that I can not show on the command line.

Is it working for you in `writer` et al?
