### ISSUE TITLE
Broken svg on website for Iosevka nerd font

### ISSUE THREAD

**Issue by laalsaas** [ryanoasis/nerd-fonts#865]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
At https://www.nerdfonts.com/font-downloads the svg for the Iosevka font is broken. The i and j-dots are shifted.

Expected behavior:
The dots from the j and i should be on top of their respective letters (I assume that's not a font issue, just the svg is broken, but since the website is also "developed" here I figured I would open an issue here.)

Example symbols:

#### 🔧 Your Setup
*(irrelevant)*
- Iosevka font in the svg at 
- I've tested it in qutebrowser (chromium-based) and Firefox
- I'm on Linux, NixOS unstable

#### ★ Screenshots (Optional)
![image](https://user-images.githubusercontent.com/43275254/178788472-5d95f081-298f-447d-b4da-6e752bdaf087.png)

**Comment by Finii** [comment]
The actual font referenced seems ok, at least in the font viewer:

![image](https://user-images.githubusercontent.com/16012374/178813347-1490e290-49f4-4b70-995d-d382601b5e51.png)

Ah yes, Iosevka is broken, I remember. Will check the image generator..

![image](https://user-images.githubusercontent.com/16012374/178813923-dfaaab00-5e39-4ee7-9925-99b1f5d7edcf.png)

Anyhow, the Iosevkas of `2.1.0` (and even `2.2.0 RC`) are broken because of a `fontforge` bug.
We need to repatch with _March 2022 Release_. See #742 and the fix in ff.

**Comment by Finii** [comment]
Hmm, the images are generated by https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/generate-font-image-previews.sh

and the image is ok if using the `2.1.0` release font

![image](https://user-images.githubusercontent.com/16012374/178827957-a9660697-fce9-4040-b662-1da41da8bbb8.png)

Strange.

Hmm, and the current images have been regenerated just after `2.1.0` came out, 3 years ago:
https://github.com/ryanoasis/nerd-fonts/tree/gh-pages/assets/img/previews

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/179358395-d94d4654-29bf-4aaf-9285-85a56cb0784b.png)

Thanks again for reporting.
