### ISSUE TITLE
0x2665 and 0x26a1

### ISSUE THREAD

**Issue by minerva1129** [ryanoasis/nerd-fonts#87]
(I'm afraid my English may be hard to read, sorry...)
I want to use "heart(0x2665)" and "zap(0x26a1)" character, they are from octicons.
However, I can't find them in patched-fonts, but they exists in glyph-source-fonts/octicons.tff ...

**Comment by ryanoasis** [comment]
No worries (and by the way I can read it just fine :smile:)

At first I thought this was likely due to the conflict between Octicons and Font Awesome ranges used (see: https://github.com/ryanoasis/nerd-fonts/blob/master/font-patcher#L215-L216)

However the Unicode points you mention are very different than most of Octicons (`f000` and above)

It **definitely** looks like you have found a bug because right now the [patcher](https://github.com/ryanoasis/nerd-fonts/blob/master/font-patcher#L251-L252) is only taking into account Octicons from range `f000` to `f0db`

Another one that seems to be missing as well is [device-desktop `f27c`](https://octicons.github.com/icon/device-desktop/)

--

**Question:** By the way are you using a 'complete' version font or just a variation with Octicons?

On the 'complete' version the Octicons glyph points do change because of the conflict with Font Awesome mentioned above^ so just something to keep in mind as well

**Comment by minerva1129** [comment]
I'm using complete version. I did with `--fontawesome --fontlinux --octicons --pomicons --powerline --powerlinextra`.

**Comment by ryanoasis** [comment]
Thanks

**Comment by ryanoasis** [comment]
This will more than likely be the next thing to be released.

**Comment by ryanoasis** [comment]
I was expecting to get to this quickly before v0.9.0 but that just didn't happen. Since I want to release v0.9.0 soon it makes to move this fix there.

A full rebuild of all fonts is needed anyway for this fix

**Comment by ryanoasis** [comment]
@minerva1129 This is fixed in [0.9.0 branch](https://github.com/ryanoasis/nerd-fonts/tree/0.9.0/patched-fonts). Please give it a try if you can thanks. I will merge to master when ready
