### ISSUE TITLE
Add Mononoki Font

### ISSUE THREAD

**Issue by praveenpuglia** [ryanoasis/nerd-fonts#89]
I absolutely love this and it's also available on GitHub. Can this be made part of the project please?

http://madmalik.github.io/mononoki/

**Comment by ryanoasis** [comment]
@praveenpuglia Yes, yes it can :smile: 

I just checked the license, so far so good.

One thing to be careful on is the Reserved Font Name. It looks like it was previously called "monoOne" and only that name is explicitly reserved in the license. I will probably ask about this.

**Comment by guiceolin** [comment]
Hello there!

Any progress on this?
there is any way to help?

**Comment by ryanoasis** [comment]
@guiceolin 
Hey thanks for pinging.

> Any progress on this?

No but you did remind me to open an [issue regarding the license](https://github.com/madmalik/mononoki/issues/46).

The main concerns now are the license and just checking that all the glyphs look at least decent.

> there is any way to help?

Yes possibly, see [the instructions for adding a new font](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md#adding-a-new-font). Hopefully it is clear but might not be for the uninitiated.

---

This project has been a bit neglected lately and that is my fault but I hope to get back into contributing within a few weeks. I have added some trusted contributors so at least some of the smaller things could be merged in without me.

I had wanted to fix issues over enhancements but I might reconsider because adding a new font is relatively easy compared to fixing some of the glyph positioning issues
